window.gameTitleMap = {
  "games/cl1.html": "1",
  "games/cl10minutestildawn.html": "10 Minutes Till Dawn",
  "games/cl10morebullets.html": "10 More Bullets",
  "games/cl12minibattles.html": "12 Mini Battles",
  "games/cl1on1soccer.html": "1 on 1 Soccer",
  "games/cl1v1tennis.html": "1 on 1 Tennis",
  "games/cl2048.html": "2048",
  "games/cl2048cupcakes.html": "2048 Cupcakes",
  "games/cl234playergame.html": "TwoPlayerGames 2 3 4 Player",
  "games/cl2Dshooting.html": "Shooter 2D Online",
  "games/cl3pandas.html": "3 Pandas",
  "games/cl3pandasbrazil.html": "3 Pandas Brazil",
  "games/cl3pandasfantasy.html": "3 Pandas Fantasy",
  "games/cl3pandasjapan.html": "3 Pandas Japan",
  "games/cl3pandasnight.html": "3 Pandas Night",
  "games/cl3slices2.html": "3 Slices 2",
  "games/cl4thandgoal.html": "4th and Goal 2022",
  "games/cl500calibercontractz.html": "500 Caliber Contractz",
  "games/cl60secondsburgerrun.html": "60 Seconds Burger Run",
  "games/cl8ballclassic.html": "8 Ball Billiards Classic",
  "games/cl8ballpool.html": "8 Ball Pool",
  "games/cl9007199254740992.html": "9007199254740992",
  "games/cl99balls.html": "99 Balls",
  "games/cl99nightsitf.html": "99 Nights in the Forest",
  "games/clabsolutemadness.html": "Absolute Madness",
  "games/clacecombat2.html": "Ace Combat 2",
  "games/clacecombat3.html": "Ace Combat 3 - Electrosphere",
  "games/clacegangstertaxi.html": "Ace Gangster Taxi",
  "games/clachievementunlocked.html": "Achievement Unlocked",
  "games/clachievmentunlocked2.html": "Achievement Unlocked 2",
  "games/clachievmentunlocked3.html": "Achievement Unlocked 3",
  "games/clachillies2.html": "Achilles 2",
  "games/clADarkRoom.html": "A Dark Room",
  "games/cladatewithdeath.html": "A Date with Death",
  "games/cladayintheoffice.html": "A Day in the Office",
  "games/clADOFAI.html": "A Dance of Fire and Ice",
  "games/cladvancewars.html": "Advance Wars",
  "games/cladvancewars2.html": "Advance Wars 2",
  "games/cladventneon.html": "AdventNEON",
  "games/clAdventureCapatalist.html": "Adventure Capitalist",
  "games/clagariolite.html": "Agar.io Lite",
  "games/clageofwar.html": "Age of War",
  "games/clageofwar2.html": "Age of War 2",
  "games/clagesofconflict.html": "game",
  "games/clahoysurvival.html": "Ahoy Survival",
  "games/clakoopasrevenge2.html": "A Koopa’s Revenge 2",
  "games/clakumanorgaiden.html": "Akumanor Gaiden",
  "games/clalienhominid.html": "Alien Hominid",
  "games/clalienhominidgba.html": "Alien Hominid",
  "games/clalienskyinvasion.html": "Alien Sky Invasion - FreezeNova",
  "games/clalientransporter.html": "Alien Transporter",
  "games/clalienvspredator.html": "Alien Vs. Predator",
  "games/clallbossesin1.html": "Paper Mario All Bosses in 1 Battle",
  "games/clallocation.html": "PICO-8 Cartridge",
  "games/clamidstthesky.html": "Amidst the Clouds",
  "games/clamigopancho.html": "Amigo Pancho",
  "games/clamigopancho2.html": "Amigo Pancho 2",
  "games/clamigopancho3.html": "Amigo Pancho 3",
  "games/clamigopancho4.html": "Amigo Pancho 4",
  "games/clamigopancho5.html": "Amigo Pancho 5",
  "games/clamigopancho6.html": "Amigo Pancho 6",
  "games/clamigopancho7.html": "Effing Worms",
  "games/clamongus.html": "Among Us",
  "games/clamorphous.html": "Amorphous +",
  "games/clancientsins.html": "Ancient Sins",
  "games/clangry-birdsspace.html": "Angry Birds Space",
  "games/clangrybirds.html": "Angry Birds",
  "games/clangrybirdsshowdown.html": "CoolGames",
  "games/clanimalcrossingwildworld.html": "Animal Crossing - Wild World",
  "games/clanotherworld.html": "Another World",
  "games/clantimatterdimensions.html": "Antimatter Dimensions",
  "games/clapotris.html": "Apotris",
  "games/clappleshooter.html": "Apple Shooter",
  "games/clappleworm.html": "Apple Worm",
  "games/claquaparkio.html": "Aquapark IO Unblocked",
  "games/clarceuslegend.html": "Pokemon Arceus Legend",
  "games/clarcheryworldtour.html": "Archery World Tour",
  "games/clarmormayhem2.html": "Armor Mayhem 2",
  "games/clarsonate.html": "ARSONATE",
  "games/clarthursnightmare.html": "Arthur’s Nightmare",
  "games/clascent.html": "PICO-8 Cartridge",
  "games/clasmallworldcup.html": "A Small World Cup",
  "games/classesmentexaminationque.html": "Reality",
  "games/clasteroids.html": "Asteroids",
  "games/clasteroidsALT.html": "Asteroids Game in WebAssembly",
  "games/clavalanche.html": "Avalanche",
  "games/claviamastersbuggy.html": "Aviamasters",
  "games/clAwesomePirates.html": "Awesome Pirates",
  "games/clawesomeplanes.html": "Awesome Planes",
  "games/clawesometanks.html": "Awesome Tanks",
  "games/clawesometanks2.html": "Awesome Tanks 2",
  "games/clB3313.html": "b3313",
  "games/clbabeltower.html": "Babel Tower",
  "games/clbabychiccoadventure.html": "Baby Chicco Adventures",
  "games/clbabykaizo.html": "Baby Kaizo World",
  "games/clbabysniperinvietnam.html": "Baby Sniper in Vietnam",
  "games/clbackrooms.html": "Backrooms",
  "games/clbackrooms2D.html": "Backrooms 2 D",
  "games/clbackyardbaseball.html": "Backyard Baseball",
  "games/clbackyardbaseball09.html": "Backyard Baseball ‘09",
  "games/clbackyardbaseball10.html": "Backyard Baseball ‘10",
  "games/clbackyardfootball.html": "Backyard Football",
  "games/clbackyardsoccer.html": "Backyard Soccer",
  "games/clbaconmaydie.html": "Bacon May Die by SnoutUp",
  "games/clbadbodyguards.html": "guard",
  "games/clbadicecream.html": "Bad Ice Cream",
  "games/clbadmondaysimulator.html": "Created with GameMaker: Studio",
  "games/clbadparenting.html": "Bad Parenting",
  "games/clbadpiggies.html": "Bad Piggies",
  "games/clbadtimesim.html": "Bad Time Simulator (Sans Fight)",
  "games/clbalatrogba.html": "Balatro",
  "games/clbaldidecomp.html": "Baldi's Basics The Ultra Decompile",
  "games/clbaldisbasics.html": "Baldi's Basics",
  "games/clbaldisbasicsremaster.html": "Baldi’s Basics Remastered",
  "games/clbaldisfunnewschoolultimate.html": "Baldi’s Fun New School Ultimate",
  "games/clballblast.html": "Ball Blast HTML5",
  "games/clballsandbricksgood.html": "Balls and Bricks",
  "games/clballz.html": "BallZ | Unblocked on CCPorted",
  "games/clbananasimulator.html": "banana simulator",
  "games/clbanditgunslingers.html": "Bandit Gunslingers",
  "games/clbanjokazooie.html": "Banjo Kazooie",
  "games/clbanjotooie.html": "Banjo Tooie",
  "games/clbankrobbery2.html": "Bank Robbery 2",
  "games/clbarryhasasecret.html": "Barry Has a Secret",
  "games/clbas.html": "PICO-8 Cartridge",
  "games/clbaseballbros.html": "BASEBALL BROS! | Official Site",
  "games/clbasketballfrvr.html": "Play Basketball FRVR - Free Basketball Hoop Shooter",
  "games/clbasketballlegends.html": "Basketball Legends 2020",
  "games/clbasketballstars.html": "Basketball Stars",
  "games/clbasketbattle.html": "YT Game Wrapper WebGL Template",
  "games/clbasketbros.html": "Basket Bros",
  "games/clbasketrandom.html": "Basket Random",
  "games/clbasketslamdunk2.html": "Basket Slam Dunk 2",
  "games/clbatterup.html": "Batter Up!",
  "games/clbattlekarts.html": "Battle Karts",
  "games/clbattles.html": "Battles",
  "games/clbattlesim.html": "Battle Simulator",
  "games/clbattlezone.html": "Battle Z One",
  "games/clbballlegend.html": "Basketball Legends",
  "games/clbeachboxingsim.html": "Beach Boxing Simulator - Poki",
  "games/clbeamrider.html": "Beamrider",
  "games/clbearbarians.html": "Bearbarians",
  "games/clbearsus.html": "Bearsus",
  "games/clben10alienforce.html": "Ben 10 Alien Force",
  "games/clben10omniverse.html": "Ben 10 - Omniverse",
  "games/clben10protector.html": "Ben 10 Protector of Earth",
  "games/clben10racing.html": "Ben 10 Galactic Racing",
  "games/clben10ultimatealien.html": "Ben 10 - Ultimate Alien - Cosmic Destruction",
  "games/clbergentruck201x.html": "BERGENTRUCK_201X",
  "games/clbfdia5b.html": "HTML5b - Battle for Dream Island",
  "games/clBig_Time_Butter_Baron.html": "Effing Worms",
  "games/clbigicetowertinysquare.html": "Big Ice Tower Tiny Square",
  "games/clbigneontowertinysquare.html": "Big NEON Tower vs Tiny Square",
  "games/clbigshotboxing2.html": "Big Shot Boxing",
  "games/clbindingofisaccsheeptime.html": "Binding of Isaac Wrath of the Lamb",
  "games/clbioevil4.html": "Bio Evil 4",
  "games/clbitlife.html": "BitLife - Life Simulator",
  "games/clbitplanes.html": "Bit Planes",
  "games/clblackjack.html": "Blackjack",
  "games/clblackjackbattle.html": "Blackjack Battle",
  "games/clblackjackhhhh.html": "BLACKJACK",
  "games/clblacksmithlab.html": "Blacksmith Lab",
  "games/clblastronaut.html": "Blastronaut",
  "games/clblazedrifter.html": "Blaze Drifter",
  "games/clbleachvsnaruto.html": "Bleach Vs. Naruto",
  "games/clblightborne.html": "Blightborne",
  "games/clblobsstory2.html": "Blob’s Story 2",
  "games/clblockblast.html": "Block Blast Puzzle",
  "games/clblockcraftparkour.html": "Minecraft Parkour",
  "games/clblockcraftshooter.html": "Minecraft Shooter",
  "games/clblockpost.html": "Blockpost - Poki",
  "games/clblockthepig.html": "Block the Pig",
  "games/clblockydemolitionderby.html": "Windows",
  "games/clblockysnakes.html": "Blocky Snakes",
  "games/clbloodmoney.html": "BLOODMONEY!",
  "games/clbloodtournament.html": "Blood Tournament",
  "games/clbloons.html": "Bloons",
  "games/clbloons2.html": "Bloons 2",
  "games/clbloonspp1.html": "Bloons Player Pack 1",
  "games/clbloonspp2.html": "Bloons Player Pack 2",
  "games/clbloonspp3.html": "Bloons Player Pack 3",
  "games/clbloonspp4.html": "Bloons Player Pack 4",
  "games/clbloonspp5.html": "Bloons Player Pack 5",
  "games/clbloonsTD1.html": "BTD 1",
  "games/clbloonsTD2.html": "BTD 2",
  "games/clbloonsTD3.html": "BTD 3",
  "games/clbloonsTD4.html": "BTD 4",
  "games/clbloonsTD6scratch.html": "Bloons TD6",
  "games/clbloxorz.html": "Bloxorz",
  "games/clblumgiracers.html": "Blumgi Racers",
  "games/clblumgirocket.html": "Blumgi Rocket",
  "games/clBMX2.html": "Mat Hoffman's Pro BMX 2",
  "games/clbobtherobber.html": "Bob the Robber",
  "games/clbobtherobber2.html": "Bob the Robber 2",
  "games/clbobtherobber5.html": "Bob the Robber 5",
  "games/clbomberman.html": "Bomberman",
  "games/clbomberman2.html": "Bomberman 2",
  "games/clbombermanhero.html": "Bomberman Hero",
  "games/clbombermanworld.html": "super bomb",
  "games/clboomslingers.html": "Boom Slingers",
  "games/clbottlecracks.html": "Bottle Cracks",
  "games/clbounceback.html": "Bounce Back",
  "games/clbouncemasters.html": "Bouncemasters",
  "games/clbouncybasketball.html": "Bouncy Basketball",
  "games/clbouncymotors.html": "Bouncy Motors",
  "games/clBountyOfOne.html": "Bounty of One",
  "games/clbowmaster.html": "Bowmasters",
  "games/clboxhead2playrooms.html": "Boxhead 2 Play Rooms",
  "games/clboxheadnightmare.html": "Boxhead Nightmare",
  "games/clboxinglive-2.html": "Boxing Live 2",
  "games/clboxingrandom.html": "Boxing Random",
  "games/clbrainrot.html": "Also Steal a Brainrot",
  "games/clbridgerace.html": "Crossy Road",
  "games/clbtd5.html": "BTD 5",
  "games/clbtts.html": "Big Tower Tiny Square",
  "games/clbtts2.html": "Big Tower Tiny Square 2",
  "games/clbubbleshooter.html": "Bubble Shooter",
  "games/clbubbleshooterpirate.html": "Bubble Shooter Pirate",
  "games/clbubbletanks.html": "Bubble Tanks",
  "games/clbubbletanks2.html": "Bubble Tanks 2",
  "games/clbubbletanks3.html": "Bubble Tanks 3",
  "games/clbubbletanksarenas.html": "Bubble Tanks Arenas",
  "games/clbubbletankstd.html": "Bubble Tanks Tower Defense",
  "games/clbubsy.html": "Bubsy",
  "games/clbuildnowgg.html": "Build Now.gg",
  "games/clbunnyland.html": "BunnyLand",
  "games/clburgerandfrights.html": "Burger and Frights",
  "games/clburritobison.html": "Burrito Bison",
  "games/clburritobisonlaunchalibre.html": "Burrito Bison",
  "games/clburritobisonrevenge.html": "Burrito Bison Revenge",
  "games/clbushidoblade.html": "Bushido Blade",
  "games/clcactusmccoy.html": "Cactus Mccoy",
  "games/clcactusmccoy2.html": "Cactus Mccoy 2",
  "games/clcannonballs3d.html": "Cannon Balls 3D",
  "games/clcannonfodder.html": "Cannon Fodder",
  "games/clcaptainlang.html": "Captain Lang",
  "games/clcapybaraclicker.html": "Capybara Clicker",
  "games/clcarcrash3.html": "CarCrashTest",
  "games/clcardrawing.html": "Car Drawing",
  "games/clcareatscar2deluxe.html": "Car Eats Car 2 Deluxe",
  "games/clcarkingarena.html": "Car King Arena",
  "games/clCartoonNetworkTableTennisUltimateTournament.html": "Table Tennis Ultimate Tournament",
  "games/clcastlebloodline.html": "Castlevania Bloodlines",
  "games/clcastlecircleofmoon.html": "Castlevania Circle of the Moon",
  "games/clcastlevania.html": "Castlevania",
  "games/clcastlevania2.html": "Castlevania 2",
  "games/clcastlevania3.html": "Castlevania 3",
  "games/clcastlevaniadawnofsorrow.html": "Resident Evil",
  "games/clcastlevanianes.html": "Castlevania",
  "games/clcastlewarsmodern.html": "Castel Wars Modern",
  "games/clcatmario.html": "Cat Mario (flash)",
  "games/clcatmariogood.html": "Open Syobon Action",
  "games/clcatslovecake2.html": "Cats Love Cake 2",
  "games/clcavestory.html": "Cave Story",
  "games/clceleste.html": "PICO-8 Cartridge",
  "games/clceleste2.html": "PICO-8 Cartridge",
  "games/clcellardoor.html": "Cellar Door",
  "games/clchainofmemories.html": "Kingdom Hearts Chain of Memories",
  "games/clchaosfaction2.html": "Chaos Faction 2",
  "games/clcheckers.html": "Checkers",
  "games/clcheesechompers3d.html": "google.com",
  "games/clcheshireinachatroom.html": "PICO-8 Cartridge",
  "games/clchess.html": "Chess",
  "games/clchessclassic.html": "Chess Classic",
  "games/clchibiknight.html": "Chibi Knight",
  "games/clchickenscream.html": "Chicken Scream",
  "games/clchickenwar.html": "Chicken War",
  "games/clchipschallenge.html": "Chip’s Challenge",
  "games/clchoppyorc.html": "Choppy Orc",
  "games/clchronotrigger.html": "Chrono Trigger",
  "games/clchuzzle.html": "Chuzzle",
  "games/clCircloO2.html": "circloO 2 Unblocked - ubg235 Poki",
  "games/clciviballs.html": "Civiballs",
  "games/clciviballs2.html": "Civiballs 2",
  "games/clclashofvikings.html": "Clash Of Vikings",
  "games/clclassof09.html": "Class of '09",
  "games/clcleanupio.html": "Cleanup.io",
  "games/clclearvision.html": "Clear Vision",
  "games/clclearvision2.html": "Clear Vision 2",
  "games/clclearvision3.html": "Clear Vision 3",
  "games/clclearvision4.html": "Clear Vision 4",
  "games/clclearvision5.html": "Clear Vision 5",
  "games/clclmadnessambulation.html": "Madness Ambulation",
  "games/clclubbytheseal.html": "Club by the Seal",
  "games/clclusterrush.html": "Cluster Rush",
  "games/clcoalllcdemo.html": "Coal LLC",
  "games/clcod4.html": "Call of Duty 4 - Modern Warfare",
  "games/clcodblackopp.html": "Call of Duty - Black Ops",
  "games/clcoddefiance.html": "Call of Duty - Modern Warfare 3 - Defiance",
  "games/clcodenamegordon.html": "Codename Gordon",
  "games/clcodmodernwarfare.html": "Call of Duty - Modern Warfare 3 - Defiance",
  "games/clcodworldatwar.html": "Call of Duty - World at War",
  "games/clcoffeemaker.html": "PICO-8 Cartridge",
  "games/clcombopool.html": "PICO-8 Cartridge",
  "games/clcommandandconquer.html": "Command and Conquer",
  "games/clcommanderkeen4.html": "Commander Keen 4",
  "games/clcommanderkeen5.html": "Commander Keen 5",
  "games/clcommanderkeen6.html": "Commander Keen 6",
  "games/clconkersbadfurday.html": "Conker's Bad Fur Day",
  "games/clcontra.html": "Contra",
  "games/clcontra3.html": "Contra III the Alien Wars",
  "games/clcookie-clicker.html": "Cookie Clicker",
  "games/clcookingmama.html": "Cooking Mama",
  "games/clcookingmama2.html": "Cooking Mama 2",
  "games/clcookingmama3.html": "Cooking Mama 3 - Shop & Chop",
  "games/clcoreball.html": "Core Ball，Level 4",
  "games/clcotlk.html": "PICO-8 Cartridge",
  "games/clcoverorange.html": "Cover Orange",
  "games/clcoverorange2.html": "Cover Orange 2",
  "games/clcoverorangejourneygangsters.html": "Cover Orange Journey Gangsters",
  "games/clcoverorangejourneyknights.html": "Cover Orange Journey Knights",
  "games/clcoverorangejourneypirates.html": "Cover Orange Journey Pirates",
  "games/clcoverorangejourneyspace.html": "Cover Orange Journey Space",
  "games/clcoverorangeplayerspack.html": "Cover Orange Players Pack",
  "games/clcoverorangeplayerspack2.html": "Cover Orange Players Pack 2",
  "games/clcrankit!.html": "Crank It!",
  "games/clcrashbandicoot.html": "Crash Bandicoot",
  "games/clcrashbandicoot2.html": "Crash Bandicoot 2",
  "games/clcrashteamracing.html": "Crash Team Racing",
  "games/clcrazycars.html": "Crazy Cars! Unblocked",
  "games/clcrazycattle3d.html": "CrazyCattle3D",
  "games/clcrazychicken3D.html": "CrazyChicken3D Remaster",
  "games/clcrazyfrogracer.html": "Crazy Frog Racer",
  "games/clcrazymotorcycle.html": "Crazy Motorcycle",
  "games/clcreaturecardidle.html": "Creature Card Idle",
  "games/clcreeperworld2.html": "Creeper World 2",
  "games/clcrossyroad.html": "Crossy Road",
  "games/clcrunchball3000.html": "C Run Ch Ball 3000",
  "games/clcs1.6.html": "C.S 1.6",
  "games/clcsds.html": "Counter Strike DS",
  "games/clcsgoclicker.html": "CS:GO Clicker",
  "games/clctgpnitro.html": "CTGP Nitro",
  "games/clcurveball.html": "Curve Ball",
  "games/clcuttherope.html": "Cut the Rope",
  "games/clcyberbungracing.html": "Cyberbung Racing",
  "games/clcybersensation.html": "FNF: Cyber Sensation (Friday Night Funkin')",
  "games/cldadgame.html": "Dadgame",
  "games/cldadnme.html": "Dad N Me",
  "games/cldandysworldclicker.html": "Dandy's World Clicker",
  "games/cldanktomb.html": "PICO-8 Cartridge",
  "games/cldborigins.html": "Dragon Ball - Origins",
  "games/cldborigins2.html": "Dragon Ball - Origins 2",
  "games/cldbsniper.html": "Double Barrel Sniper",
  "games/cldbzattacksaiyans.html": "Dragon Ball Z - Attack of the Saiyans",
  "games/cldbzdevolution.html": "Dragon Ball Z Devolution",
  "games/cldbzsuperwarriorssonic.html": "Dragon Ball Z Supersonic Warriors",
  "games/cldbzwarriors2.html": "dbz warriors 2",
  "games/cldeadestate.html": "Made in GameMaker Studio 2",
  "games/cldeadlydescent.html": "Deadly Descent",
  "games/cldeadplate.html": "DEAD PLATE",
  "games/cldeadzed.html": "Effing Worms",
  "games/cldeadzed2.html": "Dead Zed 2",
  "games/cldeathchase.html": "Death Chase",
  "games/cldeblob2.html": "de Blob 2",
  "games/cldecision.html": "Decision",
  "games/cldecision2.html": "Decision 2",
  "games/cldecision3.html": "Decision 3",
  "games/cldecisionmedieval.html": "Decision Medieval",
  "games/cldeepersleep.html": "Deeper Sleep",
  "games/cldeepestsword.html": "Deepest Sword",
  "games/cldefendyourcastle.html": "Defend Your Castle",
  "games/cldefendyournuts.html": "Defend Your Nuts",
  "games/cldefendyournuts2.html": "Defend Your Nuts 2",
  "games/cldeltarune.html": "Deltarune",
  "games/cldeltatraveler.html": "Unity Web Player | DELTATRAVELER",
  "games/cldementium.html": "Dementium - The Ward",
  "games/cldemolitionderbycrashracing.html": "Demolition Derby Crash Racing",
  "games/cldemonbluff.html": "Demon Bluff",
  "games/cldiablo.html": "Diablo",
  "games/cldiamondhollow.html": "Diamond Hollow",
  "games/cldiamondhollow2.html": "Diamond Hollow 2",
  "games/cldiddykong-racing.html": "Diddy Kong Racing",
  "games/cldieinthedungeon.html": "Die in the Dungeon",
  "games/cldigdug.html": "Dig Dug",
  "games/cldigdug2.html": "Dig Dug 2",
  "games/cldigdug26.html": "Dig Dug",
  "games/cldigtochina.html": "Dig to China",
  "games/cldinodudes.html": "Evolution Dino Dudes",
  "games/cldiredecks.html": "dire dicks",
  "games/cldoblox.html": "google.com",
  "games/cldogeminer.html": "Dogeminer",
  "games/cldogeminer2.html": "Dogeminer 2 Unblocked - GNHUSTGames",
  "games/cldokidokiliteratureclub.html": "Doki Doki Literature Club! (Ren'Py Mod)",
  "games/cldonkeykong.html": "Donkey Kong",
  "games/cldonkeykong64.html": "Donkey Kong 64",
  "games/cldonkeykongcountry.html": "Donkey Kong Country",
  "games/cldonkeykongcountry2.html": "Donkey Kong Country 2",
  "games/cldonkeykongcountry3.html": "Donkey Kong Country 3",
  "games/cldonkeykongnes.html": "Donkey Kong",
  "games/cldontescape.html": "Don't Escape",
  "games/cldontescape2.html": "Don't Escape 2",
  "games/cldontescape3.html": "Don't Escape 3",
  "games/cldoodlejumpgoober.html": "CodePen - A Pen by bound20",
  "games/cldoom.html": "Doom",
  "games/cldoom2.html": "Doom 2",
  "games/cldoom2d.html": "Doom 2 D",
  "games/cldoom2dDOS.html": "Doom 2 D",
  "games/cldoom2dos.html": "Doom 2",
  "games/cldoom3pack.html": "Doom Triple Pack",
  "games/cldoom64.html": "Doom 64",
  "games/cldoomdos.html": "Doom",
  "games/cldoomemscripten.html": "DOOM",
  "games/cldoomps.html": "Doom",
  "games/cldoomzio.html": "Doomz.io",
  "games/cldouchebaglife.html": "Douchebag Life",
  "games/cldragonballadvance.html": "Dragon Ball Advanced Adventure",
  "games/clDragonBallZTheLegacyofGoku.html": "Dragon Ball Z the Legacy of Goku",
  "games/clDragonQuestIX.html": "Dragon Quest IX - Sentinels of the Starry Skies",
  "games/cldrawclimber.html": "Draw Climber",
  "games/cldrawntolife.html": "Drawn to Life",
  "games/cldrawntolife2.html": "triple T's favorite game",
  "games/cldrawtheline.html": "YT Game Wrapper WebGL Template",
  "games/cldreader.html": "Dreader",
  "games/cldreadheadparkour.html": "Dreadhead Parkour",
  "games/cldriftboss.html": "Drift Boss",
  "games/cldrifthuntersmerge.html": "Google",
  "games/cldrivemady.html": "Drive Mad",
  "games/cldrivenwild.html": "Driven Wild! 🚗🌴",
  "games/cldrmario.html": "Dr. Mario",
  "games/cldrweedgaster.html": "Clickteam Fusion Developer 2.5+ HTML5 Runtime",
  "games/cldubstep.html": "Crazy Crash Landing",
  "games/clduckhunt.html": "Duck Hunt",
  "games/clducklfe5.html": "Duck Life 5",
  "games/clducklife.html": "Duck Life",
  "games/clducklife2.html": "Duck Life 2",
  "games/clducklife3.html": "Duck Life 3",
  "games/clducklife4.html": "Duck Life 4",
  "games/clducklifebattle.html": "Duck Life Battle",
  "games/clducklifespace.html": "Wix Games | Duck Life: Space",
  "games/clducklingsio.html": "Ducklings",
  "games/clducktales.html": "Ducktales",
  "games/cldud.html": "DUD",
  "games/cldukenukem3d.html": "Duke Nukem 3D",
  "games/cldumpling.html": "Dumpling",
  "games/cldungeondeck.html": "Dungeon Deck",
  "games/cldungeonraid.html": "DungeonRaid",
  "games/cldungeonsanddegenerategamblers.html": "Dungeons & Degenerate Gamblers",
  "games/cldunkshot.html": "Dunk Shot",
  "games/clduskchild.html": "PICO-8 Cartridge",
  "games/cldyingdreams.html": "Game",
  "games/cldynamiteheaddy.html": "Dynamite Headdy",
  "games/cleagleride.html": "Eagle Ride Unblocked - ubg235 Poki",
  "games/clearntodie.html": "Earn to Die",
  "games/clearntodie2.html": "Earn to Die 2",
  "games/clearthbound.html": "Earthbound",
  "games/clearthbound3.html": "Earthbound 3",
  "games/clearthboundsnes.html": "Earthbound",
  "games/clearthtaken.html": "Earth Taken",
  "games/clearthtaken2.html": "Earth Taken 2",
  "games/clearthtaken3.html": "Earth Taken 3",
  "games/clearthwormjim.html": "Earthworm Jim",
  "games/clearthwormjim2.html": "Earthworm Jim 2",
  "games/cledelweiss.html": "Edelweiss",
  "games/cledyscarsimulator.html": "Edys Car Simulator",
  "games/cleffinghail.html": "Effing Hail",
  "games/cleffingmachines.html": "Effing Machines",
  "games/cleffingworms.html": "Effing Worms",
  "games/cleffingzombies.html": "Effing Zombies",
  "games/clegg.html": "Egg",
  "games/cleggycar.html": "Eggy Car",
  "games/clelasticface.html": "Elastic Face",
  "games/clelectricman2.html": "Electricman 2",
  "games/clemujs.html": "EmulatorJS | Demo",
  "games/clenchain.html": "Enchain",
  "games/clendlesswar4.html": "Endless War 4",
  "games/clendlesswar5wow.html": "Endless War 5",
  "games/clendlesswar7.html": "Endless War 7",
  "games/clenduro.html": "Enduro",
  "games/clepicbattlefantasy5.html": "Epic Battle Fantasy 5",
  "games/clescalatingduel.html": "EscalatingDuel",
  "games/clescaperoad-2.html": "Escape-Road-2",
  "games/clescaperoad.html": "Escape Road",
  "games/clet.html": "E.T. the Extra Terrestrial",
  "games/cletrianoddyssey.html": "Etrian Odyssey",
  "games/clevilglitch.html": "Evil Glitch",
  "games/clevolution.html": "Evolution",
  "games/clexcitebike64.html": "Excitebike 64",
  "games/clexoobservation.html": "Exoplanet Observation",
  "games/clfactoryballs.html": "Factory Balls",
  "games/clfactoryballs2.html": "Factory Balls 2",
  "games/clfactoryballs3.html": "Factory Balls 3",
  "games/clfactoryballs4.html": "Factory Balls 4",
  "games/clfairytalevsonepiece.html": "Fairy Tale Vs. One Piece",
  "games/clfallguys.html": "Stumble Guys",
  "games/clfallout.html": "Fallout",
  "games/clfamidash.html": "Famidash",
  "games/clfancypantsadventure.html": "Fancy Pants Adventure",
  "games/clfancypantsadventure2.html": "Fancy Pants Adventure 2",
  "games/clfancypantsadventure3.html": "Fancy Pants Adventure World 3",
  "games/clfancysnowboarding.html": "Fancy Snowboarding",
  "games/clfashionbattle.html": "Fashion Battle",
  "games/clfattygenius.html": "Fatty Genius",
  "games/clfeedus2.html": "Feed Us 2",
  "games/clfeedus3.html": "Feed Us 3",
  "games/clfeedus4.html": "Feed Us 4",
  "games/clfeedus5.html": "Feed Us 5",
  "games/clFF3.html": "Final Fantasy III",
  "games/clff6.html": "Final Fantasy VI",
  "games/clffmysticquest.html": "Final Fantasy Mystic Quest",
  "games/clFFsonic1.html": "Final Fantasy Sonic X Episode 1",
  "games/clFFsonic2.html": "Final Fantasy Sonic X Episode 2",
  "games/clFFsonic3.html": "Final Fantasy Sonic X Episode 3",
  "games/clFFsonic4.html": "Final Fantasy Sonic X Episode 4",
  "games/clFFsonic5.html": "Final Fantasy Sonic X Episode 5",
  "games/clFFsonic61.html": "Final Fantasy Sonic X Episode 6 Part 1",
  "games/clFFsonic62.html": "Final Fantasy Sonic X Episode 6 Part 2",
  "games/clFIFA07.html": "FIFA 07",
  "games/clFIFA10.html": "FIFA 10 (Europe)",
  "games/clFIFA11.html": "FIFA Soccer 11",
  "games/clfifa2000.html": "FIFA 2000",
  "games/clFIFA99.html": "FIFA 99",
  "games/clFIFAinternationalsoccer.html": "FIFA International Soccer",
  "games/clFIFAroadtoworldcup98.html": "FIFA Road to World Cup 98",
  "games/clFIFAsoccer06.html": "FIFA Soccer 06",
  "games/clFIFAsoccer95.html": "FIFA Soccer 95",
  "games/clFIFAsoccer96.html": "FIFA Soccer 96",
  "games/clFIFAsoccer97.html": "FIFA Soccer 97",
  "games/clFIFAstreet2.html": "FIFA Street 2",
  "games/clfinalearth2.html": "The Final Earth 2",
  "games/clfinalfantasy.html": "Final Fantasy",
  "games/clfinalfantasyII.html": "Final Fantasy II",
  "games/clfinalfantasytactics.html": "Final Fantasy Tactics",
  "games/clfinalfantasyVII.html": "Final Fantasy VII (disc One)",
  "games/clfinalfantasyVIId2.html": "Final Fantasy VII (disc Two)",
  "games/clfinalfantasyVIId3.html": "Final Fantasy VII (disc Three)",
  "games/clfinalninja.html": "Final Ninja",
  "games/clfindthealien.html": "Find the Alien",
  "games/clfireblob.html": "Fireblob",
  "games/clfireboyandwatergirl.html": "Fireboy and Watergirl",
  "games/clfireboyandwatergirl2.html": "Fireboy & Watergirl 2 Light Temple",
  "games/clfireboyandwatergirl3.html": "Fireboy & Watergirl 3 Ice Temple",
  "games/clfireemblem.html": "Fire Emblem",
  "games/clfisheatgettingbig.html": "FishEatGettingBig",
  "games/clfisquarium.html": "Fisquarium",
  "games/clfivenightsatbaldisredone.html": "Five Nights at Baldis Redone",
  "games/clflashsonic.html": "Ultimate Flash Sonic",
  "games/clfloodrunner.html": "Flood Runner",
  "games/clfloodrunner2.html": "Flood Runner 2",
  "games/clfloodrunner4.html": "Flood Runner 4",
  "games/clfluidism.html": "WebGL Fluid Simulation",
  "games/clfnac1.html": "Five Nights at Candy's 1",
  "games/clfnac2.html": "Five Nights at Candy's 2",
  "games/clFNAF.html": "Five Nights at Freddy's 1",
  "games/clFNAF2.html": "Five Nights at Freddy's 2",
  "games/clFNAF3.html": "Five Nights at Freddy's 3",
  "games/clFNAF4.html": "Five Nights at Freddy's 4",
  "games/clfnaf4halloween.html": "Five Nights at Freddy's 4 Halloween",
  "games/clfnafps.html": "Five Nights at Freddy's Pizzeria Simulator",
  "games/clfnafsl.html": "Five Nights at Freddy's Sister Location",
  "games/clfnafucn.html": "Five Nights at Freddy's UCN",
  "games/clfnafworldd.html": "Five Nights at Freddy's World",
  "games/clfnaw.html": "Five Nights at Winston's",
  "games/clfnfagoti.html": "Game 24964",
  "games/clfnfanimation.html": "Game 24848",
  "games/clfnfannie.html": "Game 24951",
  "games/clfnfbelowdepths.html": "Game 22741",
  "games/clfnfbfdi26.html": "Game 28671",
  "games/clfnfbside.html": "Friday Night Funkin'",
  "games/clfnfcamelliarudeblaster.html": "Game 6453",
  "games/clfnfchara.html": "Game 24810",
  "games/clfnfcory.html": "Game 6629",
  "games/clfnfcrunchin.html": "Game 24838",
  "games/clfnfdropandroll.html": "Game 26642",
  "games/clfnfdustin.html": "Game 24823",
  "games/clfnffleetway.html": "Game 24882",
  "games/clfnffnaf3.html": "Game 26955",
  "games/clfnfgamebreakerbundle.html": "Game 24800",
  "games/clfnfhank.html": "Game 24929",
  "games/clfnfhex.html": "Friday Night Funkin'",
  "games/clfnfholiday.html": "Game 24915",
  "games/clfnfhorkglorpgloop.html": "Game 27553",
  "games/clfnfhypnoslullaby.html": "Game 24807",
  "games/clfnfimposter3.html": "FNF VS Impostor v3",
  "games/clfnfimposterv4.html": "Game 22808",
  "games/clfnfmarioport.html": "Game 23346",
  "games/clfnfmidfight.html": "Friday Night Funkin’ Sarvente's Mid-Fight Masses",
  "games/clfnfmiku.html": "Friday Night Funkin'",
  "games/clfnfneo.html": "Friday Night Funkin'",
  "games/clfnfpiggyfield.html": "Game 23221",
  "games/clfnfplutoshi.html": "Game 25373",
  "games/clfnfpokepastaperdition.html": "Game 26971",
  "games/clfnfqt.html": "Vs. QT Mod",
  "games/clfnfrewrite.html": "Game 23069",
  "games/clfnfselfpaced.html": "Game 26544",
  "games/clfnfshaggy4keys.html": "Game 6711",
  "games/clfnfshucks-v2.html": "Game 27472",
  "games/clfnfsky.html": "Desmos",
  "games/clfnfsoft.html": "FNF SOFT Online (Friday Night Funkin')",
  "games/clfnftricky.html": "Friday Night Funkin' (FNF) vs Tricky: Version 2, Phase 3 (w/ CHEAT BOT)",
  "games/clfnfTWIDDLEFINGER.html": "Twiddlefinger",
  "games/clfnfundertale.html": "Game 23443",
  "games/clfnfvoid.html": "Game 24875",
  "games/clfnfwednesday-infedility.html": "Game 24859",
  "games/clfnfwhitty.html": "Friday Night Funkin'",
  "games/clfnfzardy.html": "Friday Night Funkin'",
  "games/clfocus.html": "Focus",
  "games/clfolderdungeon.html": "Folder Dungeon",
  "games/clfootballbros.html": "Football Bros",
  "games/clfootballlegends.html": "Football Legends",
  "games/clforknsausage.html": "ForkNSausage",
  "games/clfortzone.html": "Fortzone Battle Royale",
  "games/clfpa4p1.html": "Fancy Pants Adventure 4 Part 1",
  "games/clfpa4p2.html": "Fancy Pants Adventure 4 Part 2",
  "games/clfreegemas.html": "Freegemas",
  "games/clfreerider.html": "Free Rider",
  "games/clfreerider2.html": "Free Rider 2",
  "games/clfreerider3.html": "Free Rider 3",
  "games/clfridaynightfunkin.html": "Friday Night Funkin'",
  "games/clfromrusttoash.html": "PICO-8 Cartridge",
  "games/clfruitninja.html": "Fruit Ninja",
  "games/clfunnybattle.html": "Funny Battle Simulator",
  "games/clfunnybattle2.html": "Funny Battle Simulator 2",
  "games/clfunnymadracing.html": "Funny Mad Racing",
  "games/clfunnyshooter22.html": "Funny Shooter 2",
  "games/clfzero.html": "F Zero",
  "games/clfzerox.html": "F Zero X",
  "games/clgachaverse.html": "Gachaverse",
  "games/clgalaga.html": "Galaga",
  "games/clgameandwatchcollection.html": "Game and Watch Collection",
  "games/clgangstabean.html": "Gangsta Bean",
  "games/clgangstabean2.html": "Gangsta Bean 2",
  "games/clgangsterbros.html": "Gangster Bros",
  "games/clgarcello.html": "Friday Night Funkin': Psych Engine",
  "games/clgdlite.html": "Geometry Dash",
  "games/clgdsubzero.html": "Geometry Dash Subzero",
  "games/clgeneralchaos.html": "General Chaos",
  "games/clgenericfightermaybe.html": "Created with GameMaker Studio 2",
  "games/clgeometrydashscratch.html": "Geometry Dash",
  "games/clgeometryvibes.html": "Geometry Vibes",
  "games/clgeorgeandtheprinter.html": "George and the Printer",
  "games/clgetawayshootout.html": "Getaway Shootout",
  "games/clgetontop.html": "Get_On_Top_Touch",
  "games/clGettothetopalthoughthereisnotop.html": "Get to the Top Although There Is No Top",
  "games/clgetyoked.html": "Get Yoked",
  "games/clggshinobi.html": "G. G. Shinobi",
  "games/clghosttrick.html": "Ghost Trick - Phantom Detective",
  "games/clgimmietheairpod.html": "Gimme the Airpod",
  "games/clgladdihoppers.html": "Gladihoppers",
  "games/clglfighters.html": "GLFighters",
  "games/clgloryhunters.html": "Glory Hunters",
  "games/clglover.html": "Glover",
  "games/clgoalsouthafrica.html": "Goal South Africa",
  "games/clgobble.html": "Gobble",
  "games/clgoingballs.html": "Going Balls - UBG365",
  "games/clgolddiggerfrvr.html": "Gold Digger FRVR - Deep Mining - Dig and Match Exploration",
  "games/clgoldeneye007.html": "Goldeneye 007",
  "games/clgoldensun.html": "Golden Sun",
  "games/clgoldensunnds.html": "Golden Sun - The Lost Age",
  "games/clGoldenSunTheLostAge.html": "Golden Sun the Lost Age",
  "games/clgoldminer.html": "Gold Miner",
  "games/clgolfsunday.html": "PICO-8 Cartridge",
  "games/clgoodboygalaxy.html": "Good Boy Galaxy",
  "games/clgooglebaseball.html": "Google Baseball",
  "games/clgoogledino.html": "Dinosaur Game Chrome",
  "games/clgorescriptclassic.html": "gorescript",
  "games/clgranddad.html": "7 Grand Dad",
  "games/clgrandtheftautoadvance.html": "Grand Theft Auto Advance",
  "games/clgranny2.html": "google.com",
  "games/clgranny22.html": "Granny 2",
  "games/clgranny3.html": "Granny 3 Return the School",
  "games/clgrannyy.html": "Granny Original",
  "games/clgranturismo.html": "Gran Turismo",
  "games/clgranturismo2.html": "Gran Turismo 2 (USA) (Arcade Mode)",
  "games/clgrassmowing.html": "Stone Grass Mowing Simulator",
  "games/clgravity.html": "Firecaster: Gravity",
  "games/clgravitymod.html": "Gravity Mod",
  "games/clgrey-box-testing.html": "Grey Box Testing",
  "games/clgrimacebirthday.html": "Grimace’s Birthday",
  "games/clgrindcraft.html": "GrindCraft",
  "games/clgrn.html": "GRN Prototype",
  "games/clgrowagarden.html": "Grow a Garden",
  "games/clgrowdenio.html": "Grow a Garden in Growden.io | Free Garden Game",
  "games/clgrowyourgarden.html": "Grow Your Garden",
  "games/clgta.html": "Grand Theft Auto",
  "games/clgta2.html": "Grand Theft Auto 2",
  "games/clgta22.html": "Grand Theft Auto 2",
  "games/clgtachina.html": "Grand Theft Auto - Chinatown Wars",
  "games/clguesstheiranswer.html": "Guess Their Answer",
  "games/clgun-spin.html": "google.com",
  "games/clgunblood.html": "Gun Blood",
  "games/clguncho.html": "PICO-8 Cartridge",
  "games/clgunmayhem.html": "Gun Mayhem",
  "games/clgunmayhem2goof.html": "Gun Mayhem 2",
  "games/clgunmayhemredux.html": "Deep Sleep",
  "games/clgunnight.html": "GUN NIGHT",
  "games/clgunsmoke.html": "Gun.smoke",
  "games/clgymstack.html": "Gym Stack GS2",
  "games/clhacx.html": "Hacx",
  "games/clhajimeippo.html": "Hajime No Ippo the Fight in G",
  "games/clhalflife.html": "Xash",
  "games/clhalocombatdevolved.html": "Halo Combat Devolved",
  "games/clhandshakes.html": "Handshakes",
  "games/clhandsofwar.html": "Hands of War",
  "games/clhandulum.html": "Handulum+",
  "games/clhanger2.html": "Hanger 2",
  "games/clhappyroom.html": "Happy Room",
  "games/clhappywheels.html": "Happy Wheels",
  "games/clhardwaretycoon.html": "Hardware Tycoon",
  "games/clHaroldsbadday.html": "PICO-8 Cartridge",
  "games/clharvestio.html": "Harvest.io",
  "games/clharvestmoon.html": "Harvest Moon",
  "games/clharvestmoon64.html": "Harvest Moon 64",
  "games/clhauntthehouse.html": "Haunt the House",
  "games/clheartandsoul.html": "Pokemon - Heart and Soul",
  "games/clhei$t.html": "HEI$T",
  "games/clhelixjump.html": "Helix Jump",
  "games/clhellron.html": "HellroN",
  "games/clhelpnobrakes.html": "HELP NO BRAKE",
  "games/clheretic.html": "Heretic",
  "games/clhextris.html": "Hextris",
  "games/clhighstakes.html": "PICO-8 Cartridge",
  "games/clhighwayracer2.html": "Highway Racer 2",
  "games/clhillclimbracinglite.html": "HCR Lite 1.0",
  "games/clHiNoHomo.html": "Hi No Homo",
  "games/clhipsterkickball.html": "Hipster Kickball",
  "games/clhit8ox.html": "PICO-8 Cartridge",
  "games/clhitsinglereal.html": "Hit Single Real",
  "games/clhitstunfly.html": "HitStunFly",
  "games/clhl2doom.html": "Doom But It’s Half Life 2",
  "games/clhobo.html": "Hobo",
  "games/clhobo2.html": "Hobo 2",
  "games/clhobo3.html": "Hobo 3",
  "games/clhobo4.html": "Hobo 4",
  "games/clhobo5.html": "Hobo 5",
  "games/clhobo6.html": "Hobo 6",
  "games/clhobo7.html": "Hobo 7",
  "games/clhobovszombies.html": "Hobo Vs. Zombies",
  "games/clholeio.html": "Hole.io",
  "games/clhollowknight.html": "Hollow Knight Demake",
  "games/clhomesheephome.html": "Home Sheep Home",
  "games/clhotwax.html": "PICO-8 Cartridge",
  "games/clhouseofhazards.html": "House of Hazards",
  "games/clhoverracerdrive.html": "Hover Racer Drive",
  "games/clhumanexpenditureprogram.html": "HUMAN EXPENDITURE PROGRAM",
  "games/clhungryknight.html": "Hungry Knight",
  "games/clhungrylamu.html": "game",
  "games/clhyppersandbox.html": "Hypper Sandbox",
  "games/clicantbelievegoogleflaggedmeforthenameofthefilelol.html": "Riddle School 5",
  "games/clicedodo.html": "Ice Dodo - Play Online at Onionfist.com",
  "games/clicypurplehead.html": "Icy Purple Head",
  "games/clidlebreakout.html": "Made by Kodiqi",
  "games/clidledice.html": "Idle Dice",
  "games/clidleidlegamedev.html": "Idle IdleGameDev",
  "games/clidleminertycoon.html": "Idle Miner Tycoon",
  "games/climpossiblequiz.html": "The Impossible Quiz",
  "games/climpossiblequiz2.html": "Deep Sleep",
  "games/clinclementemerald.html": "Pokemon inclement emerald",
  "games/clinfinitecraft.html": "Nova Craft",
  "games/clinkgame.html": "Ink Game",
  "games/clinnkeeper.html": "Factory Balls 3",
  "games/clinsidestory.html": "Mario & Luigi - Bowser's Inside Story",
  "games/clinteractivebuddy.html": "Interactive Buddy",
  "games/clintoruins.html": "PICO-8 Cartridge",
  "games/clintospace.html": "Into Space",
  "games/clintospace2.html": "Into Space 2",
  "games/clintospace3.html": "Into Space 3",
  "games/clintothedeepweb.html": "Into the Deep Web",
  "games/clintrusion.html": "Intrusion",
  "games/cliqball.html": "IQ Ball",
  "games/clironsnout.html": "Iron Snout",
  "games/clironsoldier.html": "Iron Soldier",
  "games/clitgetssolonelyhere.html": "it-gets-so-lonely-here",
  "games/cliwbtg.html": "I WANNA BE THE GUY: THE GAME: THE MOVIE",
  "games/cljacksmithencryptedorsmthn.html": "Jacksmith",
  "games/cljailbreakobbbobob.html": "Jailbreak Obby",
  "games/cljefflings.html": "Jefflings",
  "games/cljellydadhero.html": "Jellydad Hero",
  "games/cljellydrift.html": "Jelly Drift",
  "games/cljellytruckgood.html": "Jelly Truck",
  "games/cljetforcegemini.html": "Jet Force Gemini",
  "games/cljetpackjoyride.html": "Jetpack Joyride",
  "games/cljetrush.html": "Jet Rush",
  "games/cljetskiracing.html": "Jetski Race",
  "games/cljohnnytrigger.html": "Johnny Trigger",
  "games/cljohnnyupgrade.html": "Johnny Upgrade",
  "games/cljourneydownhill.html": "journey downhill",
  "games/cljsvecx.html": "JSVecX: JavaScript port of VecX by raz0red.",
  "games/clJUMP.html": "JUMP",
  "games/cljumpingshell.html": "Jumping Shell",
  "games/cljustfalllol.html": "Justfall.lol",
  "games/cljusthitthebutton.html": "Just Hit the Button",
  "games/cljustoneboss.html": "PICO-8 Cartridge",
  "games/clkaizomarioworld.html": "Kaizo Mario World",
  "games/clkalikan.html": "PICO-8 Cartridge",
  "games/clkapi.html": "Game 24899",
  "games/clkaratebros.html": "Karate Bros | Hi-yah!",
  "games/clkarlson.html": "Karlson",
  "games/clkartbros.html": "KART BROS! - Free Online .io Kart Racing Game",
  "games/clKenGriffeyJrPresentsMajorLeagueBaseball.html": "Ken Griffey Jr. Presents Major League Baseball",
  "games/clkillerinstinct.html": "Killer Instinct",
  "games/clkillover.html": "KILLOVER",
  "games/clkilltheiceagebabyadventure.html": "Kill the Ice Age Baby Adventure",
  "games/clkingdomheartsdays.html": "Kingdom Hearts - 358-2 Days",
  "games/clkingdomheartsrecoded.html": "Kingdom Hearts Re Coded",
  "games/clkirby64.html": "Kirby 64",
  "games/clkirbyandtheamzingmirror.html": "Kirby and the Amazing Mirror",
  "games/clkirbysadventure.html": "Kirby’s Adventure",
  "games/clkirbysdreamland.html": "Kirby’s Dream Land",
  "games/clkirbysdreamland3.html": "Kirby’s Dream Land 3",
  "games/clkirbysqueaksquad.html": "Kirby Squeak Squad",
  "games/clkirbysuperstar.html": "Kirby Super Star",
  "games/clkirbysuperstarultra.html": "Kirby Super Star Ultra",
  "games/clkittencannon.html": "Kitten Cannon",
  "games/clklifur.html": "Klifur",
  "games/clknightmaretower.html": "Knightmare Tower",
  "games/clkonkrio.html": "Konkr.io",
  "games/clkoopasrevenge.html": "A Koopa’s Revenge",
  "games/clkourio.html": "Kour.io",
  "games/cllaceysflashgames.html": "Lacey's Flash Games",
  "games/cllastfirered.html": "Pokemon the Last Fire Red",
  "games/cllasthorizon.html": "Last Horizon",
  "games/clleaderstrike.html": "Leader Strike",
  "games/clleapandavoid2.html": "Leap and Avoid 2",
  "games/cllearntofly.html": "Learn to Fly",
  "games/cllearntofly2.html": "Learn to Fly 2",
  "games/cllearntofly3.html": "Learn to Fly 3",
  "games/cllearntoflyidle.html": "Learn to Fly Idle",
  "games/cllegobatman.html": "LEGO Batman - The Videogame",
  "games/cllegobatman2superheroes.html": "LEGO Batman 2 - DC Super Heroes",
  "games/cllegoindianajones.html": "LEGO Indiana Jones - The Original Adventures",
  "games/cllegoindianajones2.html": "LEGO Indiana Jones 2 - The Adventure Continues",
  "games/cllegoninjago.html": "LEGO Ninjago - The Videogame",
  "games/cllegostarwars.html": "LEGO Star Wars - The Complete Saga",
  "games/cllemmings.html": "Lemmings",
  "games/clleveldevil.html": "Level Devil",
  "games/clleverwarriors.html": "Lever Warriors",
  "games/cllinerider.html": "Line Rider",
  "games/cllinktothepast.html": "The Legend of Zelda a Link to the Past",
  "games/cllittlealchemy2.html": "Little Alchemy 2",
  "games/cllittlerunmo.html": "Little Runmo - The Game 1.3",
  "games/cllockthedoor.html": "Lock the Door",
  "games/clloderunner.html": "Lode Runner",
  "games/cllonewolf.html": "Lonewolf",
  "games/cllosangelesshark.html": "Los Angeles Shark",
  "games/cllowknight.html": "PICO-8 Cartridge",
  "games/clloz1.html": "The Legend of Zelda",
  "games/cllozlinkawakening.html": "Legend of Zelda, the Link's Awakening",
  "games/cllozminishcap.html": "The Legend of Zelda Minish Cap",
  "games/cllozoracleofseasons.html": "Legend of Zelda, the Oracle of Se as on S",
  "games/cllozspirittracks.html": "Legend of Zelda, The - Spirit Tracks (USA, Australia) (En,Fr,Es)",
  "games/clluckyblocks.html": "Robby Blocks",
  "games/clmadalinstuntcarsmultiplayerfixed.html": "Madalin Stunt Cars Multiplayer",
  "games/clmadden93.html": "John Madden Football ‘93",
  "games/clmadden94.html": "Madden NFL ‘94",
  "games/clmadden95.html": "Madden NFL ‘95",
  "games/clmadden96.html": "Madden NFL ‘96",
  "games/clmadden99.html": "Madden NFL ‘99",
  "games/clmaddenfootball.html": "Madden Football",
  "games/clmaddenfootball64.html": "Madden Football 64",
  "games/clmaddennfl.html": "Madden NFL",
  "games/clmaddennfl2000.html": "Madden NFL 2000",
  "games/clmaddennfl2001.html": "Madden NFL 2001",
  "games/clmaddennfl2002.html": "Madden NFL 2002",
  "games/clmaddy98.html": "Madden NFL ‘98",
  "games/clmadness-retaliation.html": "Madness Retaliation",
  "games/clmadnessaccelerant.html": "Madness Accelerant",
  "games/clmadnesscombatdefense.html": "Madness Combat Defense",
  "games/clmadnesscombatnexus.html": "Madness Project Nexus",
  "games/clmadnessgemini.html": "Madness Gemini",
  "games/clmadnesshydraulic.html": "Madness Hydraulic",
  "games/clmadnessinteractive.html": "Madness Interactive",
  "games/clmadnessoffcolor.html": "PICO DAY",
  "games/clmadnesspremediation.html": "Madness Premediation",
  "games/clmadnesss2010.html": "Madness 2010",
  "games/clmadnessstand.html": "Madness the Stand",
  "games/clmadskillsmotocross2.html": "MSM2 0.111.00",
  "games/clmadstick.html": "Mad Stick",
  "games/clmadstuntcars2.html": "Madalin Stunt Cars 2 - Unblcoked Games 76",
  "games/clmajorasmask.html": "Legend of Zelda, The - Majora's Mask",
  "games/clmakesureitsclosed.html": "Make Sure Its Closed",
  "games/clmanagod.html": "Mana God",
  "games/clmario3.html": "Super Mario Bros. 3",
  "games/clmario64webgl.html": "Super Mario 64 PC Web! 🎩",
  "games/clmarioandluigisuperstarsaga.html": "Mario & Luigi Superstar Saga",
  "games/clmariocombat.html": "Mario Combat",
  "games/clmariogolf.html": "Mario Golf",
  "games/clMarioisMissingDoneRight.html": "Mario Is Missing Done Right",
  "games/clmariokart64.html": "Mario Kart 64",
  "games/clmariokartsupercircuit.html": "Mario Kart Super Circuit",
  "games/clmariolostlevels.html": "Super Mario Bros. 2 the Lost Levels",
  "games/clmariopaint.html": "Mario Paint",
  "games/clmarioparty.html": "Mario Party",
  "games/clmarioparty2.html": "Mario Party 2",
  "games/clmarioparty3.html": "Mario Party 3",
  "games/clmariopartyds.html": "Mario Party DS",
  "games/clmariosmysterymeat.html": "Mario’s Mystery Meat",
  "games/clmariotennis.html": "Mario Tennis",
  "games/clmaskedforcesunlimited.html": "Masked Forces Unlimited",
  "games/clmastermindworldconquerer.html": "Mastermind World Conquer or",
  "games/clmatrixrampage.html": "Matrix Rampage",
  "games/clmattv2.html": "Game 24838",
  "games/clmaxpayne.html": "Max Payne",
  "games/clmcfpsfbhd.html": "Fuelled By Hotdogs",
  "games/clmcraerally.html": "Colin McRae Rally",
  "games/clmeatboy.html": "Me at Boy",
  "games/clmeatboyflash.html": "Me at Boy",
  "games/clmedalofhonor.html": "Medal of Honor",
  "games/clmedievalshark.html": "Medieval Shark",
  "games/clmedievil.html": "Resident Evil",
  "games/clmegachess.html": "Megachess",
  "games/clmegaman.html": "Mega Man",
  "games/clmegaman2.html": "Mega Man 2",
  "games/clmegaman2gba.html": "Mega Man 2",
  "games/clmegaman3.html": "Mega Man 3",
  "games/clmegaman4.html": "Mega Man 4",
  "games/clmegaman5.html": "Mega Man 5",
  "games/clmegaman6.html": "Mega Man 6",
  "games/clmegaman7.html": "Mega Man 7",
  "games/clmegaman8.html": "Mega Man 8",
  "games/clmegamanlegends.html": "Mega Man Legends",
  "games/clmegamanlegends2.html": "Gran Turismo",
  "games/clmegamanx.html": "Mega Man X",
  "games/clmegamanx2.html": "Mega Man X 2",
  "games/clmegamanx3.html": "Mega Man X 3",
  "games/clmegamanx4.html": "Mega Man X4",
  "games/clmegamanzero.html": "Mega Man Zero",
  "games/clmegamanzx.html": "Mega Man ZX",
  "games/clmegaminer.html": "Mega Miner",
  "games/clmelonplayground.html": "Melon Playground",
  "games/clmeowuwu.html": "Tony Hawk's Pro Skater",
  "games/clmergeroundracers.html": "Merge Round Racers",
  "games/clmetalgear.html": "Metal Gear",
  "games/clmetalgearsolid.html": "Metal Gear Solid",
  "games/clmetalgearsolidps.html": "Metal Gear Solid",
  "games/clmetalslug.html": "Metal Slug",
  "games/clmetalslug2.html": "Metal Slug 2",
  "games/clmetalslugadvance.html": "Metal Slug Advance",
  "games/clmetalslugmission1.html": "Metal Slug 1 St Mission",
  "games/clmetalslugmission2.html": "Metal Slug 2 Nd Mission",
  "games/clMetalSonicHyperdrive.html": "Metal Sonic Hyperdrive",
  "games/clmetroid.html": "Metroid",
  "games/clmetroid2.html": "Metroid 2",
  "games/clmetroidfusion.html": "Metroid Fusion",
  "games/clmetroidzeromission.html": "Metroid Zero Mission",
  "games/clmiamishark.html": "Miami Shark",
  "games/clmightyknight.html": "Mighty Knight",
  "games/clmightyknight2.html": "Mighty Knight 2",
  "games/clmimic.html": "PICO-8 Cartridge",
  "games/clmindscape.html": "Mindscape",
  "games/clminecraft1-8-8.html": "EaglercraftX",
  "games/clmineshooter.html": "Mine Shooter",
  "games/clminesweeperplus.html": "MinesweeperPlus",
  "games/clminhero.html": "Min Hero",
  "games/clminicrossword.html": "Mini Crossword",
  "games/clminishooters.html": "Mini Shooters",
  "games/clminitooth.html": "Mini tooth",
  "games/clmiraginewar.html": "Miragine War",
  "games/clmisslecommand.html": "Missile Command",
  "games/clmk4ampedup.html": "Mario Kart 64 - Amped Up",
  "games/clmmwilywars.html": "Mega Man the Wily Wars",
  "games/clmobiusrevolution.html": "Mobius Evolution",
  "games/clmoneyrush.html": "Money Rush",
  "games/clmonkeymart.html": "Monkey Mart",
  "games/clmonstertracks.html": "Monster Tracks",
  "games/clmonstertruckportstunt.html": "google.com",
  "games/clmortalkombat.html": "Mortal Kombat",
  "games/clmortalkombat2.html": "Mortal Kombat 2",
  "games/clmortalkombat2a.html": "Mortal Kombat 2",
  "games/clmortalkombat3.html": "Mortal Kombat 3",
  "games/clmortalkombat3a.html": "Mortal Kombat 3",
  "games/clmortalkombat4.html": "Mortal Kombat 4",
  "games/clmortalkombata.html": "Mortal Kombat",
  "games/clmortalkombatadvance.html": "Mortal Kombat Advance",
  "games/clmortkom4.html": "Mortal Kombat 4",
  "games/clmotherload.html": "Motherload",
  "games/clmotoroadrash.html": "Moto Road Rash 3D",
  "games/clmotox3m2.html": "Moto X3M 2 Unblocked",
  "games/clmotox3m3.html": "Moto X3M 3",
  "games/clmotox3mm.html": "${pageTitle}",
  "games/clmotox3mpoolparty.html": "Moto X3M 5 Pool Party",
  "games/clmotox3mspookyland.html": "MotoX3M 6 Spooky Land",
  "games/clmotox3mwinter.html": "Moto X3M Winter Unblocked",
  "games/clmountainbikeracer.html": "Mountain Bike Racer",
  "games/clmrracer.html": "MR RACER",
  "games/clmspacman.html": "Ms. Pac Man",
  "games/clmultitask.html": "Multitask",
  "games/clmutilate-a-doll.html": "Mu Til at E a Doll",
  "games/clmxoffroadmaster.html": "MX Offroad Master",
  "games/clmyfriendpedro.html": "My Friend Pedro",
  "games/clmyfriendpedroarena.html": "My Friend Pedro Arena",
  "games/clmyteardrop.html": "myTeardrop",
  "games/cln.html": "N",
  "games/clnarc.html": "Narc",
  "games/clnaturalselection.html": "Natural Selection",
  "games/clNBAhangtime.html": "NBA Hangtime",
  "games/clNBAjam.html": "NBA Jam",
  "games/clnbajamTE.html": "NBA Jam Tournament Edition",
  "games/clnbalive2000.html": "NBA Live 2000",
  "games/clnblox.html": "Nblox",
  "games/clneonblaster.html": "Neon Blaster",
  "games/clneonrider.html": "Neon Rider",
  "games/clnesworldchampion.html": "Nintendo World Championships 1990",
  "games/clnetattack.html": "Net.Attack()",
  "games/clneverendinglegacy.html": "NeverEnding Legacy",
  "games/clnewgroundsrumble.html": "Newgrounds Rumble",
  "games/clnewsupermariobros.html": "New Super Mario Bros",
  "games/clNewSuperMarioWorld2AroundtheWorld.html": "New Super Mario World 2 Around the World",
  "games/clnewyorkshark.html": "New York Shark",
  "games/clnextdoor.html": "NextDoor",
  "games/clnflblitz.html": "NFL Blitz",
  "games/clnfscarbonowncity.html": "Need for Speed Car B on Own the City",
  "games/clnfsmostwanted.html": "Need for Speed Most Wanted",
  "games/clnfsporcheunleashed.html": "Need for Speed Porsche Unleashed",
  "games/clnfsunderground.html": "Need for Speed Underground",
  "games/clnfsunderground2.html": "Need for Speed Underground 2",
  "games/clngon.html": "n-gon",
  "games/clnhl2002.html": "NHL 2002",
  "games/clnhl98.html": "NHL 98",
  "games/clnhlhitz2003.html": "NHL Hitz 2003",
  "games/clnickelodeonsuperbrawl2.html": "Nickelodeon Super Brawl 2",
  "games/clNicktoonsFreezeFrameFrenzy.html": "Nicktoons Freeze Frame Frenzy",
  "games/clnightclubshowdown.html": "nightclubShowdown",
  "games/clnightfire.html": "007 Nightfire",
  "games/clnightshade.html": "Nightshade",
  "games/clnimrods.html": "Nimrods",
  "games/clninjabrawl.html": "Ninja Brawl",
  "games/clnintendogslab.html": "Nintendogs Lab & Friends",
  "games/clnintendoworldcup.html": "Nintendo World Cup",
  "games/clnitromemustdie.html": "Game title",
  "games/clnoobminer.html": "Noob Miner",
  "games/clnotyourpawn.html": "Not Your Pawn",
  "games/clnplus.html": "N+",
  "games/clnubbysnumberfactory.html": "GXC Game",
  "games/clnullkevin.html": "10-103NK",
  "games/clNutsandBoltsScrewingPuzzle.html": "Nuts and Bolts Screwing Puzzle",
  "games/clnzp.html": "NZ: Portable",
  "games/clobby-99-will-lose.html": "Obby 99% Will Lose",
  "games/clobbyonlyup.html": "Obby Robby: Only Up",
  "games/clobeythegame.html": "Obey the Game",
  "games/clocarinaoftime.html": "Legend of Zelda, The - Ocarina of Time",
  "games/clofflineparadise.html": "Offline Paradise",
  "games/clomeganuggetclicker.html": "Omega Nugget Clicker",
  "games/clonebitadventure.html": "Onebit Adventure",
  "games/clonenightasfreddy.html": "One Night As Fredbear",
  "games/clonepiece.html": "One Piece",
  "games/clonepiecefighting.html": "One Piece Fight in G",
  "games/cloneshotold.html": "Oneshot Legacy",
  "games/clonlyup.html": "Only Up",
  "games/clÖoo.html": "Öoo",
  "games/cloperius.html": "Operius",
  "games/cloppositeday.html": "Opposite Day",
  "games/clorbofcreation.html": "Orb of Creation",
  "games/clordinarysonicromhack.html": "An Ordinary Sonic Rom Hack (sonic.exe)",
  "games/cloregontrail.html": "The or Eg on Trail",
  "games/closu.html": "WebOsu 2.0!",
  "games/clourpleguy.html": "Game 26968",
  "games/clovo2.html": "OvO 2",
  "games/clovodimensions.html": "OvO Dimensions",
  "games/clovofixed.html": "OvO",
  "games/clpacman.html": "Pac Man",
  "games/clpacmana.html": "Pac Man",
  "games/clpacmanworld3.html": "pac man 3",
  "games/clpacmanworldg.html": "Pac Man World",
  "games/clpacmanworldpsx.html": "Pac-Man World - 20th Anniversary",
  "games/clpapabakeria.html": "Papa’s Bakeria",
  "games/clpapadonut.html": "Papa’s Donuteria",
  "games/clpapalouienighthunt2.html": "Papa Louie Night Hunt 2",
  "games/clpapalouiewhenburgersattack.html": "Papa Louie When Burgers Attack",
  "games/clpapalouiewhenpizzasattack.html": "Papa Louie When Pizzas Attack",
  "games/clpapalouiewhensundaesattack.html": "Papa Louie When Sundaes Attack",
  "games/clpapasburgerIIIAAAAA.html": "Papa’s Burgeria",
  "games/clpapascheeseria.html": "Papa’s Cheeseria",
  "games/clpapascupcakeria.html": "Papa’s Cupcakeria",
  "games/clpapasfreezeria.html": "Papa’s Freezeria",
  "games/clpapashotdoggeria.html": "Papa’s Hot Doggeria",
  "games/clpapaspancakeria.html": "Papa’s Pancakeria",
  "games/clpapaspastaria.html": "Papa’s Pastaria",
  "games/clpapasscooperia.html": "Papa’s Scooperia",
  "games/clpapassushiria.html": "Papa’s Sushiria",
  "games/clpapastacomia.html": "Papa’s Taco Mia",
  "games/clpapaswingeria.html": "Papa’s Wingeria",
  "games/clpaperio.html": "Paper.io",
  "games/clpaperio3d.html": "Paper.io 3D",
  "games/clpaperiomania.html": "Paper.io Mania",
  "games/clpapermario.html": "Paper Mario",
  "games/clpapermariopromode.html": "Paper Mario Pro Mode v0.1.6",
  "games/clpapermariottyd.html": "TTYD64-v1.0.0",
  "games/clparappatherapper.html": "Parappa the Rapper",
  "games/clparkingfury.html": "Parking Fury",
  "games/clparkingfury2.html": "Parking Fury 2",
  "games/clparkingfury3.html": "Parking Fury 3",
  "games/clparkingrush.html": "Parking Rush",
  "games/clpartnersintime.html": "Mario & Luigi - Partners in Time",
  "games/clpeacekeeper.html": "Peacekeeper",
  "games/clpeggle.html": "Peggle",
  "games/clpenaltykicks.html": "Penalty Kicks",
  "games/clpenguindiner.html": "Penguin Diner 1",
  "games/clpenguinpass.html": "Penguin Pass",
  "games/clpepsiman.html": "Pepsiman",
  "games/clpereelous.html": "Pereelous",
  "games/clperfectdark.html": "Perfect Dark",
  "games/clperfecthotel.html": "Perfect Hotel",
  "games/clpersona.html": "Persona",
  "games/clpersona2.html": "Persona 2",
  "games/clphasma.html": "Phasma",
  "games/clpheonixjusticeforall.html": "Phoenix Wright Ace Attorney Justice for All",
  "games/clpheonixtrialsandyear.html": "Phoenix Wright Ace Attorney Trials and Tribulations",
  "games/clpicodriller.html": "PICO-8 Cartridge",
  "games/clpicohot.html": "PICO-8 Cartridge",
  "games/clpicolife.html": "PICO-8 Cartridge",
  "games/clpiconightpunkin.html": "PICO-8 Cartridge",
  "games/clpicosschool.html": "Pico’s School",
  "games/clpicovsbeardx.html": "Pico vs Bear DX",
  "games/clpiecesofcake.html": "PICO-8 Cartridge",
  "games/clpingpongchaos.html": "Ping Pong Chaos",
  "games/clpinkbike.html": "Pinkbike's Grim Donut Game",
  "games/clpitfall.html": "Pitfall!",
  "games/clpixelbattlegroundsio.html": "PUBG Mini",
  "games/clpixelcombat2.html": "Pixel Combat 2",
  "games/clpixelquestlostidols.html": "Pixel Quest the Lost Idols",
  "games/clpixelshooter.html": "Pixel Shooter 1",
  "games/clpixelwarfare.html": "Pixel Warfare",
  "games/clpizzapapa.html": "Papa’s Pizzeria",
  "games/clpizzatower.html": "Pizza Tower",
  "games/clplangman.html": "Plangman",
  "games/clplazmaburst.html": "Plazma Burst",
  "games/clplinko.html": "Free Plinko Game Online - Play & Win Instant Rewards",
  "games/clplonky.html": "Plonky",
  "games/clpogo3D.html": "pogo time",
  "games/clpokeallin.html": "Pokémon All in",
  "games/clpokebattlefact.html": "Pokemon Battle Factory",
  "games/clpokeblack.html": "Pokemon Black Version",
  "games/clpokeblazeblack2redux.html": "Pokemon Blaze Black 2 Redux Complete (v1.4.1)",
  "games/clpokeblue.html": "Pokemon Blue Version",
  "games/clpokeclassic.html": "Pokéclassic",
  "games/clpokecrown.html": "Pokemon Crown",
  "games/clpokecrystalclear.html": "Pokemon Crystal Clear",
  "games/clpokediamond.html": "Pokemon - Diamond Version (USA)",
  "games/clpokedreamstone.html": "Pokemon Dreamstone",
  "games/clpokeeliteredux.html": "Pokemon Elite Redux",
  "games/clpokeelysiuma.html": "Pokemon Elysium a",
  "games/clpokeelysiumb.html": "Pokemon Elysium B",
  "games/clpokeemeraldenhanced.html": "Pokemon Emerald Enhanced",
  "games/clpokeemeraldhorizons.html": "Pokémon Emerald Horizons",
  "games/clpokeemeraldrandom.html": "Pokemon Emerald Randomized",
  "games/clpokeemeraldz.html": "Pokemon Emerald Z",
  "games/clpokefiregold.html": "Pokémon Fire Gold",
  "games/clpokeflora.html": "Pokemon Flora Sky",
  "games/clpokefuseddimension.html": "Pokemon Fused Dimension",
  "games/clpokegaia.html": "Pokemon Gaia",
  "games/clpokegschronicles.html": "GS Chronicles",
  "games/clpokeheartgold.html": "Pokemon - HeartGold Version",
  "games/clpokelightplatinum.html": "Pokemon Light Pl at in Um",
  "games/clpokeliquidcrysta.html": "Pokemon Liquid Crystal",
  "games/clpokemegamoemon.html": "Pokemon Mega Moemon",
  "games/clpokemonamnesia.html": "Pokemon Amnesia",
  "games/clpokemonclover.html": "Pokemon Clover",
  "games/clpokemoncrystal.html": "Pokemon Crystal",
  "games/clpokemonemerald.html": "Pokemon Emerald",
  "games/clpokemonemeraldcrest.html": "Pokemon emerald crest",
  "games/clpokemonemeraldimperium.html": "Pokemon emerald crest",
  "games/clpokemonemeraldkaizo.html": "Pokemon Emerald Kaizo",
  "games/clpokemonemeraldmini.html": "Pokemon emerald mini",
  "games/clPokemonemeraldrouge.html": "Pokemon emerald rouge",
  "games/clpokemonemeraldseaglass.html": "Pokemon Emerald Seaglass",
  "games/clpokemonenergizedemerald.html": "Pokemon energized emerald",
  "games/clpokemonevolvedsfdgsdfs.html": "Pokemon Evolved",
  "games/clpokemonfirered.html": "Pokemon Firered",
  "games/clpokemonfireredrandomized.html": "Pokemon Firered Randomized",
  "games/clpokemongold.html": "Pokemon Gold",
  "games/clpokemonkaizoironfirered.html": "Pokemon Kaizo Iron Fire Red",
  "games/clpokemonlazarus.html": "Pokemon Lazarus",
  "games/clpokemonleafgreen.html": "Pokemon Leaf Green",
  "games/clpokemonmodernemerald.html": "Pokemon Modern Emerald",
  "games/clpokemonmysterydungeon.html": "Pokemon Mystery Dungeon",
  "games/clpokemonquetzal.html": "Pokemon Quetzal",
  "games/clpokemonroaringred.html": "Pokemon Roaring Red",
  "games/clPokemonrocketedition.html": "Pokemon Firered Rocket Edition",
  "games/clpokemonsapphire.html": "Pokemon Sapphire",
  "games/clpokemonshinsigma.html": "Pokemon Shiny Gold Sigma",
  "games/clpokemonsilver.html": "Pokemon Silver",
  "games/clpokemonsnap.html": "Pokemon Snap",
  "games/clpokemonstadium.html": "Pokemon Stadium",
  "games/clPokémonstunningsteel.html": "Pokemon Stunning Steel",
  "games/clpokemontowerdefense.html": "Pokemon Tower Defense",
  "games/clpokemonunbound.html": "Pokemon Unbound",
  "games/clpokemysteryexplorersofsky.html": "Pokemon Mystery Dungeon - Explorers of Sky",
  "games/clpokenameless.html": "Pokemon Nameless",
  "games/clpokeodyssey.html": "Pokemon Odyssey",
  "games/clpokepath.html": "PokéPath TD",
  "games/clpokepearl.html": "Pokemon - Pearl Version (USA)",
  "games/clpokeperfectfirered.html": "Pokémon Perfect Fire Red",
  "games/clpokepisces.html": "Pokemon Pisces",
  "games/clpokeplatinum.html": "Pokemon - Platinum Version",
  "games/clpokeplatinumrandomized.html": "Pokemon Platinum Randomized",
  "games/clpokerechargedpink.html": "Pokémon Recharged Pink",
  "games/clpokerechargedyellow.html": "Pokémon Exceeded Emerald",
  "games/clpokerecordkeepers.html": "Pokémon Record Keepers",
  "games/clpokered.html": "Pokemon Red Version",
  "games/clpokerowe.html": "Pokemon - ROWE",
  "games/clpokeruby.html": "Pokemon Ruby",
  "games/clpokerunandbun.html": "pokemon run and bun",
  "games/clpokescorchedsilver.html": "scorched silver",
  "games/clpokesoulsilver.html": "Pokemon - SoulSilver Version",
  "games/clpokethepit.html": "Pokémon Pit of 100 Trials (generation 9)",
  "games/clpoketourmaline.html": "Pokémon Tourmaline Version",
  "games/clpokeultraviolet.html": "Pokemon Ultra Violet",
  "games/clpokeunovaemerald.html": "Pokémon Unova Emerald",
  "games/clpokevega.html": "Pokemon Vega",
  "games/clpokevoltwhite2redux.html": "Pokemon Volt White 2 Redux Complete (v1.4.1)",
  "games/clpokevoyager.html": "Voyager",
  "games/clpokewhite.html": "Pokemon - White Version (USA, Europe)",
  "games/clpokewhite2.html": "Pokemon White Version 2",
  "games/clpokeyellow.html": "Pokemon Yellow Version",
  "games/clpolicepursuit2.html": "Police Pursuit 2",
  "games/clpolishedcrystal.html": "Pokémon Polished Crystal",
  "games/clpomgetsinternet.html": "EasyRPG Player",
  "games/clpoorbunny.html": "Poor Bunny",
  "games/clpopeyepapi.html": "Popeye",
  "games/clporklike.html": "PICO-8 Cartridge",
  "games/clportal.html": "Portal",
  "games/clportal2d.html": "Portal 2D",
  "games/clportaldefendersfastbreak.html": "Portal Defenders Fast Break",
  "games/clportaldefendersTD.html": "Portal Defenders Tower Defence",
  "games/clportalflash.html": "Portal Flash",
  "games/clporter.html": "PICO-8 Cartridge",
  "games/clpossessquest.html": "Possess Quest",
  "games/clpostal.html": "POSTAL: Play FREE on the web",
  "games/clpotatomanseeksthetroof.html": "Game title",
  "games/clpowerslave.html": "NHL 98",
  "games/clpraxisfighterx.html": "PICO-8 Cartridge",
  "games/clprecivilationbronzeage.html": "Pre Civilization Bronze Age",
  "games/clprehistoricshark.html": "Prehistoric Shark",
  "games/clprimary.html": "Primary",
  "games/clpullfrog.html": "PICO-8 Cartridge",
  "games/clpunchout.html": "Mike Tyson’s Punch Out",
  "games/clpunchthetrump.html": "Punch the Trump",
  "games/clpuppethockey.html": "Puppet Hockey Battle",
  "games/clpuppetmaster.html": "Puppet Master",
  "games/clpushyourluck.html": "- Play it now at CoolmathGames.com",
  "games/clpuyopuyofever.html": "Puyo Puyo Fever",
  "games/clpvz.html": "Plants Vs. Zombies",
  "games/clpyrotoad.html": "Pyrotoad",
  "games/clqbert.html": "Q Bert",
  "games/clquake2.html": "Quake II",
  "games/clquake3.html": "Quake III Arena",
  "games/clquake64.html": "Quake 64",
  "games/clquickieworld.html": "Quickie World",
  "games/clqwop.html": "QWOP",
  "games/clradicalred.html": "Pokemon radical red",
  "games/clradracer.html": "Rad Racer",
  "games/clraftwars.html": "Raft Wars",
  "games/clraftwars2.html": "Raft Wars 2",
  "games/clragdoll-io.html": "Ragdoll.io",
  "games/clragdollarchers.html": "Ragdoll Archers",
  "games/clragdollhit.html": "Ragdoll Hit - Poki",
  "games/clragdollrunners.html": "Ragdoll Runners",
  "games/clragdollsoccer.html": "Ragdoll Soccer",
  "games/clrainbowsix.html": "Tom Clancy's Rainbow Six",
  "games/clray1.html": "Ray Part 1",
  "games/clray2.html": "Ray Part 2",
  "games/clrayman.html": "Rayman",
  "games/clraze.html": "Raze",
  "games/clraze2.html": "Raze 2",
  "games/clraze3.html": "Raze 3",
  "games/clre3.html": "Resident Evil 3",
  "games/clreachthecore.html": "Reach the Core",
  "games/clrealflightsim.html": "Real Flight Simulator",
  "games/clrebuild.html": "Rebuild",
  "games/clrebuild2.html": "Rebuild 2",
  "games/clrecoil.html": "Recoil Unblocked",
  "games/clredalert.html": "red alert",
  "games/clredball.html": "Red Ball",
  "games/clredball2.html": "Red Ball 2",
  "games/clredball3.html": "Red Ball 3",
  "games/clRedBall4.html": "Red Ball 4",
  "games/clredball4vol2.html": "Red Ball 4 Vol.2",
  "games/clredball4vol3.html": "Red Ball 4 Vol.3",
  "games/clredhanded.html": "Red Handed",
  "games/clredtierunner.html": "Red Tie Runner",
  "games/clredvsblue2.html": "Red Vs. Blue",
  "games/clredvsbluewar.html": "Red Vs. Blue War",
  "games/clreignofcentipede.html": "Reign of Centipede",
  "games/clrenegades.html": "Renegades",
  "games/clresidentevil.html": "Resident Evil",
  "games/clresidentevil2.html": "Resident Evil 2",
  "games/clresizer.html": "Resizer",
  "games/clresortempire.html": "Resort Empire",
  "games/clretrobowl.html": "Retro Bowl",
  "games/clretrobowlcollege.html": "Retro Bowl College",
  "games/clretrohighway.html": "Retro Highway",
  "games/clretropingpong.html": "Retro-Ping-Pong",
  "games/clreturnman.html": "Return Man",
  "games/clreturnman2.html": "Return Man 2",
  "games/clreturntoriddleschool.html": "Return to Riddle School",
  "games/clrevolutionidle.html": "Revolution Idle X",
  "games/clrhythmheaven.html": "Rhythm Heaven",
  "games/clrhythymymheaven.html": "Rhythm Heaven",
  "games/clricochetkills2.html": "Ricochet Kills 2",
  "games/clriddlemiddleschool.html": "Riddle Middle School",
  "games/clriddleschool.html": "Riddle School",
  "games/clriddleschool2.html": "Riddle School 2",
  "games/clriddleschool3.html": "Riddle School 3",
  "games/clriddleschool445544444$$444$444.html": "Riddle School 4",
  "games/clriddletransfer.html": "Riddle Transfer",
  "games/clriddletransfer2.html": "Riddle Transfer 2",
  "games/clridgeracer.html": "Ridge Racer DS (USA, Europe)",
  "games/clristar.html": "Ristar",
  "games/clroadfighter.html": "Road Fighter",
  "games/clroadoffury.html": "Road of Fury",
  "games/clroadofthedead.html": "Road of the Dead",
  "games/clroadofthedead2.html": "Road of the Dead 2",
  "games/clrocketjump.html": "Rocket Jump",
  "games/clrocketknightadventures.html": "Rocket Knight Adventures",
  "games/clrocketleague.html": "Created with GameMaker: Studio",
  "games/clrocketpult.html": "ROCKETPULT",
  "games/clrocketsoccerderby.html": "Rocket Soccer",
  "games/clrodha.html": "game",
  "games/clrollerballer.html": "Roller Baller",
  "games/clrollingsky.html": "Rolling Sky",
  "games/clrollyvortex.html": "Rolly Vortex",
  "games/clrolypolymonster.html": "Roly Poly Monsters",
  "games/clrooftopsnipers.html": "Ro of to P Snipers",
  "games/clrooftopsnipers2.html": "Rooftop Snipers 2",
  "games/clroomclicker.html": "Room Clicker",
  "games/clrouletteknight.html": "Roulette Knight for Ludum Dare 41",
  "games/clruffle.html": "Ruffle Player",
  "games/clrun-2.html": "Run 2",
  "games/clrun.html": "Run",
  "games/clrun3.html": "Run 3",
  "games/clrunningfred.html": "Running Fred",
  "games/clrussiancardriver.html": "Russian Car Driver",
  "games/clsandboxels.html": "e-wall",
  "games/clsandsofthecoliseum.html": "Sands of the Coliseum",
  "games/clsandtris.html": "Setris",
  "games/clsantarun.html": "60 Seconds Santa Run",
  "games/clsaszombieassault2.html": "SAS Zombie Assault 2",
  "games/clsaulgoodmanrun.html": "Saul Good M an Run",
  "games/clscarletshift.html": "Created with GameMaker",
  "games/clscarymazegame.html": "Scary Maze Game",
  "games/clscaryteacher3d.html": "Scary Teacher 3D - Poki",
  "games/clscrapmetal3.html": "Scrap Metal 3",
  "games/clscrapyarddog.html": "Scrapyard Dog",
  "games/clscribblenauts.html": "Scribblenauts",
  "games/clscubabear.html": "Scuba Bear",
  "games/clseamongrel.html": "game",
  "games/clsecretofmana.html": "Secret of Mana",
  "games/clsega2gg.html": "Sonic the Hedgehog 2",
  "games/clself.html": "Created with GameMaker Studio 2",
  "games/clsentryfortress.html": "Sentry Fortress",
  "games/clserenitrove.html": "Serenitrove",
  "games/clserioussamadvance.html": "Serious Sam Advance",
  "games/clservingupmadness.html": "Serving Up Madness",
  "games/clsfk.html": "Strikeforce Kitty",
  "games/clsfk2.html": "Strikeforce Kitty 2",
  "games/clsfklaststand.html": "Strikeforce Kitty Last Stand",
  "games/clsfkleague.html": "Strikeforce Kitty League",
  "games/clshaggy.html": "FNF VS Shaggy",
  "games/clshc1.html": "Sift Heads Cartels Act 1",
  "games/clshc2.html": "Sift Heads Cartels Act 2",
  "games/clshc3.html": "Sift Heads Cartels Act 3",
  "games/clshift.html": "Shift",
  "games/clshift2.html": "Shift 2",
  "games/clshinmegamitenseidevilsurvivor.html": "Shin Megami Tensei - Devil Survivor",
  "games/clshortlife.html": "Short Life",
  "games/clshotout4.html": "Shot out 4",
  "games/clshredmill.html": "shredmill",
  "games/clshredsauce.html": "Shredsauce - Freestyle Skiing Game",
  "games/clshrek-2.html": "Shrek 2",
  "games/clshwultimatem.html": "Sift Heads World Ultimatum",
  "games/clsideeffects.html": "Side Effects",
  "games/clsidepocket.html": "Side Pocket",
  "games/clsierra7.html": "Sierra 7",
  "games/clsilenthill.html": "Silent Hill",
  "games/clsiloshowdow.html": "Silhouette Showdown",
  "games/clsixwaystodie.html": "Six Ways To Suffer",
  "games/clskateit.html": "Skate It",
  "games/clskibididibidygyattohiorizzingallovertheplacestillwatermangotheoryfemboydrool.html": "SkibidiToilet.io",
  "games/clskibidiinthebackrooms.html": "google.com",
  "games/clskibidishooter.html": "Skibidi Shooter",
  "games/clskong.html": "Hollow Knight Silksong Demake",
  "games/clskyrace-3d.html": "Sky Race 3 D",
  "games/clsliceitall.html": "Slice It All",
  "games/clslideinthewoods.html": "Slide in the Woods",
  "games/clslimelabratory.html": "Slime Lab or at or Y",
  "games/clslipways.html": "PICO-8 Cartridge",
  "games/clslitherio.html": "Snake",
  "games/clslope2player.html": "Slope 2 Player on your grandma",
  "games/clslope3.html": "Slope 3",
  "games/clslopeplus.html": "Slope",
  "games/clslotornot.html": "Slot or Not",
  "games/clslowroads.html": "s l o w r o a d s",
  "games/clsm63redux.html": "Super Mario 63 Redux",
  "games/clsm64hiddenstars.html": "Super Mario 64 the Hidden Stars",
  "games/clsmadvance2.html": "Super Mario Advance 2",
  "games/clsmadvance3.html": "Super Mario Advance 3",
  "games/clsmashkartsworking.html": "Smash Karts",
  "games/clsmashremix.html": "Smash_Remix_2.0.0",
  "games/clsmbcrossover.html": "Super Mario Crossover",
  "games/clsmgds.html": "Super Mario Galaxy DS",
  "games/clsnailbob.html": "Snail Bob",
  "games/clsnailbob2.html": "Snail Bob 2",
  "games/clsnailbob3.html": "Snail Bob 3",
  "games/clsnailbob4space.html": "Snail Bob 4",
  "games/clsnailbob5lovestory.html": "Snail Bob 5 Love Story",
  "games/clsnakelike.html": "PICO-8 Cartridge",
  "games/clsnipershot.html": "google.com",
  "games/clsniperv2.html": "google.com",
  "games/clsnowballio.html": "Snowball.io",
  "games/clsnowbros.html": "Snow Bros",
  "games/clsnowrider.html": "Snow Rider 3 D",
  "games/clsnowriderrrr.html": "Alt Snow Rider",
  "games/clsnowroad.html": "Snow Road",
  "games/clsoccerbros.html": "Soccer Bros | Official Site",
  "games/clsoccerrandomgood.html": "Soccer Random 1",
  "games/clsolarsandbox.html": "solar sandbox",
  "games/clsolarsmash.html": "YT Game Wrapper WebGL Template",
  "games/clsolatrobo.html": "solatrobo",
  "games/clsolitaire.html": "Solitaire",
  "games/clsonic1contemporary.html": "Sonic 1 Contemporary",
  "games/clSonic1ScoreRush.html": "Sonic 1 Score Rush",
  "games/clSonic2ScoreRush.html": "Sonic 2 Score Rush",
  "games/clsonic3andknuckles.html": "Sonic 3 and Knuckles",
  "games/clsonic3complete.html": "Sonic 3 Complete",
  "games/clsonic3dblastdx.html": "Sonic 3 D Blast Director's Cut",
  "games/clsonicadvance.html": "Sonic Advance",
  "games/clsonicadvance2.html": "Sonic Advance 2",
  "games/clsonicadvance2sp.html": "Sonic Advance 2 SP",
  "games/clsonicadvance3.html": "Sonic Advance 3",
  "games/clsonicandashuro.html": "Sonic and Ashuro",
  "games/clsonicandfallingstar.html": "Sonic and The Fallen Star",
  "games/clsonicandknuckles.html": "Sonic and Knuckles",
  "games/clsonicbattle.html": "Sonic Battle",
  "games/clsoniccd.html": "Sonic CD",
  "games/clsonicclassiccollection.html": "Sonic Classic Collection",
  "games/clsonicclassicheroes.html": "Sonic Classic Heroes",
  "games/clsoniccolors.html": "Sonic Colors",
  "games/clsonicdeltaorigins.html": "Sonic Delta Origins",
  "games/clsoniceexeog.html": "GXC Game",
  "games/clsonicerazor.html": "Sonic Erazor",
  "games/clsonicgg.html": "Sonic the Hedgehog",
  "games/clSonicHellfireSaga.html": "Sonic Hellfire Saga",
  "games/clsonicjam.html": "Sonic Jam",
  "games/clsonicmegamix.html": "Sonic Megamix",
  "games/clsonicr.html": "Sonic R",
  "games/clsonicrevert.html": "Sonic Revert",
  "games/clsonicrush.html": "Sonic Rush",
  "games/clsonicrushadventure.html": "Sonic Rush Adventure",
  "games/clsonicspinball.html": "Sonic Sp in Ball",
  "games/clsonicthehedgehog.html": "Sonic the Hedgehog",
  "games/clsonicthehedgehog2.html": "Sonic the Hedgehog 2",
  "games/clsonicthehedgehog3.html": "Sonic the Hedgehog 3",
  "games/clsonny2.html": "Sonny 2",
  "games/clsouljumper.html": "Soul Jumper",
  "games/clspacebarclicker.html": "SPACEBAR CLICKER",
  "games/clspacecompany.html": "Space Company",
  "games/clspaceinvaders.html": "Space Invaders",
  "games/clspaceiskey.html": "Space Is Key",
  "games/clspaceiskey2.html": "Space Is Key 2",
  "games/clspaceiskeyxmas.html": "Space Is Key Xmas",
  "games/clspacewarsbattleground.html": "Space Wars Battle Ground",
  "games/clspacewaves.html": "Space Waves",
  "games/clspeedperclick.html": "Obby",
  "games/clspeedstars.html": "Speed Stars",
  "games/clspelunky.html": "SpelunkyClassicHD",
  "games/clspewer.html": "Spewer",
  "games/clspiralroll.html": "Spiral Roll",
  "games/clSpongebobPowerKartGrandPrix.html": "Spongebob Power Kart Grand Prix",
  "games/clsprunked.html": "Sprunked",
  "games/clsprunki.html": "Sprunki",
  "games/clsprunkiclicker.html": "Sprunki Clicker",
  "games/clsquidplayground.html": "CalmarPG",
  "games/clstackballio.html": "Stack Fire Ball",
  "games/clstacktris.html": "Stacktris",
  "games/clstarfox.html": "Star Fox",
  "games/clstarfox64.html": "Star Fox 64",
  "games/clstarraiders.html": "Star Raiders",
  "games/clstateio.html": "state.io yt",
  "games/clstation141.html": "Station 141",
  "games/clstationmeltdown.html": "Station Meltdown",
  "games/clstationsaturn.html": "Station Saturn",
  "games/clsteakandjake.html": "Steak and Jake",
  "games/clstealbrainrot.html": "Another Steal a Brainrot",
  "games/clstealthassassin.html": "Stealth Assassin",
  "games/clstealthmaster.html": "Stealth Master",
  "games/clsteelempire.html": "Steel Empire",
  "games/clsteelsurge.html": "PICO-8 Cartridge",
  "games/clstickarchersbattle.html": "Stick archers battle",
  "games/clstickdefenders.html": "Stick Defenders",
  "games/clstickfighter.html": "StickFighter",
  "games/clstickjetchallenge.html": "Stickjet Challenge",
  "games/clstickmanandguns.html": "Stickman and Guns",
  "games/clstickmanclash.html": "Stickman Clash",
  "games/clstickmanduel.html": "Stickman Duel",
  "games/clstickmangtacity.html": "Stickman Gta City",
  "games/clstickmanhook.html": "Stickman Hook",
  "games/clStickmanKingdomclash.html": "Stickman Kingdom Clash",
  "games/clstickmankombat2d.html": "Stickman Kombat 2 D",
  "games/clstickmanstealingdiamond.html": "Henry Stickmin Stealing the Diamond",
  "games/clstickmerge.html": "Stick Merge",
  "games/clstickminairship.html": "Henry Stickmin Infiltrating the Airship",
  "games/clstickminbreakingbank.html": "Run 2",
  "games/clstickminescapingprison.html": "Henry Stickmin Escaping the Prison",
  "games/clstickminfleecomplex.html": "Henry Stickmin Fleeing the Complex",
  "games/clstickrpgcomplete.html": "Stick RPG",
  "games/clstickslasher.html": "Stick Slasher",
  "games/clstickwar.html": "Stick War",
  "games/clstickwar2.html": "Stick War 2",
  "games/clstormthehouse.html": "Storm the House",
  "games/clstormthehouse2.html": "Storm the House 2",
  "games/clstormthehouse3.html": "Storm the House 3",
  "games/clstrangejournet.html": "Shin Megami Tensei - Strange Journey",
  "games/clstreangeropepolice.html": "Amazing Strange Rope Police",
  "games/clstreetfighter2.html": "Street Fighter 2",
  "games/clstreetfighter2turbo.html": "Street Fighter 2 Turbo",
  "games/clstreetfighteralpha3.html": "Street Fighter Alpha 3",
  "games/clstreetfighterumuhsomething.html": "Super Street Fighter II Turbo Revival",
  "games/clstreetofrage.html": "Streets of Rage",
  "games/clstreetofrage2.html": "Streets of Rage 2",
  "games/clstreetofrage3.html": "Streets of Rage 3",
  "games/clstrikeforceheroes.html": "Strike Force Heroes",
  "games/clstrikeforceheroes2.html": "Strike Force Heroes 2",
  "games/clstrikeforceheroes3.html": "Deep Sleep",
  "games/clstrikerdummies.html": "Striker dummies",
  "games/clstylesavvy.html": "Style Savvy",
  "games/clsugarsugar.html": "Sugar Sugar",
  "games/clsuika.html": "Suika Game",
  "games/clsuikapico.html": "PICO-8 Cartridge",
  "games/clsunandmoon.html": "The Sun And Moon by Daniel Linssen",
  "games/clsuperbomberman.html": "Super Bomberman",
  "games/clsuperbomberman2.html": "Super Bomberman 2",
  "games/clsuperbomberman3.html": "Super Bomberman 3",
  "games/clsuperbomberman4.html": "Super Bomberman 4",
  "games/clsuperbomberman5.html": "Super Bomberman 5",
  "games/clsuperc.html": "Super C",
  "games/clsupercarrush.html": "Super Car Rush",
  "games/clsupercastlevaniaVI.html": "Super Castlevania IV",
  "games/clsuperchibiknight.html": "Super Chibi Knight",
  "games/clsupercold.html": "SUPERCOLD",
  "games/clsuperdarkdeception.html": "Super Dark Deception",
  "games/clsuperdiagonalmario2.html": "Super Diagonal Mario 2",
  "games/clsuperfallingfred.html": "Super Falling Fred Unblocked",
  "games/clsuperfighters.html": "Super Fighters",
  "games/clsuperhot.html": "SUPERHOT",
  "games/clsuperhotlinemiami.html": "Superhot Line Miami",
  "games/clsuperhouseofdeadninjas.html": "Super House of Dead Ninjas",
  "games/clsuperislandadventure.html": "Super Adventure Island",
  "games/clsuperliquidsoccer.html": "Super Liquid Soccer",
  "games/clsupermario.html": "Super Mario Bros",
  "games/clsupermario63.html": "Super Mario 63",
  "games/clsupermario64.html": "Super Mario 64",
  "games/clsupermario64ds.html": "Super Mario 64 DS",
  "games/clsupermarioallstars.html": "Super Mario All Stars",
  "games/clsupermariobros.html": "Super Mario Bros",
  "games/clsupermariobros2.html": "Super Mario Advance",
  "games/clsupermariobros2us.html": "Super Mario Bros. 2",
  "games/clsupermariobros3.html": "Super Mario Advance 4",
  "games/clsupermariokart.html": "Super Mario Kart",
  "games/clsupermarioland.html": "Super Mario Land",
  "games/clsupermarioland2.html": "Super Mario Land 2",
  "games/clsupermariomon.html": "mariomon",
  "games/clsupermariorpg.html": "Super Mario Rpg",
  "games/clsupermarioworld.html": "Super Mario World",
  "games/clsupermarioworld2.html": "Super Mario World 2 Yoshi's Island",
  "games/clSuperMarioWorldThe SecretOfThe7GoldenStatues.html": "Super Mario World the Secret of the 7 Golden Statues",
  "games/clsupermetroid.html": "Super Metroid",
  "games/clsupermonkeyballjr.html": "Super Monkey Ball Jr",
  "games/clsupernoahsark3D.html": "Super Noah’s Ark 3 D",
  "games/clsuperoliverworld.html": "Super Oliver World",
  "games/clsuperpickleballadventure.html": "Created with GameMaker Studio 2",
  "games/clsuperpunchout.html": "Super Punch Out",
  "games/clsuperpuzzlefighter2turbo.html": "Super Puzzle Fighter II Turbo",
  "games/clsuperscribblenauts.html": "Super Scribblenauts",
  "games/clsupersmashbros.html": "Super Smash Bros",
  "games/clsupersmashflash.html": "Super Smash Flash",
  "games/clsupersmashflash2.html": "Super Smash Flash 2",
  "games/clsupertiltbros.html": "Super Tilt Bros",
  "games/clsupitdept.html": "Steal a Brainrot",
  "games/clsurvevio.html": "survev.io",
  "games/clsurvivalracev2.html": "Survival Race",
  "games/clsushicat.html": "Sushi Cat",
  "games/clsushiunroll.html": "SUSHI unROLL",
  "games/clswitchblade.html": "Switchblade",
  "games/clswordandshieldultimateplus.html": "Pokemon sword and shield ultimate plus",
  "games/clswordfight.html": "Unity Web Player | Swordfight",
  "games/clswordsandsandals2.html": "Swords and Sandals",
  "games/clswordsandsouls.html": "Swords and Souls",
  "games/clsydneyshark.html": "Sydney Shark",
  "games/cltabletanks.html": "Table Tanks",
  "games/cltabletennisworldtour.html": "Table Tennis",
  "games/cltag-.html": "Tag",
  "games/cltagc3.html": "Tag",
  "games/clTaikonoTatsujin.html": "Taiko no Tatsujin DS - Touch de Dokodon! (Japan)",
  "games/cltaisei.html": "Taisei Project — Web version (Experimental!)",
  "games/cltakeover.html": "Takeover",
  "games/cltankpixel.html": "Tank Pixel",
  "games/cltanukisunset.html": "Unity Player",
  "games/cltapper.html": "Tapper",
  "games/cltaproad.html": "Tap Road",
  "games/cltastyplanet.html": "Effing Worms",
  "games/cltboilambeternal.html": "Binding of Isaac Wrath of the Lamb Eternal Edition",
  "games/cltecmobowl.html": "Tecmo Bowl",
  "games/cltelephonetrouble.html": "TelephoneTrouble",
  "games/cltelocation.html": "Telocation",
  "games/cltempest2000.html": "Tempest 2000",
  "games/cltempleofboom.html": "Temple of Boom",
  "games/cltemplerun2.html": "Temple Run 2",
  "games/cltempoverdose.html": "Tempoverdose",
  "games/clterra.html": "PICO-8 Cartridge",
  "games/clterritorialio.html": "Territorial.io",
  "games/cltetris.html": "Tetris",
  "games/cltetrisattack.html": "Tetris Attack",
  "games/cltetrisgba.html": "Tetris",
  "games/clthanksforremindingmeihadtofixthis.html": "Abandoned",
  "games/cltheclassroom.html": "The Classroom",
  "games/cltheclassroom2.html": "The Classroom 2",
  "games/cltheclassroom3.html": "The Classroom 3",
  "games/clthedeadseat.html": "The Deadseat",
  "games/clthedeepestsleep.html": "The Deepest Sleep",
  "games/cltheenchantedcave2.html": "The Enchanted Cave 2",
  "games/cltheimpossiblegame.html": "The Impossible Game",
  "games/cltheincrediblemachine.html": "The Incredible Machine",
  "games/clthelaststand.html": "Deep Sleep",
  "games/clthelaststandunioncity.html": "The Last Stand Union City",
  "games/clthemaninthewindow.html": "The Man from the Window",
  "games/clthemepark.html": "Theme Park",
  "games/clthepit.html": "The Pit",
  "games/clthereisnofile.html": "There Is No Game",
  "games/clthermomorph.html": "Thermomorph",
  "games/clthesodorrace.html": "The Sodor Race",
  "games/cltheyarecoming.html": "They Are Coming",
  "games/clthisistheonlylevel.html": "This Is the Only Level",
  "games/clthisistheonlyleveltoo.html": "This Is the Only Level Too",
  "games/clthreegoblets.html": "Three Goblets",
  "games/clthrowapotato.html": "Throw a Potato",
  "games/clthrowapotatoagain.html": "Throw a Potato Again",
  "games/clthwack.html": "Thwack",
  "games/cltiberiandawn.html": "Vanilla Conquer",
  "games/cltimeshooter2.html": "Time Shooter 2",
  "games/cltimeshooter3.html": "Time Shooter 3 SWAT",
  "games/cltimewarriors.html": "warriors 23.0",
  "games/cltinyfishing.html": "Tiny Fishing",
  "games/cltmnt.html": "Teenage Mutant Ninja Turtles Shredder's Re Revenge",
  "games/cltoastarling.html": "PICO-8 Cartridge",
  "games/cltoasterball.html": "Toasterball",
  "games/cltommorowandyesterday.html": "T&Y 3D",
  "games/cltomodachicollection.html": "Tomodachi Collection",
  "games/cltonyhawkskater2.html": "Tony Hawk’s Pro Skater 2",
  "games/cltonyhawkskater4.html": "Tony Hawk’s Pro Skater 4",
  "games/cltonyhawksunderground.html": "Tony Hawk’s Underground",
  "games/cltoomanytypes.html": "triple T's favorite game",
  "games/cltopspeedracing3d.html": "Top Speed Racing 3 D",
  "games/cltosstheturtle.html": "Toss the Turtle",
  "games/cltotm.html": "New Tab",
  "games/cltouhou.html": "Emscripten-Generated Code",
  "games/cltouhou2.html": "Emscripten-Generated Code",
  "games/cltouhou3.html": "Emscripten-Generated Code",
  "games/cltouhou4.html": "Emscripten-Generated Code",
  "games/cltouhou5.html": "Emscripten-Generated Code",
  "games/cltowerblocks.html": "Tower Blocks",
  "games/cltowercrash3d.html": "Tower Crash 3D",
  "games/cltownscraper.html": "game",
  "games/cltrace.html": "Trace",
  "games/cltrafficjam3d.html": "Traffic Jam 3D unblocked",
  "games/cltralalerotralalaescapetungtungtungsahur.html": "Tralalero Tralala Escape Tung Tung Tung Sahur",
  "games/cltrapthecat.html": "Chat Trap",
  "games/cltrechoroustrials.html": "Treacherous Trials",
  "games/cltrechoroustrialspart2.html": "Megachess",
  "games/cltriachnid.html": "Triachnid",
  "games/cltripleplay2000.html": "Triple Play 2000",
  "games/cltriviacrack.html": "Youtube Playable",
  "games/cltrollfacequest1.html": "Troll Face Quest 1",
  "games/cltrollfacequest10.html": "Troll Face Quest 10",
  "games/cltrollfacequest11.html": "Troll Face Quest 11",
  "games/cltrollfacequest12.html": "Troll Face Quest 12",
  "games/cltrollfacequest13.html": "Troll Face Quest 13",
  "games/cltrollfacequest2.html": "Troll Face Quest 2",
  "games/cltrollfacequest3.html": "Troll Face Quest 3",
  "games/cltrollfacequest4.html": "Troll Face Quest 4",
  "games/cltrollfacequest5.html": "Troll Face Quest 5",
  "games/cltrollfacequest6.html": "Troll Face Quest 6",
  "games/cltrollfacequest7.html": "Troll Face Quest 7",
  "games/cltrollfacequest8.html": "Troll Face Quest 8",
  "games/cltrollfacequest9.html": "Troll Face Quest 9",
  "games/cltrucksim.html": "In DI an Truck Simulator",
  "games/cltubejumpers.html": "Tube Jumpers",
  "games/cltungtungtungsahurobby.html": "Tung Tung Tung Sahur Obby",
  "games/cltunnelrush.html": "Tunnel Rush 1",
  "games/cltunnelrushbetter.html": "Better Tunnel Rush",
  "games/clturokdinosaurhunter.html": "Turok Dinosaur Hunter",
  "games/cltwinshot.html": "Twin Shot",
  "games/cltwistedmetal.html": "Twisted Metal",
  "games/cltwistedmetal2.html": "Twisted Metal 2",
  "games/cltwoball3d.html": "Two Ball 3 D",
  "games/clucds.html": "Top Speed Racing 3d - topVAZ",
  "games/cluckyblockobbyEUOPHRATESRIVER.html": "Lucky Blocks Obby",
  "games/clufoswampoddysey.html": "PICO-8 Cartridge",
  "games/clultimateassassian2.html": "Ultimate Assassin 2",
  "games/clultimateassassian3.html": "Ultimate Assassin 3",
  "games/clUltimatecardrivingsimulator.html": "Ultimate Car Driving Game",
  "games/clultimatemortalkombat.html": "Ultimate Mortal Kombat",
  "games/clultimatemortalkombat3.html": "Ultimate Mortal Kombat 3",
  "games/clultrakill.html": "Ultrakill (buggy)",
  "games/clumstickmangameidkiforgor.html": "Game title",
  "games/cluncannycatgolf.html": "Uncanny Cat Golf",
  "games/clunderneath.html": "Underneath",
  "games/clundertaleyellow.html": "UNDERTALE Yellow",
  "games/clunfairmarioworkquestionmark.html": "Unfair Mario",
  "games/clunfairundyne.html": "NGAHHH! Simulator v0.99",
  "games/clunicyclehero.html": "Uni_Poki_CustomPreloader",
  "games/clunitresdreams.html": "UNITRES - Tech Demo",
  "games/cluno.html": "Uno",
  "games/cluntime.html": "Untime",
  "games/clupgradecomplete.html": "Upgrade Complete",
  "games/clupgradecomplete2.html": "Upgrade Complete 2",
  "games/clupslash.html": "UpSlash",
  "games/clUZG.html": "UZG",
  "games/clvampiresurvivors.html": "Vampire Survivors",
  "games/clvanguard.html": "Vanguard",
  "games/clvaportrails.html": "Vapor Trails",
  "games/clvex.html": "Vex",
  "games/clvex2.html": "Vex 2",
  "games/clvex3.html": "Vex 3",
  "games/clvex3xmas.html": "Vex 3 Xmas",
  "games/clvex4.html": "Vex 4",
  "games/clvex5.html": "Vex 5",
  "games/clvex6.html": "Vex 6 Unblocked - xxx",
  "games/clvex7.html": "Vex 7 | BallBang",
  "games/clvex8.html": "Vex 8",
  "games/clvexchallenges.html": "Vex Challenges",
  "games/clvexx3m.html": "Vex X3M",
  "games/clvexx3m2.html": "Vex X3M 2",
  "games/clvillager.html": "PICO-8 Cartridge",
  "games/clvincentmansionofthedead.html": "Vincent Mansion of the Dead",
  "games/clvisitor.html": "The Visitor",
  "games/clvolleyrandom.html": "Volley Random",
  "games/clvollyballchallenge.html": "Ultimate Car Driving Game",
  "games/clvvvvvv.html": "VVVVVV",
  "games/clwaluigitacostand.html": "Waluigi’s Taco Stand",
  "games/clwarfare1944.html": "Warfare 1944",
  "games/clwarioland4.html": "Wario Land 4",
  "games/clwariowarediy.html": "War IO War E D.I.Y",
  "games/clwariowareinc.html": "Wario Ware Inc",
  "games/clwartheknight.html": "War the Knight",
  "games/clwaterpoolio.html": "Water Pool Heroes.io",
  "games/clwavedash.html": "Wave Dash",
  "games/clwaverace64.html": "Wave Race 64",
  "games/clwaverun.html": "Wave Run!",
  "games/clwebecomewhatwebehold.html": "We Become What We Behold",
  "games/clwebfishing.html": "autumn_webfishing_main",
  "games/clweltling.html": "Weltling",
  "games/clwermhole.html": "GMTK2025",
  "games/clwhackthetheif.html": "Whack the Thief",
  "games/clwhackyourboss.html": "Whack Your Boss",
  "games/clwhackyourcomputer.html": "Whack Your Computer",
  "games/clwheeliebike.html": "Wheelie Bike",
  "games/clwheely.html": "Wheely",
  "games/clwheely2.html": "Wheely 2",
  "games/clwheely3.html": "Wheely 3",
  "games/clwheely4.html": "Wheely 4",
  "games/clwheely5.html": "Wheely 5",
  "games/clwheely6.html": "Wheely 6",
  "games/clwheely7.html": "Wheely 7",
  "games/clwheely8.html": "Wheely 8",
  "games/clwindowsdoors.html": "Windows Doors",
  "games/clwinterfalling.html": "Winter Falling",
  "games/clwipeout2097.html": "Wipeout 2097",
  "games/clwitchcrafttd.html": "PICO-8 Cartridge",
  "games/clwolfenstein.html": "Wolfenstein 3D",
  "games/clwolfenstein3d.html": "Wolfenstein 3 D",
  "games/clwoodworm.html": "PICO-8 Cartridge",
  "games/clwordle.html": "Wordle",
  "games/clworldcup98.html": "FIFA World Cup 98",
  "games/clworldshardestgame.html": "World’s Hardest Game",
  "games/clworldshardestgame2.html": "World’s Hardest Game 2",
  "games/clworldshardestgame3.html": "World’s Hardest Game 3",
  "games/clworldshardestgame4.html": "World’s Hardest Game 4",
  "games/clwrassling.html": "Wrassling",
  "games/clwrestlebros.html": "Wrestle Bros &#127918; Play Now on the Official Site",
  "games/clXevious.html": "Xevious",
  "games/clyanderesimulator.html": "YandereSimulator",
  "games/clyarsrevenge.html": "Yar’s Revenge",
  "games/clyellow.html": "Yellow",
  "games/clYoshisStrangeQuest.html": "Yoshi’s Strange Quest",
  "games/clyouarelucky.html": "You Are Lucky",
  "games/clyouvs100skibidi.html": "google.com",
  "games/clyumenikki.html": "Yume Nikki",
  "games/clzdoom.html": "Z Doom",
  "games/clzelda2thelegendoflink.html": "Zelda 2 the Legend of Link",
  "games/clzenword.html": "Word Wonders",
  "games/clzoinkz.html": "Zoikz Defender",
  "games/clzombieexploder.html": "Zombie Exploder",
  "games/clzombieroad.html": "Zombie Road",
  "games/clzombierush.html": "Zombie Rush",
  "games/clzombiesatemyneighboors.html": "Zombies Ate My Neighbors",
  "games/clzombopaclypse2.html": "Zombocalypse 2",
  "games/clzombotron.html": "Zombotron",
  "games/clzombotron2.html": "Zombotron 2",
  "games/clzombotronreboot.html": "Zombotron",
  "games/clzrist.html": "Zrist",
  "games/clzuma.html": "Zuma",
  "games/clʘ.html": "ʘ"
};
