window.gameTitleMap = {
  "games/cl1.html": "1",
  "games/cl10minutestildawn.html": "10 Minutes Till Dawn",
  "games/cl10morebullets.html": "10 More Bullets",
  "games/cl12minibattles.html": "12 Mini Battles",
  "games/cl1on1soccer.html": "1 On 1 Soccer",
  "games/cl1v1tennis.html": "1 On 1 Tennis",
  "games/cl2048.html": "2048",
  "games/cl2048cupcakes.html": "2048 Cupcakes",
  "games/cl234playergame.html": "2-3-4 Player Games",
  "games/cl2Dshooting.html": "2D Shooting",
  "games/cl3pandas.html": "3 Pandas",
  "games/cl3pandasbrazil.html": "3 Pandas Brazil",
  "games/cl3pandasfantasy.html": "3 Pandas Fantasy",
  "games/cl3pandasjapan.html": "3 Pandas Japan",
  "games/cl3pandasnight.html": "3 Pandas Night",
  "games/cl3slices2.html": "3 Slices 2",
  "games/cl4thandgoal.html": "4th And Goal",
  "games/cl500calibercontractz.html": "500 Caliber Contractz",
  "games/cl60secondsburgerrun.html": "60 Seconds Burger Run",
  "games/cl8ballclassic.html": "8 Ball Classic",
  "games/cl8ballpool.html": "8 Ball Pool",
  "games/cl9007199254740992.html": "9007199254740992",
  "games/cl99balls.html": "99 Balls",
  "games/cl99nightsitf.html": "99 Nights In The Forest",
  "games/clabsolutemadness.html": "Absolute Madness",
  "games/clacecombat2.html": "Ace Combat 2",
  "games/clacecombat3.html": "Ace Combat 3",
  "games/clacegangstertaxi.html": "Ace Gangster Taxi",
  "games/clachievementunlocked.html": "Achievement Unlocked",
  "games/clachievmentunlocked2.html": "Achievement Unlocked 2",
  "games/clachievmentunlocked3.html": "Achievement Unlocked 3",
  "games/clachillies2.html": "Achilles 2",
  "games/clADarkRoom.html": "A Dark Room",
  "games/cladatewithdeath.html": "A Date With Death",
  "games/cladayintheoffice.html": "A Day In The Office",
  "games/clADOFAI.html": "A Dance of Fire and Ice",
  "games/cladvancewars.html": "Advance Wars",
  "games/cladvancewars2.html": "Advance Wars 2",
  "games/cladventneon.html": "Advent Neon",
  "games/clAdventureCapatalist.html": "Adventure Capitalist",
  "games/clagariolite.html": "Agar.io Lite",
  "games/clageofwar.html": "Age of War",
  "games/clageofwar2.html": "Age of War 2",
  "games/clagesofconflict.html": "Ages of Conflict",
  "games/clahoysurvival.html": "Ahoy Survival",
  "games/clakoopasrevenge2.html": "A Koopa's Revenge 2",
  "games/clakumanorgaiden.html": "Akumanor Gaiden",
  "games/clalienhominid.html": "Alien Hominid",
  "games/clalienhominidgba.html": "Alien Hominid",
  "games/clalienskyinvasion.html": "Alien Sky Invasion",
  "games/clalientransporter.html": "Alien Transporter",
  "games/clalienvspredator.html": "Alien vs. Predator",
  "games/clallbossesin1.html": "Paper Mario All Bosses In 1 Battle",
  "games/clallocation.html": "Allocation",
  "games/clamidstthesky.html": "Amidst The Sky",
  "games/clamigopancho.html": "Amigo Pancho",
  "games/clamigopancho2.html": "Amigo Pancho 2",
  "games/clamigopancho3.html": "Amigo Pancho 3",
  "games/clamigopancho4.html": "Amigo Pancho 4",
  "games/clamigopancho5.html": "Amigo Pancho 5",
  "games/clamigopancho6.html": "Amigo Pancho 6",
  "games/clamigopancho7.html": "Amigo Pancho 7",
  "games/clamongus.html": "Among Us",
  "games/clamorphous.html": "Amorphous +",
  "games/clancientsins.html": "Ancient Sins",
  "games/clangry-birdsspace.html": "Angry Birds Space",
  "games/clangrybirds.html": "Angry Birds",
  "games/clangrybirdsshowdown.html": "Angry Birds Showdown",
  "games/clanimalcrossingwildworld.html": "Animal Crossing-Wild World",
  "games/clanotherworld.html": "Another World",
  "games/clantimatterdimensions.html": "Antimatter Dimensions",
  "games/clapotris.html": "Apotris",
  "games/clappleshooter.html": "Apple Shooter",
  "games/clappleworm.html": "Apple Worm",
  "games/claquaparkio.html": "Aquapark.io",
  "games/clarceuslegend.html": "Pokemon Arceus Legend",
  "games/clarcheryworldtour.html": "Archery World Tour",
  "games/clarmormayhem2.html": "Armor Mayhem 2",
  "games/clarsonate.html": "Arsonate",
  "games/clarthursnightmare.html": "Arthur's Nightmare",
  "games/clascent.html": "Ascent",
  "games/clasmallworldcup.html": "A Small World Cup",
  "games/classesmentexaminationque.html": "Assessment Examination",
  "games/clasteroids.html": "Asteroids",
  "games/clasteroidsALT.html": "Asteroids",
  "games/clavalanche.html": "Avalanche",
  "games/claviamastersbuggy.html": "Aviamasters",
  "games/clAwesomePirates.html": "Awesome Pirates",
  "games/clawesomeplanes.html": "Awesome Planes",
  "games/clawesometanks.html": "Awesome Tanks",
  "games/clawesometanks2.html": "Awesome Tanks 2",
  "games/clB3313.html": "B3313",
  "games/clbabeltower.html": "Babel Tower",
  "games/clbabychiccoadventure.html": "Baby Chicco Adventure",
  "games/clbabykaizo.html": "Baby Kaizo World",
  "games/clbabysniperinvietnam.html": "Baby Sniper In Vietnam",
  "games/clbackrooms.html": "Backrooms",
  "games/clbackrooms2D.html": "Backrooms 2D",
  "games/clbackyardbaseball.html": "Backyard Baseball",
  "games/clbackyardbaseball09.html": "Backyard Baseball '09",
  "games/clbackyardbaseball10.html": "Backyard Baseball '10",
  "games/clbackyardfootball.html": "Backyard Football",
  "games/clbackyardsoccer.html": "Backyard Soccer",
  "games/clbaconmaydie.html": "Bacon May Die",
  "games/clbadbodyguards.html": "Bad Bodyguards",
  "games/clbadicecream.html": "Bad Ice Cream",
  "games/clbadmondaysimulator.html": "Bad Monday Simulator",
  "games/clbadparenting.html": "Bad Parenting",
  "games/clbadpiggies.html": "Bad Piggies",
  "games/clbadtimesim.html": "Bad Time Simulator",
  "games/clbalatrogba.html": "Balatro",
  "games/clbaldidecomp.html": "Baldi's Basics The Ultra Decompile",
  "games/clbaldisbasics.html": "Baldi's Basics",
  "games/clbaldisbasicsremaster.html": "Baldi's Basics Remastered",
  "games/clbaldisfunnewschoolultimate.html": "Baldi's Fun New School Ultimate",
  "games/clballblast.html": "Ball Blast",
  "games/clballsandbricksgood.html": "Balls And Bricks",
  "games/clballz.html": "BallZ",
  "games/clbananasimulator.html": "Banana Simulator",
  "games/clbanditgunslingers.html": "Bandit Gunslingers",
  "games/clbanjokazooie.html": "Banjo-Kazooie",
  "games/clbanjotooie.html": "Banjo-Tooie",
  "games/clbankrobbery2.html": "Bank Robbery 2",
  "games/clbarryhasasecret.html": "Barry Has a Secret",
  "games/clbas.html": "BAS",
  "games/clbaseballbros.html": "Baseball Bros",
  "games/clbasketballfrvr.html": "Basketball FRVR",
  "games/clbasketballlegends.html": "Basketball Legends 2020",
  "games/clbasketballstars.html": "Basketball Stars",
  "games/clbasketbattle.html": "Basket Battle",
  "games/clbasketbros.html": "Basket Bros",
  "games/clbasketrandom.html": "Basket Random",
  "games/clbasketslamdunk2.html": "Basket Slam Dunk 2",
  "games/clbatterup.html": "Batter Up",
  "games/clbattlekarts.html": "Battle Karts",
  "games/clbattles.html": "Battles",
  "games/clbattlesim.html": "Battle Simulator",
  "games/clbattlezone.html": "Battlezone",
  "games/clbballlegend.html": "Basketball Legends",
  "games/clbeachboxingsim.html": "Beach Boxing Simulator",
  "games/clbeamrider.html": "Beamrider",
  "games/clbearbarians.html": "Bearbarians",
  "games/clbearsus.html": "Bearsus",
  "games/clben10alienforce.html": "Ben 10 - Alien Force",
  "games/clben10omniverse.html": "Ben 10 - Omniverse",
  "games/clben10protector.html": "Ben 10 - Protector of Earth",
  "games/clben10racing.html": "Ben 10 - Galactic Racing",
  "games/clben10ultimatealien.html": "Ben 10 - Ultimate Alien",
  "games/clbergentruck201x.html": "BERGENTRUCK 201x",
  "games/clbfdia5b.html": "BFDIA 5b",
  "games/clBig_Time_Butter_Baron.html": "Big Time Butter Baron",
  "games/clbigicetowertinysquare.html": "Big Ice Tower Tiny Square",
  "games/clbigneontowertinysquare.html": "Big Neon Tower Tiny Square",
  "games/clbigshotboxing2.html": "Big Shot Boxing",
  "games/clbindingofisaccsheeptime.html": "Binding of Isaac Wrath of The Lamb",
  "games/clbioevil4.html": "Bio Evil 4",
  "games/clbitlife.html": "Bitlife",
  "games/clbitplanes.html": "Bit Planes",
  "games/clblackjack.html": "Blackjack",
  "games/clblackjackbattle.html": "Blackjack Battle",
  "games/clblackjackhhhh.html": "Blackjack",
  "games/clblacksmithlab.html": "Blacksmith Lab",
  "games/clblastronaut.html": "Blastronaut",
  "games/clblazedrifter.html": "Blaze Drifter",
  "games/clbleachvsnaruto.html": "Bleach vs. Naruto",
  "games/clblightborne.html": "Blightborne",
  "games/clblobsstory2.html": "Blob's Story 2",
  "games/clblockblast.html": "Block Blast",
  "games/clblockcraftparkour.html": "Minecraft Parkour",
  "games/clblockcraftshooter.html": "Minecraft Shooter",
  "games/clblockpost.html": "Blockpost",
  "games/clblockthepig.html": "Block the Pig",
  "games/clblockydemolitionderby.html": "Blocky Demolition Derby",
  "games/clblockysnakes.html": "Blocky Snakes",
  "games/clbloodmoney.html": "Bloodmoney",
  "games/clbloodtournament.html": "Blood Tournament",
  "games/clbloons.html": "Bloons",
  "games/clbloons2.html": "Bloons 2",
  "games/clbloonspp1.html": "Bloons Player Pack 1",
  "games/clbloonspp2.html": "Bloons Player Pack 2",
  "games/clbloonspp3.html": "Bloons Player Pack 3",
  "games/clbloonspp4.html": "Bloons Player Pack 4",
  "games/clbloonspp5.html": "Bloons Player Pack 5",
  "games/clbloonsTD1.html": "BTD1",
  "games/clbloonsTD2.html": "BTD2",
  "games/clbloonsTD3.html": "BTD3",
  "games/clbloonsTD4.html": "BTD4",
  "games/clbloonsTD6scratch.html": "BTD6 (scratch)",
  "games/clbloxorz.html": "Bloxorz",
  "games/clblumgiracers.html": "Blumgi Racers",
  "games/clblumgirocket.html": "Blumgi Rocket",
  "games/clBMX2.html": "Mat Hoffman's Pro BMX 2",
  "games/clbobtherobber.html": "Bob the Robber",
  "games/clbobtherobber2.html": "Bob the Robber 2",
  "games/clbobtherobber5.html": "Bob the Robber 5",
  "games/clbomberman.html": "Bomberman",
  "games/clbomberman2.html": "Bomberman 2",
  "games/clbombermanhero.html": "Bomberman Hero",
  "games/clbombermanworld.html": "Bomberman World",
  "games/clboomslingers.html": "Boom Slingers",
  "games/clbottlecracks.html": "Bottle Cracks",
  "games/clbounceback.html": "Bounce Back",
  "games/clbouncemasters.html": "Bouncemasters",
  "games/clbouncybasketball.html": "Bouncy Basketball",
  "games/clbouncymotors.html": "Bouncy Motors",
  "games/clBountyOfOne.html": "Bounty of One",
  "games/clbowmaster.html": "Bowmasters",
  "games/clboxhead2playrooms.html": "Boxhead 2play Rooms",
  "games/clboxheadnightmare.html": "Boxhead Nightmare",
  "games/clboxinglive-2.html": "Boxing Live 2",
  "games/clboxingrandom.html": "Boxing Random",
  "games/clbrainrot.html": "Also Steal A Brainrot",
  "games/clbridgerace.html": "Bridge Race",
  "games/clbtd5.html": "BTD5",
  "games/clbtts.html": "Big Tower Tiny Square",
  "games/clbtts2.html": "Big Tower Tiny Square 2",
  "games/clbubbleshooter.html": "Bubble Shooter",
  "games/clbubbleshooterpirate.html": "Bubble Shooter Pirate",
  "games/clbubbletanks.html": "Bubble Tanks",
  "games/clbubbletanks2.html": "Bubble Tanks 2",
  "games/clbubbletanks3.html": "Bubble Tanks 3",
  "games/clbubbletanksarenas.html": "Bubble Tanks Arenas",
  "games/clbubbletankstd.html": "Bubble Tanks Tower Defense",
  "games/clbubsy.html": "Bubsy",
  "games/clbuildnowgg.html": "BuildNow.GG",
  "games/clbunnyland.html": "Bunnyland",
  "games/clburgerandfrights.html": "Burger and Frights",
  "games/clburritobison.html": "Burrito Bison",
  "games/clburritobisonlaunchalibre.html": "Burrito Bison Launcha Libre",
  "games/clburritobisonrevenge.html": "Burrito Bison Revenge",
  "games/clbushidoblade.html": "Bushido Blade",
  "games/clcactusmccoy.html": "Cactus Mccoy",
  "games/clcactusmccoy2.html": "Cactus Mccoy 2",
  "games/clcannonballs3d.html": "Cannon Balls 3D",
  "games/clcannonfodder.html": "Cannon Fodder",
  "games/clcaptainlang.html": "Captain Lang",
  "games/clcapybaraclicker.html": "Capybara Clicker",
  "games/clcarcrash3.html": "Car Crash 3",
  "games/clcardrawing.html": "Car Drawing",
  "games/clcareatscar2deluxe.html": "Car Eats Car 2 Deluxe",
  "games/clcarkingarena.html": "Car King Arena",
  "games/clCartoonNetworkTableTennisUltimateTournament.html": "Cartoon Network Table Tennis Ultimate Tournament",
  "games/clcastlebloodline.html": "Castlevania - Bloodlines",
  "games/clcastlecircleofmoon.html": "Castlevania - Circle of the Moon",
  "games/clcastlevania.html": "Castlevania",
  "games/clcastlevania2.html": "Castlevania 2",
  "games/clcastlevania3.html": "Castlevania 3",
  "games/clcastlevaniadawnofsorrow.html": "Castlevania Dawn of Sorrow",
  "games/clcastlevanianes.html": "Castlevania",
  "games/clcastlewarsmodern.html": "Castle Wars Modern",
  "games/clcatmario.html": "Cat Mario (flash)",
  "games/clcatmariogood.html": "Cat Mario",
  "games/clcatslovecake2.html": "Cats Love Cake 2",
  "games/clcavestory.html": "Cave Story",
  "games/clceleste.html": "Celeste Pico",
  "games/clceleste2.html": "Celeste 2",
  "games/clcellardoor.html": "Cellar Door",
  "games/clchainofmemories.html": "Kingdom Hearts - Chain of Memories",
  "games/clchaosfaction2.html": "Chaos Faction 2",
  "games/clcheckers.html": "Checkers",
  "games/clcheesechompers3d.html": "Cheese Chompers 3D",
  "games/clcheshireinachatroom.html": "Cheshire In a Chatroom",
  "games/clchess.html": "Chess",
  "games/clchessclassic.html": "Chess Classic",
  "games/clchibiknight.html": "Chibi Knight",
  "games/clchickenscream.html": "Chicken Scream",
  "games/clchickenwar.html": "Chickenwar",
  "games/clchipschallenge.html": "Chip's Challenge",
  "games/clchoppyorc.html": "Choppy Orc",
  "games/clchronotrigger.html": "Chrono Trigger",
  "games/clchuzzle.html": "Chuzzle",
  "games/clCircloO2.html": "CircloO 2",
  "games/clciviballs.html": "Civiballs",
  "games/clciviballs2.html": "Civiballs 2",
  "games/clclashofvikings.html": "Clash Of Vikings",
  "games/clclassof09.html": "Class of '09",
  "games/clcleanupio.html": "Cleanup.io",
  "games/clclearvision.html": "Clear Vision",
  "games/clclearvision2.html": "Clear Vision 2",
  "games/clclearvision3.html": "Clear Vision 3",
  "games/clclearvision4.html": "Clear Vision 4",
  "games/clclearvision5.html": "Clear Vision 5",
  "games/clclmadnessambulation.html": "Madness Ambulation",
  "games/clclubbytheseal.html": "Clubby The Seal",
  "games/clclusterrush.html": "Cluster Rush",
  "games/clcoalllcdemo.html": "Coal LLC",
  "games/clcod4.html": "Call of Duty 4 - Modern Warfare",
  "games/clcodblackopp.html": "Call of Duty - Black Ops",
  "games/clcoddefiance.html": "Call of Duty - Modern Warfare 3 - Defiance",
  "games/clcodenamegordon.html": "Codename Gordon",
  "games/clcodmodernwarfare.html": "Call of Duty - Modern Warfare - Mobilized",
  "games/clcodworldatwar.html": "Call of Duty - World at War",
  "games/clcoffeemaker.html": "Coffee Maker",
  "games/clcombopool.html": "Combo Pool",
  "games/clcommandandconquer.html": "Command and Conquer",
  "games/clcommanderkeen4.html": "Commander Keen 4",
  "games/clcommanderkeen5.html": "Commander Keen 5",
  "games/clcommanderkeen6.html": "Commander Keen 6",
  "games/clconkersbadfurday.html": "Conker's Bad Fur Day",
  "games/clcontra.html": "Contra",
  "games/clcontra3.html": "Contra III The Alien Wars",
  "games/clcookie-clicker.html": "Cookie Clicker",
  "games/clcookingmama.html": "Cooking Mama",
  "games/clcookingmama2.html": "Cooking Mama 2",
  "games/clcookingmama3.html": "Cooking Mama 3",
  "games/clcoreball.html": "Core Ball",
  "games/clcotlk.html": "Curse of the Lich King",
  "games/clcoverorange.html": "Cover Orange",
  "games/clcoverorange2.html": "Cover Orange 2",
  "games/clcoverorangejourneygangsters.html": "Cover Orange Journey Gangsters",
  "games/clcoverorangejourneyknights.html": "Cover Orange Journey Knights",
  "games/clcoverorangejourneypirates.html": "Cover Orange Journey Pirates",
  "games/clcoverorangejourneyspace.html": "Cover Orange Journey Space",
  "games/clcoverorangeplayerspack.html": "Cover Orange Players Pack",
  "games/clcoverorangeplayerspack2.html": "Cover Orange Players Pack 2",
  "games/clcrankit!.html": "Crank It!",
  "games/clcrashbandicoot.html": "Crash Bandicoot",
  "games/clcrashbandicoot2.html": "Crash Bandicoot 2",
  "games/clcrashteamracing.html": "Crash Team Racing",
  "games/clcrazycars.html": "Crazy Cars",
  "games/clcrazycattle3d.html": "Crazy Cattle 3D",
  "games/clcrazychicken3D.html": "Crazy Chicken 3D",
  "games/clcrazyfrogracer.html": "Crazy Frog Racer",
  "games/clcrazymotorcycle.html": "Crazy Motorcycle",
  "games/clcreaturecardidle.html": "Creature Card Idle",
  "games/clcreeperworld2.html": "Creeper World 2",
  "games/clcrossyroad.html": "Crossy Road",
  "games/clcrunchball3000.html": "Crunchball 3000",
  "games/clcs1.6.html": "C.S 1.6",
  "games/clcsds.html": "Counter Strike DS",
  "games/clcsgoclicker.html": "Csgo Clicker",
  "games/clctgpnitro.html": "CTGP Nitro",
  "games/clcurveball.html": "Curve Ball",
  "games/clcuttherope.html": "Cut the Rope",
  "games/clcyberbungracing.html": "Cyberbung Racing",
  "games/clcybersensation.html": "Friday Night Funkin Vs. Cyber Sensation",
  "games/cldadgame.html": "Dadgame",
  "games/cldadnme.html": "Dad n Me",
  "games/cldandysworldclicker.html": "Dandy's World Clicker",
  "games/cldanktomb.html": "Dank Tomb",
  "games/cldborigins.html": "Dragon Ball Origins",
  "games/cldborigins2.html": "Dragon Ball Origins 2",
  "games/cldbsniper.html": "Double Barrel Sniper",
  "games/cldbzattacksaiyans.html": "Dragon Ball Z - Attack Of the Saiyans",
  "games/cldbzdevolution.html": "Dragon Ball Z - Devolution",
  "games/cldbzsuperwarriorssonic.html": "Dragon Ball Z - Supersonic Warriors",
  "games/cldbzwarriors2.html": "Dragon Ball Z - Supersonic Warriors 2",
  "games/cldeadestate.html": "Dead Estate",
  "games/cldeadlydescent.html": "Deadly Descent",
  "games/cldeadplate.html": "Dead Plate",
  "games/cldeadzed.html": "Dead Zed",
  "games/cldeadzed2.html": "Dead Zed 2",
  "games/cldeathchase.html": "Death Chase",
  "games/cldeblob2.html": "De Blob 2",
  "games/cldecision.html": "Decision",
  "games/cldecision2.html": "Decision 2",
  "games/cldecision3.html": "Decision 3",
  "games/cldecisionmedieval.html": "Decision Medieval",
  "games/cldeepersleep.html": "Deeper Sleep",
  "games/cldeepestsword.html": "Deepest Sword",
  "games/cldefendyourcastle.html": "Defend Your Castle",
  "games/cldefendyournuts.html": "Defend Your Nuts",
  "games/cldefendyournuts2.html": "Defend Your Nuts 2",
  "games/cldeltarune.html": "Deltarune",
  "games/cldeltatraveler.html": "Deltatraveler",
  "games/cldementium.html": "Dementium - The Ward",
  "games/cldemolitionderbycrashracing.html": "Demolition Derby Crash Racing",
  "games/cldemonbluff.html": "Demon Bluff",
  "games/cldiablo.html": "Diablo",
  "games/cldiamondhollow.html": "Diamond Hollow",
  "games/cldiamondhollow2.html": "Diamond Hollow 2",
  "games/cldiddykong-racing.html": "Diddy Kong Racing",
  "games/cldieinthedungeon.html": "Die in the Dungeon",
  "games/cldigdug.html": "Dig Dug",
  "games/cldigdug2.html": "Dig Dug 2",
  "games/cldigdug26.html": "Dig Dug",
  "games/cldigtochina.html": "Dig to China",
  "games/cldinodudes.html": "Evolution-dino Dudes",
  "games/cldiredecks.html": "Dire Decks",
  "games/cldoblox.html": "Doblox",
  "games/cldogeminer.html": "Doge Miner",
  "games/cldogeminer2.html": "Doge Miner 2",
  "games/cldokidokiliteratureclub.html": "Doki Doki Literature Club",
  "games/cldonkeykong.html": "Donkey Kong",
  "games/cldonkeykong64.html": "Donkey kong 64",
  "games/cldonkeykongcountry.html": "Donkey Kong Country",
  "games/cldonkeykongcountry2.html": "Donkey Kong Country 2",
  "games/cldonkeykongcountry3.html": "Donkey Kong Country 3",
  "games/cldonkeykongnes.html": "Donkey Kong",
  "games/cldontescape.html": "Don't Escape",
  "games/cldontescape2.html": "Don't Escape 2",
  "games/cldontescape3.html": "Don't Escape 3",
  "games/cldoodlejumpgoober.html": "Doodle Jump",
  "games/cldoom.html": "Doom",
  "games/cldoom2.html": "Doom 2",
  "games/cldoom2d.html": "Doom 2D",
  "games/cldoom2dDOS.html": "Doom 2D",
  "games/cldoom2dos.html": "Doom 2",
  "games/cldoom3pack.html": "Doom Triple Pack",
  "games/cldoom64.html": "Doom 64",
  "games/cldoomdos.html": "Doom",
  "games/cldoomemscripten.html": "Doom Emscripten",
  "games/cldoomps.html": "Doom",
  "games/cldoomzio.html": "Doomz.io",
  "games/cldouchebaglife.html": "Douchebag Life",
  "games/cldragonballadvance.html": "Dragon Ball Advanced Adventure",
  "games/clDragonBallZTheLegacyofGoku.html": "Dragon Ball Z - the Legacy of Goku",
  "games/clDragonQuestIX.html": "Dragon Quest IX",
  "games/cldrawclimber.html": "Draw Climber",
  "games/cldrawntolife.html": "Drawn To Life",
  "games/cldrawntolife2.html": "Drawn To Life - The Next Chapter",
  "games/cldrawtheline.html": "Draw the Line",
  "games/cldreader.html": "Dreader",
  "games/cldreadheadparkour.html": "Dreadhead Parkour",
  "games/cldriftboss.html": "Drift Boss",
  "games/cldrifthuntersmerge.html": "Drift Hunters",
  "games/cldrivemady.html": "Drive Mad",
  "games/cldrivenwild.html": "Driven Wild",
  "games/cldrmario.html": "Dr. Mario",
  "games/cldrweedgaster.html": "Dr. Weed Gaster",
  "games/cldubstep.html": "Crazy Crash Landing",
  "games/clduckhunt.html": "Duck hunt",
  "games/clducklfe5.html": "Duck Life 5",
  "games/clducklife.html": "Duck Life",
  "games/clducklife2.html": "Duck Life 2",
  "games/clducklife3.html": "Duck Life 3",
  "games/clducklife4.html": "Duck Life 4",
  "games/clducklifebattle.html": "Duck Life Battle",
  "games/clducklifespace.html": "Duck Life Space",
  "games/clducklingsio.html": "Ducklings.io",
  "games/clducktales.html": "Ducktales",
  "games/cldud.html": "DUD",
  "games/cldukenukem3d.html": "Duke Nukem 3D",
  "games/cldumpling.html": "Dumpling",
  "games/cldungeondeck.html": "Dungeon Deck",
  "games/cldungeonraid.html": "Dungeon Raid",
  "games/cldungeonsanddegenerategamblers.html": "Dungeons And Degenerate Gamblers",
  "games/cldunkshot.html": "Dunk Shot",
  "games/clduskchild.html": "Dusk Child",
  "games/cldyingdreams.html": "Dying Dreams",
  "games/cldynamiteheaddy.html": "Dynamite Headdy",
  "games/cleagleride.html": "Eagle Ride",
  "games/clearntodie.html": "Earn to Die",
  "games/clearntodie2.html": "Earn to Die 2",
  "games/clearthbound.html": "Earthbound",
  "games/clearthbound3.html": "Earthbound 3",
  "games/clearthboundsnes.html": "Earthbound",
  "games/clearthtaken.html": "Earth Taken",
  "games/clearthtaken2.html": "Earth Taken 2",
  "games/clearthtaken3.html": "Earth Taken 3",
  "games/clearthwormjim.html": "Earthworm Jim",
  "games/clearthwormjim2.html": "Earthworm Jim 2",
  "games/cledelweiss.html": "Edelweiss",
  "games/cledyscarsimulator.html": "Edy's Car Simulator",
  "games/cleffinghail.html": "Effing Hail",
  "games/cleffingmachines.html": "Effing Machines",
  "games/cleffingworms.html": "Effing Worms",
  "games/cleffingzombies.html": "Effing Zombies",
  "games/clegg.html": "Egg",
  "games/cleggycar.html": "Eggy Car",
  "games/clelasticface.html": "Elastic Face",
  "games/clelectricman2.html": "Electricman 2",
  "games/clemujs.html": "EMULATOR",
  "games/clenchain.html": "Enchain",
  "games/clendlesswar4.html": "Endless War 4",
  "games/clendlesswar5wow.html": "Endless War 5",
  "games/clendlesswar7.html": "Endless War 7",
  "games/clenduro.html": "Enduro",
  "games/clepicbattlefantasy5.html": "Epic Battle Fantasy 5",
  "games/clescalatingduel.html": "Escalating Duel",
  "games/clescaperoad-2.html": "Escape Road 2",
  "games/clescaperoad.html": "Escape Road",
  "games/clet.html": "E.T. - the Extra-Terrestrial",
  "games/cletrianoddyssey.html": "Etrian Odyssey",
  "games/clevilglitch.html": "Evil Glitch",
  "games/clevolution.html": "Evolution",
  "games/clexcitebike64.html": "Excitebike 64",
  "games/clexoobservation.html": "Exoplanet Observation",
  "games/clfactoryballs.html": "Factory Balls",
  "games/clfactoryballs2.html": "Factory Balls 2",
  "games/clfactoryballs3.html": "Factory Balls 3",
  "games/clfactoryballs4.html": "Factory Balls 4",
  "games/clfairytalevsonepiece.html": "Fairy Tale vs. One Piece",
  "games/clfallguys.html": "Fall Guys",
  "games/clfallout.html": "Fallout",
  "games/clfamidash.html": "Famidash",
  "games/clfancypantsadventure.html": "Fancy Pants Adventure",
  "games/clfancypantsadventure2.html": "Fancy Pants Adventure 2",
  "games/clfancypantsadventure3.html": "Fancy Pants Adventure - World 3",
  "games/clfancysnowboarding.html": "Fancy Snowboarding",
  "games/clfashionbattle.html": "Fashion Battle",
  "games/clfattygenius.html": "Fatty Genius",
  "games/clfeedus2.html": "Feed Us 2",
  "games/clfeedus3.html": "Feed Us 3",
  "games/clfeedus4.html": "Feed Us 4",
  "games/clfeedus5.html": "Feed Us 5",
  "games/clFF3.html": "Final Fantasy III",
  "games/clff6.html": "Final Fantasy VI",
  "games/clffmysticquest.html": "Final Fantasy Mystic Quest",
  "games/clFFsonic1.html": "Final Fantasy Sonic X Episode 1",
  "games/clFFsonic2.html": "Final Fantasy Sonic X Episode 2",
  "games/clFFsonic3.html": "Final Fantasy Sonic X Episode 3",
  "games/clFFsonic4.html": "Final Fantasy Sonic X Episode 4",
  "games/clFFsonic5.html": "Final Fantasy Sonic X Episode 5",
  "games/clFFsonic61.html": "Final Fantasy Sonic X Episode 6 part 1",
  "games/clFFsonic62.html": "Final Fantasy Sonic X Episode 6 part 2",
  "games/clFIFA07.html": "FIFA 07",
  "games/clFIFA10.html": "FIFA 10",
  "games/clFIFA11.html": "FIFA 11",
  "games/clfifa2000.html": "FIFA 2000",
  "games/clFIFA99.html": "FIFA 99",
  "games/clFIFAinternationalsoccer.html": "FIFA International Soccer",
  "games/clFIFAroadtoworldcup98.html": "FIFA Road To World Cup 98",
  "games/clFIFAsoccer06.html": "FIFA Soccer 06",
  "games/clFIFAsoccer95.html": "FIFA Soccer 95",
  "games/clFIFAsoccer96.html": "FIFA Soccer 96",
  "games/clFIFAsoccer97.html": "FIFA Soccer 97",
  "games/clFIFAstreet2.html": "FIFA Street 2",
  "games/clfinalearth2.html": "Final Earth 2",
  "games/clfinalfantasy.html": "Final Fantasy",
  "games/clfinalfantasyII.html": "Final Fantasy II",
  "games/clfinalfantasytactics.html": "Final Fantasy Tactics",
  "games/clfinalfantasyVII.html": "Final Fantasy VII (disc one)",
  "games/clfinalfantasyVIId2.html": "Final Fantasy VII (disc two)",
  "games/clfinalfantasyVIId3.html": "Final Fantasy VII (disc three)",
  "games/clfinalninja.html": "Final Ninja",
  "games/clfindthealien.html": "Find The Alien",
  "games/clfireblob.html": "Fireblob",
  "games/clfireboyandwatergirl.html": "Fireboy and Watergirl",
  "games/clfireboyandwatergirl2.html": "Fireboy and Watergirl 2",
  "games/clfireboyandwatergirl3.html": "Fireboy and Watergirl 3",
  "games/clfireemblem.html": "Fire Emblem",
  "games/clfisheatgettingbig.html": "Fish Eat Getting Big",
  "games/clfisquarium.html": "Fisquarium",
  "games/clfivenightsatbaldisredone.html": "Five Nights at Baldis Redone",
  "games/clflashsonic.html": "Ultimate Flash Sonic",
  "games/clfloodrunner.html": "Flood Runner",
  "games/clfloodrunner2.html": "Flood Runner 2",
  "games/clfloodrunner4.html": "Flood Runner 4",
  "games/clfluidism.html": "Fluidism",
  "games/clfnac1.html": "Five Nights at Candy's 1",
  "games/clfnac2.html": "Five Nights at Candy's 2",
  "games/clFNAF.html": "FNAF",
  "games/clFNAF2.html": "FNAF 2",
  "games/clFNAF3.html": "FNAF 3",
  "games/clFNAF4.html": "FNAF 4",
  "games/clfnaf4halloween.html": "FNAF 4 Halloween",
  "games/clfnafps.html": "FNAF Pizzeria Simulator",
  "games/clfnafsl.html": "FNAF Sister Location",
  "games/clfnafucn.html": "FNAF Ultimate Custom Night",
  "games/clfnafworldd.html": "FNAF World",
  "games/clfnaw.html": "Five Nights at Winston's",
  "games/clfnfagoti.html": "Friday Night Funkin' VS A.G.O.T.I",
  "games/clfnfanimation.html": "Animation vs Friday Night Funkin'",
  "games/clfnfannie.html": "Friday Night Funkin' V.S. Annie",
  "games/clfnfbelowdepths.html": "Friday Night Funkin- Below The Depths",
  "games/clfnfbfdi26.html": "Friday Night Funkin Vs. BFDI 26",
  "games/clfnfbside.html": "Friday Night Funkin B-Sides",
  "games/clfnfcamelliarudeblaster.html": "Friday Night Funkin' Vs Camellia RUDE BUSTER",
  "games/clfnfchara.html": "Friday Night Funkin' - V.S Chara",
  "games/clfnfcory.html": "Friday Night Funkin vs. CoryXKenshion",
  "games/clfnfcrunchin.html": "Friday Night Crunchin'",
  "games/clfnfdropandroll.html": "Friday Night Funkin' Drop and Roll, but Playable",
  "games/clfnfdustin.html": "Friday Night Dustin'",
  "games/clfnffleetway.html": "Friday Night Funkin Chaos Nightmare (fleetway)",
  "games/clfnffnaf3.html": "Friday Night Funkin Vs. FNAF 3",
  "games/clfnfgamebreakerbundle.html": "Friday Night Funkin' GameBreaker Bundle",
  "games/clfnfhank.html": "Friday Night Funkin' VS Accelerant Hank",
  "games/clfnfhex.html": "Friday Night Funkin vs. Hex",
  "games/clfnfholiday.html": "Friday Night Funkin' The Holiday Mod",
  "games/clfnfhorkglorpgloop.html": "Friday Night Funkin HORKGLORPGLOOP",
  "games/clfnfhypnoslullaby.html": "Friday Night Funkin vs Hypno Lullaby",
  "games/clfnfimposter3.html": "Friday Night Funkin VS Impostor v3",
  "games/clfnfimposterv4.html": "Friday Night Funkin VS Impostor v4",
  "games/clfnfmarioport.html": "Mario FNF Port",
  "games/clfnfmidfight.html": "Friday Night Funkin' Sarvente's Mid-Fight Masses",
  "games/clfnfmiku.html": "Friday Night Funkin vs. Hatsune Miku",
  "games/clfnfneo.html": "Friday Night Funkin Neo",
  "games/clfnfpiggyfield.html": "Friday Night Funkin' Piggyfied",
  "games/clfnfplutoshi.html": "Friday Night Funkin' Pluto's Reprisal Part 1",
  "games/clfnfpokepastaperdition.html": "Friday Night Funkin' VS Pokepasta Perdition",
  "games/clfnfqt.html": "Friday Night Funkin vs QT",
  "games/clfnfrewrite.html": "Friday Night Funkin VS Rewrite",
  "games/clfnfselfpaced.html": "Friday Night Funkin' Self-Paced, but Playable",
  "games/clfnfshaggy4keys.html": "Friday Night Funkin vs Shaggy only 4 keys",
  "games/clfnfshucks-v2.html": "Friday Night Funkin' Shucks V2",
  "games/clfnfsky.html": "Friday Night Funkin VS Sky",
  "games/clfnfsoft.html": "Friday Night Funkin' Soft",
  "games/clfnftricky.html": "Friday Night Funkin vs. Tricky",
  "games/clfnfTWIDDLEFINGER.html": "Friday Night Funkin' TwiddleFinger",
  "games/clfnfundertale.html": "Friday Night Funkin' Undertale",
  "games/clfnfvoid.html": "Friday Night Funkin' - Vs Void",
  "games/clfnfwednesday-infedility.html": "Friday Night Funkin' Wednesday's Infidelity",
  "games/clfnfwhitty.html": "Friday Night Funkin vs. Whitty",
  "games/clfnfzardy.html": "Friday Night Funkin vs. Zardy",
  "games/clfocus.html": "Focus",
  "games/clfolderdungeon.html": "Folder Dungeon",
  "games/clfootballbros.html": "Football Bros",
  "games/clfootballlegends.html": "Football Legends",
  "games/clforknsausage.html": "Fork n Sausage",
  "games/clfortzone.html": "Fortzone Battle Royale",
  "games/clfpa4p1.html": "Fancy Pants Adventure 4 Part 1",
  "games/clfpa4p2.html": "Fancy Pants Adventure 4 Part 2",
  "games/clfreegemas.html": "Freegemas",
  "games/clfreerider.html": "Free Rider",
  "games/clfreerider2.html": "Free Rider 2",
  "games/clfreerider3.html": "Free Rider 3",
  "games/clfridaynightfunkin.html": "Friday Night Funkin",
  "games/clfromrusttoash.html": "From Rust To Ash",
  "games/clfruitninja.html": "Fruit Ninja",
  "games/clfunnybattle.html": "Funny Battle Simulator",
  "games/clfunnybattle2.html": "Funny Battle Simulator 2",
  "games/clfunnymadracing.html": "Funny Mad Racing",
  "games/clfunnyshooter22.html": "Funny Shooter 2",
  "games/clfzero.html": "F-zero",
  "games/clfzerox.html": "F-zero X",
  "games/clgachaverse.html": "Gachaverse",
  "games/clgalaga.html": "Galaga",
  "games/clgameandwatchcollection.html": "Game And Watch Collection",
  "games/clgangstabean.html": "Gangsta Bean",
  "games/clgangstabean2.html": "Gangsta Bean 2",
  "games/clgangsterbros.html": "Gangster Bros",
  "games/clgarcello.html": "Friday Night Funkin vs. Garcello",
  "games/clgdlite.html": "Geometry Dash Lite",
  "games/clgdsubzero.html": "Geometry Dash Subzero (scratch)",
  "games/clgeneralchaos.html": "General Chaos",
  "games/clgenericfightermaybe.html": "Generic Fighter Maybe",
  "games/clgeometrydashscratch.html": "Geometry Dash Scratch",
  "games/clgeometryvibes.html": "Geometry Vibes",
  "games/clgeorgeandtheprinter.html": "George And The Printer",
  "games/clgetawayshootout.html": "Getaway Shootout",
  "games/clgetontop.html": "Get On Top",
  "games/clGettothetopalthoughthereisnotop.html": "Get to the Top Although There Is No Top",
  "games/clgetyoked.html": "Get Yoked",
  "games/clggshinobi.html": "G. G. Shinobi",
  "games/clghosttrick.html": "Ghost Trick - Phantom Detective",
  "games/clgimmietheairpod.html": "Gimme the Airpod",
  "games/clgladdihoppers.html": "Gladihoppers",
  "games/clglfighters.html": "GLFighters",
  "games/clgloryhunters.html": "Glory Hunters",
  "games/clglover.html": "Glover",
  "games/clgoalsouthafrica.html": "Goal South Africa",
  "games/clgobble.html": "Gobble",
  "games/clgoingballs.html": "Going Balls",
  "games/clgolddiggerfrvr.html": "Gold Digger FRVR",
  "games/clgoldeneye007.html": "Goldeneye 007",
  "games/clgoldensun.html": "Golden Sun",
  "games/clgoldensunnds.html": "Golden Sun - Dark Dawn",
  "games/clGoldenSunTheLostAge.html": "Golden Sun - The Lost Age",
  "games/clgoldminer.html": "Gold Miner",
  "games/clgolfsunday.html": "Golf Sunday",
  "games/clgoodboygalaxy.html": "Goodboy Galaxy",
  "games/clgooglebaseball.html": "Google Baseball",
  "games/clgoogledino.html": "Google Dino",
  "games/clgorescriptclassic.html": "Gorescript Classic",
  "games/clgranddad.html": "7 Grand Dad",
  "games/clgrandtheftautoadvance.html": "Grand Theft Auto Advance",
  "games/clgranny2.html": "Granny Online",
  "games/clgranny22.html": "Granny 2",
  "games/clgranny3.html": "Granny 3",
  "games/clgrannyy.html": "Granny",
  "games/clgranturismo.html": "Gran Turismo",
  "games/clgranturismo2.html": "Gran Turismo 2",
  "games/clgrassmowing.html": "Stone Grass Mowing Simulator",
  "games/clgravity.html": "Gravity",
  "games/clgravitymod.html": "Gravity Mod",
  "games/clgrey-box-testing.html": "Grey Box Testing",
  "games/clgrimacebirthday.html": "Grimace's Birthday",
  "games/clgrindcraft.html": "Grindcraft",
  "games/clgrn.html": "GRN",
  "games/clgrowagarden.html": "Grow A Garden",
  "games/clgrowdenio.html": "Growden.io",
  "games/clgrowyourgarden.html": "Grow Your Garden",
  "games/clgta.html": "Grand Theft Auto",
  "games/clgta2.html": "Grand Theft Auto 2",
  "games/clgta22.html": "Grand Theft Auto 2",
  "games/clgtachina.html": "Grand Theft Auto - Chinatown Wars",
  "games/clguesstheiranswer.html": "Guess Their Answer",
  "games/clgun-spin.html": "Gun Spin",
  "games/clgunblood.html": "Gun Blood",
  "games/clguncho.html": "Guncho",
  "games/clgunmayhem.html": "Gun Mayhem",
  "games/clgunmayhem2goof.html": "Gun Mayhem 2",
  "games/clgunmayhemredux.html": "Gun Mayhem Redux",
  "games/clgunnight.html": "Gun Night",
  "games/clgunsmoke.html": "Gun.smoke",
  "games/clgymstack.html": "Gym Stack",
  "games/clhacx.html": "Hacx",
  "games/clhajimeippo.html": "Hajime No Ippo - the Fighting",
  "games/clhalflife.html": "Half Life",
  "games/clhalocombatdevolved.html": "Halo Combat Devolved",
  "games/clhandshakes.html": "Handshakes",
  "games/clhandsofwar.html": "Hands of War",
  "games/clhandulum.html": "Handulam+",
  "games/clhanger2.html": "Hanger 2",
  "games/clhappyroom.html": "Happy Room",
  "games/clhappywheels.html": "Happy Wheels",
  "games/clhardwaretycoon.html": "Hardware Tycoon",
  "games/clHaroldsbadday.html": "Harold's Bad Day",
  "games/clharvestio.html": "Harvest.io",
  "games/clharvestmoon.html": "Harvest Moon",
  "games/clharvestmoon64.html": "Harvest Moon 64",
  "games/clhauntthehouse.html": "Haunt The House",
  "games/clheartandsoul.html": "Pokemon Heart & Soul",
  "games/clhei$t.html": "HEI$T",
  "games/clhelixjump.html": "Helix Jump",
  "games/clhellron.html": "HellroN",
  "games/clhelpnobrakes.html": "Help No Brakes!",
  "games/clheretic.html": "Heretic",
  "games/clhextris.html": "Hextris",
  "games/clhighstakes.html": "High Stakes",
  "games/clhighwayracer2.html": "Highway Racer",
  "games/clhillclimbracinglite.html": "Hill Climb Racing Lite",
  "games/clHiNoHomo.html": "Hi No Homo",
  "games/clhipsterkickball.html": "Hipster Kickball",
  "games/clhit8ox.html": "HIT8OX",
  "games/clhitsinglereal.html": "Friday Night Funkin Hit Single Real",
  "games/clhitstunfly.html": "HitStunFly",
  "games/clhl2doom.html": "Doom But It's Half Life 2",
  "games/clhobo.html": "Hobo",
  "games/clhobo2.html": "Hobo 2",
  "games/clhobo3.html": "Hobo 3",
  "games/clhobo4.html": "Hobo 4",
  "games/clhobo5.html": "Hobo 5",
  "games/clhobo6.html": "Hobo 6",
  "games/clhobo7.html": "Hobo 7",
  "games/clhobovszombies.html": "Hobo vs. Zombies",
  "games/clholeio.html": "Hole.io",
  "games/clhollowknight.html": "Hollow Knight Demake",
  "games/clhomesheephome.html": "Home Sheep Home",
  "games/clhotwax.html": "Hot Wax",
  "games/clhouseofhazards.html": "House of Hazards",
  "games/clhoverracerdrive.html": "Hover Racer Drive",
  "games/clhumanexpenditureprogram.html": "Human Expenditure Program",
  "games/clhungryknight.html": "Hungry Knight",
  "games/clhungrylamu.html": "Hungry Lamu",
  "games/clhyppersandbox.html": "Hypper Sandbox",
  "games/clicantbelievegoogleflaggedmeforthenameofthefilelol.html": "Riddle School 5",
  "games/clicedodo.html": "Ice Dodo",
  "games/clicypurplehead.html": "Icy Purple Head",
  "games/clidlebreakout.html": "Idle Breakout",
  "games/clidledice.html": "Idle Dice",
  "games/clidleidlegamedev.html": "Idle Idle Game Dev",
  "games/clidleminertycoon.html": "Idle Miner Tycoon",
  "games/climpossiblequiz.html": "The Impossible Quiz",
  "games/climpossiblequiz2.html": "The Impossible Quiz 2",
  "games/clinclementemerald.html": "Pokemon Inclement Emerald",
  "games/clinfinitecraft.html": "Infinite Craft",
  "games/clinkgame.html": "Ink Game",
  "games/clinnkeeper.html": "Innkeeper",
  "games/clinsidestory.html": "Mario & Luigi - Bowser's Inside Story",
  "games/clinteractivebuddy.html": "Interactive Buddy",
  "games/clintoruins.html": "Into Ruins",
  "games/clintospace.html": "Into Space",
  "games/clintospace2.html": "Into Space 2",
  "games/clintospace3.html": "Into Space 3",
  "games/clintothedeepweb.html": "Into The Deep Web",
  "games/clintrusion.html": "Intrusion",
  "games/cliqball.html": "IQ Ball",
  "games/clironsnout.html": "Iron Snout",
  "games/clironsoldier.html": "Iron Soldier",
  "games/clitgetssolonelyhere.html": "It Gets So Lonely Here",
  "games/cliwbtg.html": "I Wanna Be The Guy",
  "games/cljacksmithencryptedorsmthn.html": "Jacksmith",
  "games/cljailbreakobbbobob.html": "Jailbreak Obby",
  "games/cljefflings.html": "Jefflings",
  "games/cljellydadhero.html": "Jellydad Hero",
  "games/cljellydrift.html": "Jelly Drift",
  "games/cljellytruckgood.html": "Jelly Truck",
  "games/cljetforcegemini.html": "Jet Force Gemini",
  "games/cljetpackjoyride.html": "Jetpack Joyride",
  "games/cljetrush.html": "Jet Rush",
  "games/cljetskiracing.html": "Jetski Race",
  "games/cljohnnytrigger.html": "Johnny Trigger",
  "games/cljohnnyupgrade.html": "Johnny Upgrade",
  "games/cljourneydownhill.html": "Journey Downhill",
  "games/cljsvecx.html": "Jsvecx",
  "games/clJUMP.html": "JUMP",
  "games/cljumpingshell.html": "Jumping Shell",
  "games/cljustfalllol.html": "Justfall.lol",
  "games/cljusthitthebutton.html": "Just Hit The Button",
  "games/cljustoneboss.html": "Just One Boss",
  "games/clkaizomarioworld.html": "Kaizo Mario World",
  "games/clkalikan.html": "Kalikan",
  "games/clkapi.html": "Friday Night Funkin VS. KAPI",
  "games/clkaratebros.html": "Karate Bros",
  "games/clkarlson.html": "Karlson",
  "games/clkartbros.html": "Kart Bros",
  "games/clKenGriffeyJrPresentsMajorLeagueBaseball.html": "Ken Griffey jr. Presents Major League Baseball",
  "games/clkillerinstinct.html": "Killer Instinct",
  "games/clkillover.html": "Killover",
  "games/clkilltheiceagebabyadventure.html": "Kill The Ice Age Baby Adventure",
  "games/clkingdomheartsdays.html": "Kingdom Hearts - 358-2 Days",
  "games/clkingdomheartsrecoded.html": "Kingdom Hearts Re-Coded",
  "games/clkirby64.html": "Kirby 64",
  "games/clkirbyandtheamzingmirror.html": "Kirby and the Amazing Mirror",
  "games/clkirbysadventure.html": "Kirby's Adventure",
  "games/clkirbysdreamland.html": "Kirby's Dream Land",
  "games/clkirbysdreamland3.html": "Kirby's Dream Land 3",
  "games/clkirbysqueaksquad.html": "Kirby Squeak Squad",
  "games/clkirbysuperstar.html": "Kirby Super Star",
  "games/clkirbysuperstarultra.html": "Kirby Super Star Ultra",
  "games/clkittencannon.html": "Kitten Cannon",
  "games/clklifur.html": "Klifur",
  "games/clknightmaretower.html": "Knightmare Tower",
  "games/clkonkrio.html": "Konkr.io",
  "games/clkoopasrevenge.html": "A Koopa's Revenge",
  "games/clkourio.html": "Kour.io",
  "games/cllaceysflashgames.html": "Lacey's Flash Games",
  "games/cllastfirered.html": "Pokemon the Last Fire Red",
  "games/cllasthorizon.html": "Last Horizon",
  "games/clleaderstrike.html": "Leader Strike",
  "games/clleapandavoid2.html": "Leap And Avoid 2",
  "games/cllearntofly.html": "Learn to Fly",
  "games/cllearntofly2.html": "Learn to Fly 2",
  "games/cllearntofly3.html": "Learn to Fly 3",
  "games/cllearntoflyidle.html": "Learn to Fly Idle",
  "games/cllegobatman.html": "Lego Batman - the Videogame",
  "games/cllegobatman2superheroes.html": "Lego Batman 2 - DC Super Heroes",
  "games/cllegoindianajones.html": "Lego Indiana Jones - the Original Adventures",
  "games/cllegoindianajones2.html": "Lego Indiana Jones 2 - the Adventure Continues",
  "games/cllegoninjago.html": "Lego Ninjago - the Videogame",
  "games/cllegostarwars.html": "Lego Star Wars - the Complete Saga",
  "games/cllemmings.html": "Lemmings",
  "games/clleveldevil.html": "Level Devil",
  "games/clleverwarriors.html": "Lever Warriors",
  "games/cllinerider.html": "Line Rider",
  "games/cllinktothepast.html": "The Legend of Zelda a Link to the Past",
  "games/cllittlealchemy2.html": "Little Alchemy 2",
  "games/cllittlerunmo.html": "Little Runmo",
  "games/cllockthedoor.html": "Lock the Door",
  "games/clloderunner.html": "Lode Runner",
  "games/cllonewolf.html": "Lonewolf",
  "games/cllosangelesshark.html": "Los Angeles Shark",
  "games/cllowknight.html": "Low Knight",
  "games/clloz1.html": "The legend of Zelda",
  "games/cllozlinkawakening.html": "Legend of Zelda, the - Link's Awakening",
  "games/cllozminishcap.html": "The Legend of Zelda - Minish Cap",
  "games/cllozoracleofseasons.html": "Legend of Zelda, the - Oracle of Seasons",
  "games/cllozspirittracks.html": "Legend of Zelda, The - Spirit Tracks",
  "games/clluckyblocks.html": "Robby Blocks",
  "games/clmadalinstuntcarsmultiplayerfixed.html": "Madalin Stunt Cars Multiplayer",
  "games/clmadden93.html": "John Madden Football '93",
  "games/clmadden94.html": "Madden NFL '94",
  "games/clmadden95.html": "Madden NFL '95",
  "games/clmadden96.html": "Madden NFL '96",
  "games/clmadden99.html": "Madden NFL '99",
  "games/clmaddenfootball.html": "Madden Football",
  "games/clmaddenfootball64.html": "Madden Football 64",
  "games/clmaddennfl.html": "Madden NFL",
  "games/clmaddennfl2000.html": "Madden NFL 2000",
  "games/clmaddennfl2001.html": "Madden NFL 2001",
  "games/clmaddennfl2002.html": "Madden NFL 2002",
  "games/clmaddy98.html": "Madden NFL '98",
  "games/clmadness-retaliation.html": "Madness Retaliation",
  "games/clmadnessaccelerant.html": "Madness Accelerant",
  "games/clmadnesscombatdefense.html": "Madness Combat Defense",
  "games/clmadnesscombatnexus.html": "Madness Project Nexus",
  "games/clmadnessgemini.html": "Madness Gemini",
  "games/clmadnesshydraulic.html": "Madness Hydraulic",
  "games/clmadnessinteractive.html": "Madness Interactive",
  "games/clmadnessoffcolor.html": "Madness Off Color",
  "games/clmadnesspremediation.html": "Madness Premediation",
  "games/clmadnesss2010.html": "Madness 2010",
  "games/clmadnessstand.html": "Madness The Stand",
  "games/clmadskillsmotocross2.html": "Mad Skills Motocross 2",
  "games/clmadstick.html": "Mad Stick",
  "games/clmadstuntcars2.html": "Madalin Stunt Cars 2",
  "games/clmajorasmask.html": "The Legend of Zelda Majora's Mask",
  "games/clmakesureitsclosed.html": "Make Sure Its Closed",
  "games/clmanagod.html": "Mana God",
  "games/clmario3.html": "Super Mario Bros. 3",
  "games/clmario64webgl.html": "Super Mario 64 (webgl)",
  "games/clmarioandluigisuperstarsaga.html": "Mario & Luigi - Superstar Saga",
  "games/clmariocombat.html": "Mario Combat",
  "games/clmariogolf.html": "Mario Golf",
  "games/clMarioisMissingDoneRight.html": "Mario is Missing Done Right",
  "games/clmariokart64.html": "Mario Kart 64",
  "games/clmariokartsupercircuit.html": "Mario Kart Super Circuit",
  "games/clmariolostlevels.html": "Super Mario Bros. 2 - The Lost Levels",
  "games/clmariopaint.html": "Mario Paint",
  "games/clmarioparty.html": "Mario Party",
  "games/clmarioparty2.html": "Mario Party 2",
  "games/clmarioparty3.html": "Mario Party 3",
  "games/clmariopartyds.html": "Mario Party DS",
  "games/clmariosmysterymeat.html": "Mario's Mystery Meat",
  "games/clmariotennis.html": "Mario Tennis",
  "games/clmaskedforcesunlimited.html": "Masked Forces Unlimited",
  "games/clmastermindworldconquerer.html": "Mastermind World Conqueror",
  "games/clmatrixrampage.html": "Matrix Rampage",
  "games/clmattv2.html": "Wii Funkin' - VS Matt (v2)",
  "games/clmaxpayne.html": "Max Payne",
  "games/clmcfpsfbhd.html": "Madness Combat FPS Fueled by Hot Dogs",
  "games/clmcraerally.html": "Colin Mcrae Rally",
  "games/clmeatboy.html": "Meatboy",
  "games/clmeatboyflash.html": "Meatboy",
  "games/clmedalofhonor.html": "Medal Of Honor",
  "games/clmedievalshark.html": "Medieval Shark",
  "games/clmedievil.html": "MediEvil",
  "games/clmegachess.html": "Megachess",
  "games/clmegaman.html": "Mega Man",
  "games/clmegaman2.html": "Mega Man 2",
  "games/clmegaman2gba.html": "Mega Man 2",
  "games/clmegaman3.html": "Mega Man 3",
  "games/clmegaman4.html": "Mega Man 4",
  "games/clmegaman5.html": "Mega Man 5",
  "games/clmegaman6.html": "Mega Man 6",
  "games/clmegaman7.html": "Mega Man 7",
  "games/clmegaman8.html": "Mega Man 8",
  "games/clmegamanlegends.html": "Mega Man Legends",
  "games/clmegamanlegends2.html": "Mega Man Legends 2",
  "games/clmegamanx.html": "Mega Man X",
  "games/clmegamanx2.html": "Mega Man X2",
  "games/clmegamanx3.html": "Mega Man X3",
  "games/clmegamanx4.html": "Mega Man X4",
  "games/clmegamanzero.html": "Mega Man Zero",
  "games/clmegamanzx.html": "Mega Man ZX",
  "games/clmegaminer.html": "Mega Miner",
  "games/clmelonplayground.html": "Melon Playground",
  "games/clmeowuwu.html": "Tony Hawk's Pro Skater",
  "games/clmergeroundracers.html": "Merge Round Racers",
  "games/clmetalgear.html": "Metal Gear",
  "games/clmetalgearsolid.html": "Metal gear Solid",
  "games/clmetalgearsolidps.html": "Metal Gear Solid",
  "games/clmetalslug.html": "Metal Slug",
  "games/clmetalslug2.html": "Metal Slug 2",
  "games/clmetalslugadvance.html": "Metal Slug Advance",
  "games/clmetalslugmission1.html": "Metal Slug - 1st Mission",
  "games/clmetalslugmission2.html": "Metal Slug - 2nd Mission",
  "games/clMetalSonicHyperdrive.html": "Metal Sonic Hyperdrive",
  "games/clmetroid.html": "Metroid",
  "games/clmetroid2.html": "Metroid 2",
  "games/clmetroidfusion.html": "Metroid Fusion",
  "games/clmetroidzeromission.html": "Metroid Zero Mission",
  "games/clmiamishark.html": "Miami Shark",
  "games/clmightyknight.html": "Mighty Knight",
  "games/clmightyknight2.html": "Mighty Knight 2",
  "games/clmimic.html": "Mimic",
  "games/clmindscape.html": "Mindscape",
  "games/clminecraft1-8-8.html": "Minecraft 1.8 compressed (for code editors)",
  "games/clmineshooter.html": "Mine Shooter",
  "games/clminesweeperplus.html": "Minesweeper Plus",
  "games/clminhero.html": "Min Hero",
  "games/clminicrossword.html": "Mini Crossword",
  "games/clminishooters.html": "Mini Shooters",
  "games/clminitooth.html": "Mini Tooth",
  "games/clmiraginewar.html": "Miragine War",
  "games/clmisslecommand.html": "Missile Command",
  "games/clmk4ampedup.html": "Mario Kart 64 - Amped Up",
  "games/clmmwilywars.html": "Mega Man - The Wily Wars",
  "games/clmobiusrevolution.html": "Mobius Evolution",
  "games/clmoneyrush.html": "Money Rush",
  "games/clmonkeymart.html": "Monkey Mart",
  "games/clmonstertracks.html": "Monster Tracks",
  "games/clmonstertruckportstunt.html": "Monster Truck Port Stunt",
  "games/clmortalkombat.html": "Mortal Kombat",
  "games/clmortalkombat2.html": "Mortal Kombat 2",
  "games/clmortalkombat2a.html": "Mortal Kombat 2",
  "games/clmortalkombat3.html": "Mortal Kombat 3",
  "games/clmortalkombat3a.html": "Mortal Kombat 3",
  "games/clmortalkombat4.html": "Mortal Kombat 4",
  "games/clmortalkombata.html": "Mortal Kombat",
  "games/clmortalkombatadvance.html": "Mortal Kombat Advance",
  "games/clmortkom4.html": "Mortal Kombat 4",
  "games/clmotherload.html": "Motherload",
  "games/clmotoroadrash.html": "Moto Road Rash",
  "games/clmotox3m2.html": "MotoX3m2",
  "games/clmotox3m3.html": "MotoX3m3",
  "games/clmotox3mm.html": "MotoX3m",
  "games/clmotox3mpoolparty.html": "MotoX3m Pool Party",
  "games/clmotox3mspookyland.html": "MotoX3m Spooky Land",
  "games/clmotox3mwinter.html": "MotoX3m Winter",
  "games/clmountainbikeracer.html": "Mountain Bike Racer",
  "games/clmrracer.html": "Mr. Racer - Car Racing",
  "games/clmspacman.html": "Ms. Pac-man",
  "games/clmultitask.html": "Multitask",
  "games/clmutilate-a-doll.html": "Mutilate a Doll",
  "games/clmxoffroadmaster.html": "MX Offroad Master",
  "games/clmyfriendpedro.html": "My Friend Pedro",
  "games/clmyfriendpedroarena.html": "My Friend Pedro Arena",
  "games/clmyteardrop.html": "My Teardrop",
  "games/cln.html": "N",
  "games/clnarc.html": "Narc",
  "games/clnaturalselection.html": "Natural Selection",
  "games/clNBAhangtime.html": "NBA Hangtime",
  "games/clNBAjam.html": "NBA Jam",
  "games/clnbajamTE.html": "NBA Jam - Tournament Edition",
  "games/clnbalive2000.html": "NBA Live 2000",
  "games/clnblox.html": "Nblox",
  "games/clneonblaster.html": "Neon Blaster",
  "games/clneonrider.html": "Neon Rider",
  "games/clnesworldchampion.html": "Nintendo World Championships 1990",
  "games/clnetattack.html": "Net.Attack",
  "games/clneverendinglegacy.html": "Neverending Legacy",
  "games/clnewgroundsrumble.html": "Newgrounds Rumble",
  "games/clnewsupermariobros.html": "New Super Mario Bros",
  "games/clNewSuperMarioWorld2AroundtheWorld.html": "New Super Mario World 2 - Around the World",
  "games/clnewyorkshark.html": "New York Shark",
  "games/clnextdoor.html": "Nextdoor",
  "games/clnflblitz.html": "NFL Blitz",
  "games/clnfscarbonowncity.html": "Need For Speed - Carbon - Own the City",
  "games/clnfsmostwanted.html": "Need For Speed - Most Wanted",
  "games/clnfsporcheunleashed.html": "Need For Speed - Porsche Unleashed",
  "games/clnfsunderground.html": "Need For Speed - Underground",
  "games/clnfsunderground2.html": "Need For Speed - Underground 2",
  "games/clngon.html": "N-gon",
  "games/clnhl2002.html": "NHL 2002",
  "games/clnhl98.html": "NHL 98",
  "games/clnhlhitz2003.html": "NHL Hitz 2003",
  "games/clnickelodeonsuperbrawl2.html": "Nickelodeon Super Brawl 2",
  "games/clNicktoonsFreezeFrameFrenzy.html": "Nicktoons - Freeze Frame Frenzy",
  "games/clnightclubshowdown.html": "Nightclub Showdown",
  "games/clnightfire.html": "007 Nightfire",
  "games/clnightshade.html": "Nightshade",
  "games/clnimrods.html": "Nimrods",
  "games/clninjabrawl.html": "Ninja Brawl",
  "games/clnintendogslab.html": "Nintendogs - Lab & Friends",
  "games/clnintendoworldcup.html": "Nintendo World Cup",
  "games/clnitromemustdie.html": "Nitrome Must Die",
  "games/clnoobminer.html": "Noob Miner",
  "games/clnotyourpawn.html": "Not Your Pawn",
  "games/clnplus.html": "N+",
  "games/clnubbysnumberfactory.html": "Nubby's Number Factory",
  "games/clnullkevin.html": "10-103 Null Kevin",
  "games/clNutsandBoltsScrewingPuzzle.html": "Nuts and Bolts Screwing Puzzle",
  "games/clnzp.html": "Nazi Zombies Portable (nzp)",
  "games/clobby-99-will-lose.html": "Obby 99% Will Lose",
  "games/clobbyonlyup.html": "Obby Robby - Only Up",
  "games/clobeythegame.html": "Obey the Game",
  "games/clocarinaoftime.html": "The Legend of Zelda Ocarina of Time",
  "games/clofflineparadise.html": "Offline Paradise",
  "games/clomeganuggetclicker.html": "Omega Nugget Clicker",
  "games/clonebitadventure.html": "Onebit Adventure",
  "games/clonenightasfreddy.html": "One Night As Freddy",
  "games/clonepiece.html": "One Piece",
  "games/clonepiecefighting.html": "One Piece Fighting",
  "games/cloneshotold.html": "Oneshot (old)",
  "games/clonlyup.html": "Only Up",
  "games/clÖoo.html": "Öoo",
  "games/cloperius.html": "Operius",
  "games/cloppositeday.html": "Opposite Day",
  "games/clorbofcreation.html": "Orb of Creation",
  "games/clordinarysonicromhack.html": "An Ordinary Sonic rom Hack (sonic.exe)",
  "games/cloregontrail.html": "The Oregon Trail",
  "games/closu.html": "osu!",
  "games/clourpleguy.html": "Friday Night Funkin Vs. Ourple Guy v2",
  "games/clovo2.html": "OVO 2",
  "games/clovodimensions.html": "OVO 3 Dimensions",
  "games/clovofixed.html": "OVO",
  "games/clpacman.html": "Pac-man",
  "games/clpacmana.html": "Pac-man",
  "games/clpacmanworld3.html": "Pac-man World 3",
  "games/clpacmanworldg.html": "Pac-man World",
  "games/clpacmanworldpsx.html": "Pac-man World",
  "games/clpapabakeria.html": "Papa's Bakeria",
  "games/clpapadonut.html": "Papa's Donuteria",
  "games/clpapalouienighthunt2.html": "Papa Louie Night Hunt 2",
  "games/clpapalouiewhenburgersattack.html": "Papa Louie When Burgers Attack",
  "games/clpapalouiewhenpizzasattack.html": "Papa Louie When Pizzas Attack",
  "games/clpapalouiewhensundaesattack.html": "Papa Louie When Sundaes Attack",
  "games/clpapasburgerIIIAAAAA.html": "Papa's Burgeria",
  "games/clpapascheeseria.html": "Papa's Cheeseria",
  "games/clpapascupcakeria.html": "Papa's Cupcakeria",
  "games/clpapasfreezeria.html": "Papa's Freezeria",
  "games/clpapashotdoggeria.html": "Papa's Hot Doggeria",
  "games/clpapaspancakeria.html": "Papa's Pancakeria",
  "games/clpapaspastaria.html": "Papa's Pastaria",
  "games/clpapasscooperia.html": "Papa's Scooperia",
  "games/clpapassushiria.html": "Papa's Sushiria",
  "games/clpapastacomia.html": "Papa's Taco mia",
  "games/clpapaswingeria.html": "Papa's Wingeria",
  "games/clpaperio.html": "Paper.io",
  "games/clpaperio3d.html": "Paper.io 3D",
  "games/clpaperiomania.html": "Paper.io Mania",
  "games/clpapermario.html": "Paper Mario",
  "games/clpapermariopromode.html": "Paper Mario Pro Mode",
  "games/clpapermariottyd.html": "Paper Mario-TTYD Edition",
  "games/clparappatherapper.html": "Parappa the Rapper",
  "games/clparkingfury.html": "Parking Fury",
  "games/clparkingfury2.html": "Parking Fury 2",
  "games/clparkingfury3.html": "Parking Fury 3",
  "games/clparkingrush.html": "Parking Rush",
  "games/clpartnersintime.html": "Mario & Luigi - Partners In Time",
  "games/clpeacekeeper.html": "Peacekeeper",
  "games/clpeggle.html": "Peggle",
  "games/clpenaltykicks.html": "Penalty kicks",
  "games/clpenguindiner.html": "Penguin Diner",
  "games/clpenguinpass.html": "Penguin Pass",
  "games/clpepsiman.html": "Pepsiman",
  "games/clpereelous.html": "Pereelous",
  "games/clperfectdark.html": "Perfect Dark",
  "games/clperfecthotel.html": "Perfect Hotel",
  "games/clpersona.html": "Persona",
  "games/clpersona2.html": "Persona 2",
  "games/clphasma.html": "Phasma",
  "games/clpheonixjusticeforall.html": "Phoenix wright - Ace Attorney - Justice For All",
  "games/clpheonixtrialsandyear.html": "Phoenix wright - Ace Attorney - Trials and Tribulations",
  "games/clpicodriller.html": "Pico Driller",
  "games/clpicohot.html": "Pico Hot",
  "games/clpicolife.html": "Pico Life",
  "games/clpiconightpunkin.html": "Pico Night Punkin",
  "games/clpicosschool.html": "Pico's School",
  "games/clpicovsbeardx.html": "Pico Vs Bear DX",
  "games/clpiecesofcake.html": "Pieces of Cake",
  "games/clpingpongchaos.html": "Ping Pong Chaos",
  "games/clpinkbike.html": "Pinkbike",
  "games/clpitfall.html": "Pitfall!",
  "games/clpixelbattlegroundsio.html": "Pixel Battlegrounds.io",
  "games/clpixelcombat2.html": "Pixel Combat 2",
  "games/clpixelquestlostidols.html": "Pixel Quest - the Lost Idols",
  "games/clpixelshooter.html": "Pixel Shooter",
  "games/clpixelwarfare.html": "Pixel Warfare",
  "games/clpizzapapa.html": "Papa's Pizzeria",
  "games/clpizzatower.html": "Pizza Tower",
  "games/clplangman.html": "Plangman",
  "games/clplazmaburst.html": "Plazma Burst",
  "games/clplinko.html": "Plinko",
  "games/clplonky.html": "Plonky",
  "games/clpogo3D.html": "Pogo 3D",
  "games/clpokeallin.html": "Pokémon All In",
  "games/clpokebattlefact.html": "Pokemon Battle Factory",
  "games/clpokeblack.html": "Pokemon Black Version",
  "games/clpokeblazeblack2redux.html": "Pokemon Blaze Black 2 Redux",
  "games/clpokeblue.html": "Pokemon Blue Version",
  "games/clpokeclassic.html": "Pokéclassic",
  "games/clpokecrown.html": "Pokemon Crown",
  "games/clpokecrystalclear.html": "Pokemon Crystal Clear",
  "games/clpokediamond.html": "Pokemon - Diamond Version",
  "games/clpokedreamstone.html": "Pokemon Dreamstone",
  "games/clpokeeliteredux.html": "Pokemon Elite Redux",
  "games/clpokeelysiuma.html": "Pokemon Elysium A",
  "games/clpokeelysiumb.html": "Pokemon Elysium B",
  "games/clpokeemeraldenhanced.html": "Pokemon Emerald Enhanced",
  "games/clpokeemeraldhorizons.html": "Pokémon Emerald Horizons",
  "games/clpokeemeraldrandom.html": "Pokemon Emerald Randomized",
  "games/clpokeemeraldz.html": "Pokemon Emerald Z",
  "games/clpokefiregold.html": "Pokémon Fire Gold",
  "games/clpokeflora.html": "Pokemon Flora Sky",
  "games/clpokefuseddimension.html": "Pokemon Fused dimension",
  "games/clpokegaia.html": "Pokemon Gaia",
  "games/clpokegschronicles.html": "GS Chronicles",
  "games/clpokeheartgold.html": "Pokemon - Heartgold Version",
  "games/clpokelightplatinum.html": "Pokemon Light Platinum",
  "games/clpokeliquidcrysta.html": "Pokemon Liquid Crystal",
  "games/clpokemegamoemon.html": "Pokemon Mega Moemon",
  "games/clpokemonamnesia.html": "Pokemon Amnesia",
  "games/clpokemonclover.html": "Pokemon Clover",
  "games/clpokemoncrystal.html": "Pokemon Crystal",
  "games/clpokemonemerald.html": "Pokemon Emerald",
  "games/clpokemonemeraldcrest.html": "Pokemon Emerald Crest",
  "games/clpokemonemeraldimperium.html": "Pokemon Emerald Imperium",
  "games/clpokemonemeraldkaizo.html": "Pokemon Emerald Kaizo",
  "games/clpokemonemeraldmini.html": "Pokemon Emerald Mini",
  "games/clPokemonemeraldrouge.html": "Pokemon Emerald Rouge",
  "games/clpokemonemeraldseaglass.html": "Pokemon Emerald Seaglass",
  "games/clpokemonenergizedemerald.html": "Pokemon Energized Emerald",
  "games/clpokemonevolvedsfdgsdfs.html": "Pokemon Evolved",
  "games/clpokemonfirered.html": "Pokemon Firered",
  "games/clpokemonfireredrandomized.html": "Pokemon Firered Randomized",
  "games/clpokemongold.html": "Pokemon Gold",
  "games/clpokemonkaizoironfirered.html": "Pokemon Kaizo Iron Fire Red",
  "games/clpokemonlazarus.html": "Pokemon Lazarus",
  "games/clpokemonleafgreen.html": "Pokemon Leaf Green",
  "games/clpokemonmodernemerald.html": "Pokemon Modern Emerald",
  "games/clpokemonmysterydungeon.html": "Pokemon Mystery Dungeon",
  "games/clpokemonquetzal.html": "Pokemon Quetzal",
  "games/clpokemonroaringred.html": "Pokemon Roaring Red",
  "games/clPokemonrocketedition.html": "Pokemon Firered Rocket Edition",
  "games/clpokemonsapphire.html": "Pokemon Sapphire",
  "games/clpokemonshinsigma.html": "Pokemon Shiny Gold Sigma",
  "games/clpokemonsilver.html": "Pokemon Silver",
  "games/clpokemonsnap.html": "Pokemon Snap",
  "games/clpokemonstadium.html": "Pokemon Stadium",
  "games/clPokémonstunningsteel.html": "Pokemon Stunning Steel",
  "games/clpokemontowerdefense.html": "Pokemon Tower Defense",
  "games/clpokemonunbound.html": "Pokemon Unbound",
  "games/clpokemysteryexplorersofsky.html": "Pokemon Mystery Dungeon - Explorers of Sky",
  "games/clpokenameless.html": "Pokemon Nameless",
  "games/clpokeodyssey.html": "Pokemon Odyssey",
  "games/clpokepath.html": "PokéPath TD",
  "games/clpokepearl.html": "Pokemon - Pearl Version",
  "games/clpokeperfectfirered.html": "Pokémon Perfect Fire Red",
  "games/clpokepisces.html": "Pokemon Pisces",
  "games/clpokeplatinum.html": "Pokemon - Platinum Version",
  "games/clpokeplatinumrandomized.html": "Pokemon - Platinum Version Randomized",
  "games/clpokerechargedpink.html": "Pokémon Recharged Pink",
  "games/clpokerechargedyellow.html": "Pokémon Exceeded Emerald",
  "games/clpokerecordkeepers.html": "Pokémon Record Keepers",
  "games/clpokered.html": "Pokemon Red Version",
  "games/clpokerowe.html": "Pokemon ROWE",
  "games/clpokeruby.html": "Pokemon Ruby",
  "games/clpokerunandbun.html": "Pokemon Run and Bun",
  "games/clpokescorchedsilver.html": "Pokemon Scorched Silver",
  "games/clpokesoulsilver.html": "Pokemon - SoulSilver Version",
  "games/clpokethepit.html": "Pokémon Pit of 100 trials (generation 9)",
  "games/clpoketourmaline.html": "Pokémon Tourmaline Version",
  "games/clpokeultraviolet.html": "Pokemon Ultra Violet",
  "games/clpokeunovaemerald.html": "Pokémon Unova Emerald",
  "games/clpokevega.html": "Pokemon Vega",
  "games/clpokevoltwhite2redux.html": "Pokemon Volt White 2 Redux",
  "games/clpokevoyager.html": "Pokemon Voyager",
  "games/clpokewhite.html": "Pokemon White Version",
  "games/clpokewhite2.html": "Pokemon White Version 2",
  "games/clpokeyellow.html": "Pokemon Yellow Version",
  "games/clpolicepursuit2.html": "Police Pursuit 2",
  "games/clpolishedcrystal.html": "Pokémon Polished Crystal",
  "games/clpomgetsinternet.html": "Pom Gets Wi-Fi",
  "games/clpoorbunny.html": "Poor Bunny",
  "games/clpopeyepapi.html": "Popeye",
  "games/clporklike.html": "Porklike",
  "games/clportal.html": "Portal",
  "games/clportal2d.html": "Portal 2D",
  "games/clportaldefendersfastbreak.html": "Portal Defenders Fast Break",
  "games/clportaldefendersTD.html": "Portal Defenders Tower Defence",
  "games/clportalflash.html": "Portal Flash",
  "games/clporter.html": "Porter",
  "games/clpossessquest.html": "Possess Quest",
  "games/clpostal.html": "Postal",
  "games/clpotatomanseeksthetroof.html": "Potatoman Seeks The Troof",
  "games/clpowerslave.html": "Powerslave",
  "games/clpraxisfighterx.html": "Praxis Fighter X",
  "games/clprecivilationbronzeage.html": "Pre Civilization Bronze Age",
  "games/clprehistoricshark.html": "Prehistoric Shark",
  "games/clprimary.html": "Primary",
  "games/clpullfrog.html": "Pullfrog",
  "games/clpunchout.html": "Mike Tyson's Punch Out",
  "games/clpunchthetrump.html": "Punch the Trump",
  "games/clpuppethockey.html": "Puppet Hockey",
  "games/clpuppetmaster.html": "Puppet Master",
  "games/clpushyourluck.html": "Push Your Luck",
  "games/clpuyopuyofever.html": "Puyo Puyo Fever",
  "games/clpvz.html": "Plants vs. Zombies",
  "games/clpyrotoad.html": "Pyrotoad",
  "games/clqbert.html": "Q-bert",
  "games/clquake2.html": "Quake II",
  "games/clquake3.html": "Quake III Arena",
  "games/clquake64.html": "Quake 64",
  "games/clquickieworld.html": "Quickie World",
  "games/clqwop.html": "QWOP",
  "games/clradicalred.html": "Pokemon Radical Red",
  "games/clradracer.html": "Rad Racer",
  "games/clraftwars.html": "Raft Wars",
  "games/clraftwars2.html": "Raft Wars 2",
  "games/clragdoll-io.html": "Ragdoll.io",
  "games/clragdollarchers.html": "Ragdoll Archers",
  "games/clragdollhit.html": "Ragdoll Hit",
  "games/clragdollrunners.html": "Ragdoll Runners",
  "games/clragdollsoccer.html": "Ragdoll Soccer",
  "games/clrainbowsix.html": "Tom Clancy's Rainbow Six",
  "games/clray1.html": "Ray Part 1",
  "games/clray2.html": "Ray Part 2",
  "games/clrayman.html": "Rayman",
  "games/clraze.html": "Raze",
  "games/clraze2.html": "Raze 2",
  "games/clraze3.html": "Raze 3",
  "games/clre3.html": "Resident Evil 3",
  "games/clreachthecore.html": "Reach the Core",
  "games/clrealflightsim.html": "Real Flight Simulator",
  "games/clrebuild.html": "Rebuild",
  "games/clrebuild2.html": "Rebuild 2",
  "games/clrecoil.html": "Recoil",
  "games/clredalert.html": "Command and Conquer Red Alert",
  "games/clredball.html": "Red Ball",
  "games/clredball2.html": "Red Ball 2",
  "games/clredball3.html": "Red Ball 3",
  "games/clRedBall4.html": "Red Ball 4",
  "games/clredball4vol2.html": "Red Ball 4 vol.2",
  "games/clredball4vol3.html": "Red Ball 4 vol.3",
  "games/clredhanded.html": "Red Handed",
  "games/clredtierunner.html": "Red Tie Runner",
  "games/clredvsblue2.html": "Red vs. Blue",
  "games/clredvsbluewar.html": "Red vs. Blue War",
  "games/clreignofcentipede.html": "Reign of Centipede",
  "games/clrenegades.html": "Renegades",
  "games/clresidentevil.html": "Resident Evil",
  "games/clresidentevil2.html": "Resident Evil 2",
  "games/clresizer.html": "Resizer",
  "games/clresortempire.html": "Resort Empire",
  "games/clretrobowl.html": "Retro Bowl",
  "games/clretrobowlcollege.html": "Retro Bowl College",
  "games/clretrohighway.html": "Retro Highway",
  "games/clretropingpong.html": "Retro Ping Pong",
  "games/clreturnman.html": "Return Man",
  "games/clreturnman2.html": "Return Man 2",
  "games/clreturntoriddleschool.html": "Return to Riddle School",
  "games/clrevolutionidle.html": "Revolution Idle",
  "games/clrhythmheaven.html": "Rhythm Heaven",
  "games/clrhythymymheaven.html": "Rhythm Heaven",
  "games/clricochetkills2.html": "Ricochet Kills 2",
  "games/clriddlemiddleschool.html": "Riddle Middle School",
  "games/clriddleschool.html": "Riddle School",
  "games/clriddleschool2.html": "Riddle School 2",
  "games/clriddleschool3.html": "Riddle School 3",
  "games/clriddleschool445544444$$444$444.html": "Riddle School 4",
  "games/clriddletransfer.html": "Riddle Transfer",
  "games/clriddletransfer2.html": "Riddle Transfer 2",
  "games/clridgeracer.html": "Ridge Racer",
  "games/clristar.html": "Ristar",
  "games/clroadfighter.html": "Road Fighter",
  "games/clroadoffury.html": "Road of Fury",
  "games/clroadofthedead.html": "Road of the Dead",
  "games/clroadofthedead2.html": "Road of the Dead 2",
  "games/clrocketjump.html": "Rocket Jump",
  "games/clrocketknightadventures.html": "Rocket Knight Adventures",
  "games/clrocketleague.html": "Rocket League",
  "games/clrocketpult.html": "Rocketpult",
  "games/clrocketsoccerderby.html": "Rocket Soccer Derby",
  "games/clrodha.html": "Rodha",
  "games/clrollerballer.html": "Roller Baller",
  "games/clrollingsky.html": "Rolling Sky",
  "games/clrollyvortex.html": "Rolly Vortex",
  "games/clrolypolymonster.html": "Roly-Poly Monsters",
  "games/clrooftopsnipers.html": "Rooftop Snipers",
  "games/clrooftopsnipers2.html": "Rooftop Snipers 2",
  "games/clroomclicker.html": "Room Clicker",
  "games/clrouletteknight.html": "Roulette Knight",
  "games/clruffle.html": "Ruffle emulator",
  "games/clrun-2.html": "Run 2",
  "games/clrun.html": "Run",
  "games/clrun3.html": "Run 3",
  "games/clrunningfred.html": "Running Fred",
  "games/clrussiancardriver.html": "Russian Car Driver",
  "games/clsandboxels.html": "Sandboxels",
  "games/clsandsofthecoliseum.html": "Sands of the Coliseum",
  "games/clsandtris.html": "Sandtris",
  "games/clsantarun.html": "60 Seconds Santa Run",
  "games/clsaszombieassault2.html": "SAS Zombie Assault 2",
  "games/clsaulgoodmanrun.html": "Saul Goodman Run",
  "games/clscarletshift.html": "Scarlet Shift",
  "games/clscarymazegame.html": "Scary Maze Game",
  "games/clscaryteacher3d.html": "Scary Teacher 3D",
  "games/clscrapmetal3.html": "Scrap Metal 3",
  "games/clscrapyarddog.html": "Scrapyard Dog",
  "games/clscribblenauts.html": "Scribblenauts",
  "games/clscubabear.html": "Scuba Bear",
  "games/clseamongrel.html": "Sea Mongrel",
  "games/clsecretofmana.html": "Secret of Mana",
  "games/clsega2gg.html": "Sonic The Hedgehog 2",
  "games/clself.html": "Self",
  "games/clsentryfortress.html": "Sentry Fortress",
  "games/clserenitrove.html": "Serenitrove",
  "games/clserioussamadvance.html": "Serious Sam Advance",
  "games/clservingupmadness.html": "Serving Up Madness",
  "games/clsfk.html": "Strikeforce Kitty",
  "games/clsfk2.html": "Strikeforce Kitty 2",
  "games/clsfklaststand.html": "Strikeforce Kitty Last Stand",
  "games/clsfkleague.html": "Strikeforce Kitty League",
  "games/clshaggy.html": "Friday Night Funkin vs Shaggy",
  "games/clshc1.html": "Sift Heads Cartels Act 1",
  "games/clshc2.html": "Sift Heads Cartels Act 2",
  "games/clshc3.html": "Sift Heads Cartels Act 3",
  "games/clshift.html": "Shift",
  "games/clshift2.html": "Shift 2",
  "games/clshinmegamitenseidevilsurvivor.html": "Shin Megami Tensei Devil Survivor",
  "games/clshortlife.html": "Short Life",
  "games/clshotout4.html": "Shot Out 4",
  "games/clshredmill.html": "Shredmill",
  "games/clshredsauce.html": "Shredsauce",
  "games/clshrek-2.html": "Shrek 2",
  "games/clshwultimatem.html": "Sift Heads World Ultimatum",
  "games/clsideeffects.html": "Side Effects",
  "games/clsidepocket.html": "Side Pocket",
  "games/clsierra7.html": "Sierra 7",
  "games/clsilenthill.html": "Silent Hill",
  "games/clsiloshowdow.html": "Silhouette Showdown",
  "games/clsixwaystodie.html": "Six ways to die",
  "games/clskateit.html": "Skate It",
  "games/clskibididibidygyattohiorizzingallovertheplacestillwatermangotheoryfemboydrool.html": "Skibidi toilet.io",
  "games/clskibidiinthebackrooms.html": "Skibidi in the Backrooms",
  "games/clskibidishooter.html": "Skibidi Shooter",
  "games/clskong.html": "Hollow Knight Silksong Demake",
  "games/clskyrace-3d.html": "Sky Race 3D",
  "games/clsliceitall.html": "Slice It All",
  "games/clslideinthewoods.html": "Slide in the Woods",
  "games/clslimelabratory.html": "Slime Laboratory",
  "games/clslipways.html": "Slipways",
  "games/clslitherio.html": "Slither.io",
  "games/clslope2player.html": "Slope 2 player",
  "games/clslope3.html": "Slope 3",
  "games/clslopeplus.html": "Slope",
  "games/clslotornot.html": "Slot or Not",
  "games/clslowroads.html": "Slow Roads",
  "games/clsm63redux.html": "Super Mario 63 Redux",
  "games/clsm64hiddenstars.html": "Super Mario 64 The Hidden Stars",
  "games/clsmadvance2.html": "Super Mario Advance 2",
  "games/clsmadvance3.html": "Super Mario Advance 3",
  "games/clsmashkartsworking.html": "Smash Karts",
  "games/clsmashremix.html": "Smash Remix",
  "games/clsmbcrossover.html": "Super Mario Crossover",
  "games/clsmgds.html": "Super Mario Galaxy DS",
  "games/clsnailbob.html": "Snail Bob",
  "games/clsnailbob2.html": "Snail Bob 2",
  "games/clsnailbob3.html": "Snail Bob 3",
  "games/clsnailbob4space.html": "Snail Bob 4",
  "games/clsnailbob5lovestory.html": "Snail Bob 5 Love Story",
  "games/clsnakelike.html": "Snakelike",
  "games/clsnipershot.html": "Sniper Shot",
  "games/clsniperv2.html": "Sniper v2",
  "games/clsnowballio.html": "Snowball.io",
  "games/clsnowbros.html": "Snow Bros",
  "games/clsnowrider.html": "Snow Rider 3D",
  "games/clsnowriderrrr.html": "Alt Snow Rider",
  "games/clsnowroad.html": "Snow Road",
  "games/clsoccerbros.html": "Soccer Bros",
  "games/clsoccerrandomgood.html": "Soccer Random",
  "games/clsolarsandbox.html": "Solar Sandbox",
  "games/clsolarsmash.html": "Solar Smash",
  "games/clsolatrobo.html": "Solatorobo - Red the Hunter",
  "games/clsolitaire.html": "Solitaire",
  "games/clsonic1contemporary.html": "Sonic 1 Contemporary",
  "games/clSonic1ScoreRush.html": "Sonic 1 Score Rush",
  "games/clSonic2ScoreRush.html": "Sonic 2 Score Rush",
  "games/clsonic3andknuckles.html": "Sonic 3 And Knuckles",
  "games/clsonic3complete.html": "Sonic 3 Complete",
  "games/clsonic3dblastdx.html": "Sonic 3D Blast - Director's Cut",
  "games/clsonicadvance.html": "Sonic Advance",
  "games/clsonicadvance2.html": "Sonic Advance 2",
  "games/clsonicadvance2sp.html": "Sonic Advance 2 SP",
  "games/clsonicadvance3.html": "Sonic Advance 3",
  "games/clsonicandashuro.html": "Sonic and Ashuro",
  "games/clsonicandfallingstar.html": "Sonic And The Falling Star",
  "games/clsonicandknuckles.html": "Sonic and Knuckles",
  "games/clsonicbattle.html": "Sonic Battle",
  "games/clsoniccd.html": "Sonic CD",
  "games/clsonicclassiccollection.html": "Sonic Classic Collection",
  "games/clsonicclassicheroes.html": "Sonic Classic Heroes",
  "games/clsoniccolors.html": "Sonic Colors",
  "games/clsonicdeltaorigins.html": "Sonic Delta Origins",
  "games/clsoniceexeog.html": "Sonic.EXE Original",
  "games/clsonicerazor.html": "Sonic Erazor",
  "games/clsonicgg.html": "Sonic the Hedgehog",
  "games/clSonicHellfireSaga.html": "Sonic Hellfire Saga",
  "games/clsonicjam.html": "Sonic Jam",
  "games/clsonicmegamix.html": "Sonic Megamix",
  "games/clsonicr.html": "Sonic R",
  "games/clsonicrevert.html": "Sonic Revert",
  "games/clsonicrush.html": "Sonic Rush",
  "games/clsonicrushadventure.html": "Sonic Rush Adventure",
  "games/clsonicspinball.html": "Sonic Spinball",
  "games/clsonicthehedgehog.html": "Sonic the Hedgehog",
  "games/clsonicthehedgehog2.html": "Sonic the Hedgehog 2",
  "games/clsonicthehedgehog3.html": "Sonic the Hedgehog 3",
  "games/clsonny2.html": "Sonny 2",
  "games/clsouljumper.html": "Soul Jumper",
  "games/clspacebarclicker.html": "Spacebar Clicker",
  "games/clspacecompany.html": "Space Company",
  "games/clspaceinvaders.html": "Space Invaders",
  "games/clspaceiskey.html": "Space is Key",
  "games/clspaceiskey2.html": "Space is Key 2",
  "games/clspaceiskeyxmas.html": "Space is Key Xmas",
  "games/clspacewarsbattleground.html": "Space Wars BattleGround",
  "games/clspacewaves.html": "Space Waves",
  "games/clspeedperclick.html": "Speed Per Click",
  "games/clspeedstars.html": "Speed Stars",
  "games/clspelunky.html": "Spelunky Classic HD",
  "games/clspewer.html": "Spewer",
  "games/clspiralroll.html": "Spiral Roll",
  "games/clSpongebobPowerKartGrandPrix.html": "Spongebob PowerKart Grand Prix",
  "games/clsprunked.html": "Sprunked",
  "games/clsprunki.html": "Sprunki",
  "games/clsprunkiclicker.html": "Sprunki Clicker",
  "games/clsquidplayground.html": "Squid Playground",
  "games/clstackballio.html": "Stackball.io",
  "games/clstacktris.html": "Stacktris",
  "games/clstarfox.html": "Star Fox",
  "games/clstarfox64.html": "Star Fox 64",
  "games/clstarraiders.html": "Star Raiders",
  "games/clstateio.html": "State.io",
  "games/clstation141.html": "Station 141",
  "games/clstationmeltdown.html": "Station Meltdown",
  "games/clstationsaturn.html": "Station Saturn",
  "games/clsteakandjake.html": "Steak and Jake",
  "games/clstealbrainrot.html": "Another Steal a Brainrot",
  "games/clstealthassassin.html": "Stealth Assassin",
  "games/clstealthmaster.html": "Stealth Master",
  "games/clsteelempire.html": "Steel Empire",
  "games/clsteelsurge.html": "Steel Surge Revolution",
  "games/clstickarchersbattle.html": "Stick Archers Battle",
  "games/clstickdefenders.html": "Stick Defenders",
  "games/clstickfighter.html": "Stick Fighter",
  "games/clstickjetchallenge.html": "Stickjet Challenge",
  "games/clstickmanandguns.html": "Stickman and Guns",
  "games/clstickmanclash.html": "Stickman Clash",
  "games/clstickmanduel.html": "Stickman Duel",
  "games/clstickmangtacity.html": "Stickman gta City",
  "games/clstickmanhook.html": "Stickman Hook",
  "games/clStickmanKingdomclash.html": "Stickman Kingdom Clash",
  "games/clstickmankombat2d.html": "Stickman Kombat 2D",
  "games/clstickmanstealingdiamond.html": "Henry Stickmin Stealing The Diamond",
  "games/clstickmerge.html": "Stick Merge",
  "games/clstickminairship.html": "Henry Stickmin Infiltrating The Airship",
  "games/clstickminbreakingbank.html": "Henry Stickmin Breaking The Bank",
  "games/clstickminescapingprison.html": "Henry Stickmin Escaping The Prison",
  "games/clstickminfleecomplex.html": "Henry Stickmin Fleeing The Complex",
  "games/clstickrpgcomplete.html": "Stick RPG",
  "games/clstickslasher.html": "Stick Slasher",
  "games/clstickwar.html": "Stick War",
  "games/clstickwar2.html": "Stick War 2",
  "games/clstormthehouse.html": "Storm the House",
  "games/clstormthehouse2.html": "Storm the House 2",
  "games/clstormthehouse3.html": "Storm the House 3",
  "games/clstrangejournet.html": "Shin Megami Tensei Strange Journey",
  "games/clstreangeropepolice.html": "Amazing Strange Rope Police",
  "games/clstreetfighter2.html": "Street Fighter 2",
  "games/clstreetfighter2turbo.html": "Street Fighter 2 Turbo",
  "games/clstreetfighteralpha3.html": "Street Fighter Alpha 3",
  "games/clstreetfighterumuhsomething.html": "Super Street Fighter II Turbo Revival",
  "games/clstreetofrage.html": "Streets Of Rage",
  "games/clstreetofrage2.html": "Streets Of Rage 2",
  "games/clstreetofrage3.html": "Streets Of Rage 3",
  "games/clstrikeforceheroes.html": "Strike Force Heroes",
  "games/clstrikeforceheroes2.html": "Strike Force Heroes 2",
  "games/clstrikeforceheroes3.html": "Strike Force Heroes 3",
  "games/clstrikerdummies.html": "Striker Dummies",
  "games/clstylesavvy.html": "Style Savvy",
  "games/clsugarsugar.html": "Sugar Sugar",
  "games/clsuika.html": "Suika Game",
  "games/clsuikapico.html": "Suika Pico",
  "games/clsunandmoon.html": "The Sun and Moon",
  "games/clsuperbomberman.html": "Super Bomberman",
  "games/clsuperbomberman2.html": "Super Bomberman 2",
  "games/clsuperbomberman3.html": "Super Bomberman 3",
  "games/clsuperbomberman4.html": "Super Bomberman 4",
  "games/clsuperbomberman5.html": "Super Bomberman 5",
  "games/clsuperc.html": "Super C",
  "games/clsupercarrush.html": "Super Car Rush",
  "games/clsupercastlevaniaVI.html": "Super Castlevania IV",
  "games/clsuperchibiknight.html": "Super Chibi Knight",
  "games/clsupercold.html": "Supercold",
  "games/clsuperdarkdeception.html": "Super Dark Deception",
  "games/clsuperdiagonalmario2.html": "Super Diagonal mario 2",
  "games/clsuperfallingfred.html": "Super Falling Fred",
  "games/clsuperfighters.html": "Super Fighters",
  "games/clsuperhot.html": "Superhot",
  "games/clsuperhotlinemiami.html": "Superhot Line Miami",
  "games/clsuperhouseofdeadninjas.html": "Super House of Dead Ninjas",
  "games/clsuperislandadventure.html": "Super Adventure Island",
  "games/clsuperliquidsoccer.html": "Super Liquid Soccer",
  "games/clsupermario.html": "Super Mario Bros",
  "games/clsupermario63.html": "Super Mario 63",
  "games/clsupermario64.html": "Super Mario 64",
  "games/clsupermario64ds.html": "Super Mario 64 DS",
  "games/clsupermarioallstars.html": "Super Mario All Stars",
  "games/clsupermariobros.html": "Super Mario Bros",
  "games/clsupermariobros2.html": "Super Mario Advance",
  "games/clsupermariobros2us.html": "Super Mario Bros. 2",
  "games/clsupermariobros3.html": "Super Mario Advance 4",
  "games/clsupermariokart.html": "Super Mario Kart",
  "games/clsupermarioland.html": "Super Mario Land",
  "games/clsupermarioland2.html": "Super Mario Land 2",
  "games/clsupermariomon.html": "Super Mariomon",
  "games/clsupermariorpg.html": "Super Mario Rpg",
  "games/clsupermarioworld.html": "Super Mario World",
  "games/clsupermarioworld2.html": "Super Mario World 2 Yoshi's Island",
  "games/clSuperMarioWorldThe SecretOfThe7GoldenStatues.html": "Super Mario World the Secret of the 7 Golden Statues",
  "games/clsupermetroid.html": "Super Metroid",
  "games/clsupermonkeyballjr.html": "Super Monkey Ball jr",
  "games/clsupernoahsark3D.html": "Super Noah's Ark 3D",
  "games/clsuperoliverworld.html": "Super Oliver World",
  "games/clsuperpickleballadventure.html": "Super Pickleball Adventure",
  "games/clsuperpunchout.html": "Super Punch Out",
  "games/clsuperpuzzlefighter2turbo.html": "Super Puzzle Fighter II Turbo",
  "games/clsuperscribblenauts.html": "Super Scribblenauts",
  "games/clsupersmashbros.html": "Super Smash bros",
  "games/clsupersmashflash.html": "Super Smash Flash",
  "games/clsupersmashflash2.html": "Super Smash Flash 2",
  "games/clsupertiltbros.html": "Super Tilt Bros",
  "games/clsupitdept.html": "Steal A Brainrot",
  "games/clsurvevio.html": "Survev.io",
  "games/clsurvivalracev2.html": "Survival Race v2",
  "games/clsushicat.html": "Sushi Cat",
  "games/clsushiunroll.html": "Sushi Unroll",
  "games/clswitchblade.html": "Switchblade",
  "games/clswordandshieldultimateplus.html": "Pokemon Sword and Shield Ultimate Plus",
  "games/clswordfight.html": "Swordfight",
  "games/clswordsandsandals2.html": "Swords and Sandals",
  "games/clswordsandsouls.html": "Swords and Souls",
  "games/clsydneyshark.html": "Sydney Shark",
  "games/cltabletanks.html": "Table Tanks",
  "games/cltabletennisworldtour.html": "Table Tennis World Tour",
  "games/cltag-.html": "Tag",
  "games/cltagc3.html": "Also Tag",
  "games/clTaikonoTatsujin.html": "Taiko No Tatsujin",
  "games/cltaisei.html": "Taisei Project",
  "games/cltakeover.html": "Takeover",
  "games/cltankpixel.html": "Tank Pixel",
  "games/cltanukisunset.html": "Tanuki Sunset",
  "games/cltapper.html": "Tapper",
  "games/cltaproad.html": "Tap Road",
  "games/cltastyplanet.html": "Tasty Planet",
  "games/cltboilambeternal.html": "Binding of Isaac - Wrath of the Lamb Eternal Edition",
  "games/cltecmobowl.html": "Tecmo Bowl",
  "games/cltelephonetrouble.html": "Telephone Trouble",
  "games/cltelocation.html": "Telocation",
  "games/cltempest2000.html": "Tempest 2000",
  "games/cltempleofboom.html": "Temple of Boom",
  "games/cltemplerun2.html": "Temple Run 2",
  "games/cltempoverdose.html": "TEMPOVERDOSE",
  "games/clterra.html": "Terra",
  "games/clterritorialio.html": "Territorial.io",
  "games/cltetris.html": "Tetris",
  "games/cltetrisattack.html": "Tetris Attack",
  "games/cltetrisgba.html": "Tetris",
  "games/clthanksforremindingmeihadtofixthis.html": "Abandoned",
  "games/cltheclassroom.html": "The Classroom",
  "games/cltheclassroom2.html": "The Classroom 2",
  "games/cltheclassroom3.html": "The Classroom 3",
  "games/clthedeadseat.html": "The Deadseat",
  "games/clthedeepestsleep.html": "The Deepest Sleep",
  "games/cltheenchantedcave2.html": "The Enchanted Cave 2",
  "games/cltheimpossiblegame.html": "The Impossible Game",
  "games/cltheincrediblemachine.html": "The Incredible Machine",
  "games/clthelaststand.html": "The Last Stand",
  "games/clthelaststandunioncity.html": "The Last Stand Union City",
  "games/clthemaninthewindow.html": "The Man From The Window",
  "games/clthemepark.html": "Theme Park",
  "games/clthepit.html": "The Pit",
  "games/clthereisnofile.html": "There is No Game",
  "games/clthermomorph.html": "Thermomorph",
  "games/clthesodorrace.html": "The Sodor Race",
  "games/cltheyarecoming.html": "They Are Coming",
  "games/clthisistheonlylevel.html": "This is the Only Level",
  "games/clthisistheonlyleveltoo.html": "This is the Only Level Too",
  "games/clthreegoblets.html": "Three Goblets",
  "games/clthrowapotato.html": "Throw a Potato",
  "games/clthrowapotatoagain.html": "Throw a Potato Again",
  "games/clthwack.html": "Thwack",
  "games/cltiberiandawn.html": "Command and Conquer Tiberian Dawn",
  "games/cltimeshooter2.html": "Time Shooter 2",
  "games/cltimeshooter3.html": "Time Shooter 3",
  "games/cltimewarriors.html": "Timewarriors",
  "games/cltinyfishing.html": "Tiny Fishing",
  "games/cltmnt.html": "Teenage Mutant Ninja Turtles - Shredder's Re-Revenge",
  "games/cltoastarling.html": "To a Starling",
  "games/cltoasterball.html": "Toasterball",
  "games/cltommorowandyesterday.html": "Tomorrow And Yesterday",
  "games/cltomodachicollection.html": "Tomodachi Collection",
  "games/cltonyhawkskater2.html": "Tony Hawk's Pro Skater 2",
  "games/cltonyhawkskater4.html": "Tony Hawk's Pro Skater 4",
  "games/cltonyhawksunderground.html": "Tony Hawk's Underground",
  "games/cltoomanytypes.html": "Pokemon Too Many Types",
  "games/cltopspeedracing3d.html": "Top Speed Racing 3D",
  "games/cltosstheturtle.html": "Toss the Turtle",
  "games/cltotm.html": "Tomb of the Mask",
  "games/cltouhou.html": "Touhou 1 Touhou-Reiiden",
  "games/cltouhou2.html": "Touhou 2 Touhou-Fuumaroku",
  "games/cltouhou3.html": "Touhou 3 Touhou-Yumejikuu",
  "games/cltouhou4.html": "Touhou 4 Touhou-Gensokyou",
  "games/cltouhou5.html": "Touhou 5 Touhou-Kaikidan",
  "games/cltowerblocks.html": "Tower Blocks",
  "games/cltowercrash3d.html": "Tower Crash 3D",
  "games/cltownscraper.html": "Townscraper",
  "games/cltrace.html": "Trace",
  "games/cltrafficjam3d.html": "Traffic Jam 3D",
  "games/cltralalerotralalaescapetungtungtungsahur.html": "Tralalero Tralala Escape Tung Tung Tung Sahur",
  "games/cltrapthecat.html": "Trap The Cat",
  "games/cltrechoroustrials.html": "Treacherous Trials",
  "games/cltrechoroustrialspart2.html": "Treacherous Trials Part 2",
  "games/cltriachnid.html": "Triachnid",
  "games/cltripleplay2000.html": "Triple Play 2000",
  "games/cltriviacrack.html": "Trivia Crack",
  "games/cltrollfacequest1.html": "Troll Face Quest 1",
  "games/cltrollfacequest10.html": "Troll Face Quest 10",
  "games/cltrollfacequest11.html": "Troll Face Quest 11",
  "games/cltrollfacequest12.html": "Troll Face Quest 12",
  "games/cltrollfacequest13.html": "Troll Face Quest 13",
  "games/cltrollfacequest2.html": "Troll Face Quest 2",
  "games/cltrollfacequest3.html": "Troll Face Quest 3",
  "games/cltrollfacequest4.html": "Troll Face Quest 4",
  "games/cltrollfacequest5.html": "Troll Face Quest 5",
  "games/cltrollfacequest6.html": "Troll Face Quest 6",
  "games/cltrollfacequest7.html": "Troll Face Quest 7",
  "games/cltrollfacequest8.html": "Troll Face Quest 8",
  "games/cltrollfacequest9.html": "Troll Face Quest 9",
  "games/cltrucksim.html": "Indian Truck Simulator",
  "games/cltubejumpers.html": "Tube Jumpers",
  "games/cltungtungtungsahurobby.html": "Tung Tung Tung Sahur Obby",
  "games/cltunnelrush.html": "Tunnel Rush",
  "games/cltunnelrushbetter.html": "Better Tunnel Rush",
  "games/clturokdinosaurhunter.html": "Turok - Dinosaur Hunter",
  "games/cltwinshot.html": "Twin Shot",
  "games/cltwistedmetal.html": "Twisted Metal",
  "games/cltwistedmetal2.html": "Twisted Metal 2",
  "games/cltwoball3d.html": "Two Ball 3D",
  "games/clucds.html": "Other Car Driving Simulator",
  "games/cluckyblockobbyEUOPHRATESRIVER.html": "Lucky Blocks Obby",
  "games/clufoswampoddysey.html": "Ufo Swamp Odyssey",
  "games/clultimateassassian2.html": "Ultimate Assassin 2",
  "games/clultimateassassian3.html": "Ultimate Assassin 3",
  "games/clUltimatecardrivingsimulator.html": "Ultimate Car Driving Simulator",
  "games/clultimatemortalkombat.html": "Ultimate Mortal Kombat",
  "games/clultimatemortalkombat3.html": "Ultimate Mortal Kombat 3",
  "games/clultrakill.html": "Ultrakill (buggy)",
  "games/clumstickmangameidkiforgor.html": "Animator Vs Animation Game (Special Edition)",
  "games/cluncannycatgolf.html": "Uncanny Cat Golf",
  "games/clunderneath.html": "Underneath",
  "games/clundertaleyellow.html": "Undertale Yellow",
  "games/clunfairmarioworkquestionmark.html": "Unfair Mario",
  "games/clunfairundyne.html": "Unfair Undyne",
  "games/clunicyclehero.html": "Unicycle Hero",
  "games/clunitresdreams.html": "Unitres Dreams",
  "games/cluno.html": "Uno",
  "games/cluntime.html": "Untime",
  "games/clupgradecomplete.html": "Upgrade Complete",
  "games/clupgradecomplete2.html": "Upgrade Complete 2",
  "games/clupslash.html": "UpSlash",
  "games/clUZG.html": "UZG",
  "games/clvampiresurvivors.html": "Vampire Survivors",
  "games/clvanguard.html": "Vanguard",
  "games/clvaportrails.html": "Vapor Trails",
  "games/clvex.html": "Vex",
  "games/clvex2.html": "Vex 2",
  "games/clvex3.html": "Vex 3",
  "games/clvex3xmas.html": "Vex 3 Xmas",
  "games/clvex4.html": "Vex 4",
  "games/clvex5.html": "Vex 5",
  "games/clvex6.html": "Vex 6",
  "games/clvex7.html": "Vex 7",
  "games/clvex8.html": "Vex 8",
  "games/clvexchallenges.html": "Vex Challenges",
  "games/clvexx3m.html": "Vex x3m",
  "games/clvexx3m2.html": "Vex x3m 2",
  "games/clvillager.html": "Villager",
  "games/clvincentmansionofthedead.html": "Vincent Mansion Of The Dead",
  "games/clvisitor.html": "The Visitor",
  "games/clvolleyrandom.html": "Volley Random",
  "games/clvollyballchallenge.html": "Volleyball Challenge",
  "games/clvvvvvv.html": "VVVVVV",
  "games/clwaluigitacostand.html": "Waluigi's Taco Stand",
  "games/clwarfare1944.html": "Warfare 1944",
  "games/clwarioland4.html": "Wario Land 4",
  "games/clwariowarediy.html": "Warioware D.I.Y",
  "games/clwariowareinc.html": "Wario Ware inc",
  "games/clwartheknight.html": "War the Knight",
  "games/clwaterpoolio.html": "Waterpool.io",
  "games/clwavedash.html": "Wave Dash",
  "games/clwaverace64.html": "Wave Race 64",
  "games/clwaverun.html": "Wave Run",
  "games/clwebecomewhatwebehold.html": "We Become What We Behold",
  "games/clwebfishing.html": "Webfishing",
  "games/clweltling.html": "Weltling",
  "games/clwermhole.html": "Wermhole",
  "games/clwhackthetheif.html": "Whack the Thief",
  "games/clwhackyourboss.html": "Whack Your Boss",
  "games/clwhackyourcomputer.html": "Whack Your Computer",
  "games/clwheeliebike.html": "Wheelie Bike",
  "games/clwheely.html": "Wheely",
  "games/clwheely2.html": "Wheely 2",
  "games/clwheely3.html": "Wheely 3",
  "games/clwheely4.html": "Wheely 4",
  "games/clwheely5.html": "Wheely 5",
  "games/clwheely6.html": "Wheely 6",
  "games/clwheely7.html": "Wheely 7",
  "games/clwheely8.html": "Wheely 8",
  "games/clwindowsdoors.html": "Windows Doors",
  "games/clwinterfalling.html": "Winter Falling",
  "games/clwipeout2097.html": "Wipeout 2097",
  "games/clwitchcrafttd.html": "Witchcraft td",
  "games/clwolfenstein.html": "Wolfenstein 3D Emscripten",
  "games/clwolfenstein3d.html": "Wolfenstein 3D",
  "games/clwoodworm.html": "Woodworm",
  "games/clwordle.html": "Wordle",
  "games/clworldcup98.html": "FIFA World Cup 98",
  "games/clworldshardestgame.html": "World's Hardest Game",
  "games/clworldshardestgame2.html": "World's Hardest Game 2",
  "games/clworldshardestgame3.html": "World's Hardest Game 3",
  "games/clworldshardestgame4.html": "World's Hardest Game 4",
  "games/clwrassling.html": "Wrassling",
  "games/clwrestlebros.html": "Wrestle Bros",
  "games/clXevious.html": "Xevious",
  "games/clyanderesimulator.html": "Yandere Simulator",
  "games/clyarsrevenge.html": "Yar's Revenge",
  "games/clyellow.html": "Yellow",
  "games/clYoshisStrangeQuest.html": "Yoshi's Strange Quest",
  "games/clyouarelucky.html": "You Are Lucky",
  "games/clyouvs100skibidi.html": "You vs. 100 Skibidi",
  "games/clyumenikki.html": "Yume Nikki",
  "games/clzdoom.html": "ZDoom",
  "games/clzelda2thelegendoflink.html": "Zelda 2 the Legend of Link",
  "games/clzenword.html": "Zen Word",
  "games/clzoinkz.html": "Zoikz Defender",
  "games/clzombieexploder.html": "Zombie Exploder",
  "games/clzombieroad.html": "Zombie Road",
  "games/clzombierush.html": "Zombie Rush",
  "games/clzombiesatemyneighboors.html": "Zombies Ate My Neighbors",
  "games/clzombopaclypse2.html": "Zombocalypse 2",
  "games/clzombotron.html": "Zombotron",
  "games/clzombotron2.html": "Zombotron 2",
  "games/clzombotronreboot.html": "Zombotron Reboot",
  "games/clzrist.html": "Zrist",
  "games/clzuma.html": "Zuma",
  "games/clʘ.html": "ʘ"
};
